//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSET_MRP
    {
        public string MRP_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string DEPT_CODE { get; set; }
        public string MRP_YMD { get; set; }
        public string MRP_NAEM { get; set; }
        public short PRI { get; set; }
        public string MRP_STATUS { get; set; }
        public decimal TOTAL_COST { get; set; }
        public System.DateTime NEED_DATE { get; set; }
        public string MEMO { get; set; }
        public System.DateTime CRT_TIME { get; set; }
        public string CRT_USER { get; set; }
    }
}
