//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSET_MOBILE
    {
        public string MOBILE_ID { get; set; }
        public string DEPT_CODE { get; set; }
        public string PHONE { get; set; }
        public string SN { get; set; }
        public short ENABLE { get; set; }
        public Nullable<System.DateTime> LAST_TIME { get; set; }
        public string MEMO { get; set; }
    }
}
