//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRIDGE_MSG
    {
        public string MSG_ID { get; set; }
        public short MSG_CAT { get; set; }
        public string NOTICE_ID { get; set; }
        public string ISSUE_DEPT_CODE { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public string SIGN_DEPT_CODE { get; set; }
        public Nullable<System.DateTime> SIGN_DATE { get; set; }
        public string RECEIVER { get; set; }
        public string PLAN_ID { get; set; }
        public string MEMO { get; set; }
        public Nullable<System.DateTime> CRT_TM { get; set; }
        public string CRT_NAME { get; set; }
    }
}
