//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRIDGE_EQU_DATA_TEMP
    {
        public string REPORT_ID { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string EQU_CAT { get; set; }
        public short EQU_ORDER { get; set; }
        public Nullable<int> EQU_TOTAL { get; set; }
        public Nullable<int> EQU_SCORE { get; set; }
        public Nullable<decimal> PERCENT_SCORE { get; set; }
        public Nullable<int> EQU_PASS { get; set; }
        public Nullable<decimal> PERCENT_PASS { get; set; }
        public Nullable<int> EQU_DISPASS { get; set; }
        public Nullable<decimal> PERCENT_DISPASS { get; set; }
        public Nullable<int> NOTICE_ISSUE { get; set; }
        public Nullable<int> NOTICE_SIGN { get; set; }
        public Nullable<int> PROBLEM_REPAIR { get; set; }
        public Nullable<System.DateTime> REPORT_DATE { get; set; }
        public string MEMO { get; set; }
    }
}
