//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRIDGE_MAINTENAN_NOTICE
    {
        public string NOTICE_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string CJ_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string CHECK_GQ_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public decimal CENTER_MILE { get; set; }
        public string EQU_CAT { get; set; }
        public string EQU_CODE { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public Nullable<System.DateTime> ACCESS_DATE { get; set; }
        public Nullable<System.DateTime> EVALUATE_DATE { get; set; }
        public string ISSUE_DEPT { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public Nullable<short> NOTICE_STATUS { get; set; }
        public string MEMO { get; set; }
        public string ISSUER { get; set; }
        public string EQU_NAME { get; set; }
        public Nullable<System.DateTime> ACTUAL_PROC_DATE { get; set; }
    }
}
