//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRIDGE_LRON_OVERPASS
    {
        public string LRON_OVERPASS_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string CJ_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public decimal CENTER_MILE { get; set; }
        public string BRIDGE_NAME { get; set; }
        public string BRIDGE_CODE { get; set; }
        public string HOLESPAN_STYLE { get; set; }
        public string BRIDGE_SECTION { get; set; }
        public string ROAD_LINENAME { get; set; }
        public Nullable<decimal> ROAD_MILE { get; set; }
        public string HOLE_POSITION { get; set; }
        public string MEMO { get; set; }
    }
}
