//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRIDGE_LIMITOVERHEAD
    {
        public string LIMITOVERHEAD_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string CJ_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public decimal CENTER_MILE { get; set; }
        public string RUN_STATUS { get; set; }
        public string HOLESPAN_STYLE { get; set; }
        public string CULVERT_CLEANHEIGHT { get; set; }
        public string CROSS_TYPE { get; set; }
        public string CROSS_HOLETYPE { get; set; }
        public string STRUCTSTYLE_STAND { get; set; }
        public string STRUCTSTYLE_SIMPLE { get; set; }
        public Nullable<decimal> LIMITOVERHEAD_NUM { get; set; }
        public string LIMITOVERHEAD_CLEANHEIGHT { get; set; }
        public Nullable<decimal> LIMITCARD_NUM { get; set; }
        public Nullable<decimal> CLEANWIDTH_LEFT { get; set; }
        public Nullable<decimal> CLEANWIDTH_RIGHT { get; set; }
        public Nullable<decimal> DISTANCE_LEFT { get; set; }
        public Nullable<decimal> DISTANCE_RIGHT { get; set; }
        public string HIT_IF { get; set; }
        public Nullable<decimal> ROAD_WIDTH { get; set; }
        public string ROAD_MATERIAL { get; set; }
        public string ROAD_LEVEL { get; set; }
        public string ROAD_NAME { get; set; }
        public string MEMO { get; set; }
    }
}
