//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURVE_BASE
    {
        public string PKID { get; set; }
        public string C_GWD_CODE { get; set; }
        public string C_DEP_CODE { get; set; }
        public string C_LINE_CODE { get; set; }
        public string C_LINE_DIR { get; set; }
        public string C_LINE_CAT { get; set; }
        public string C_RUN_STATUS { get; set; }
        public Nullable<decimal> N_START_MILE { get; set; }
        public Nullable<decimal> N_END_MILE { get; set; }
        public string C_LONGCHAIN_MARK { get; set; }
        public string C_CURVE_DIR { get; set; }
        public Nullable<decimal> N_CURVE_RADIUS { get; set; }
        public Nullable<decimal> N_DEFLECTION_ANGLE { get; set; }
        public string C_GAUGE_TYPE { get; set; }
        public Nullable<short> N_GAUGE_WIDEN { get; set; }
        public Nullable<short> N_SUPHIGH { get; set; }
        public Nullable<decimal> N_SLOPE_RATE { get; set; }
        public Nullable<decimal> N_START_TANGENT { get; set; }
        public Nullable<short> N_START_ALLAYLINE { get; set; }
        public Nullable<short> N_END_ALLAYLINE { get; set; }
        public Nullable<decimal> N_END_TANGENT { get; set; }
        public Nullable<decimal> N_CURVE_FULLLEN { get; set; }
        public Nullable<short> N_AVG_SPEED { get; set; }
        public Nullable<decimal> N_SORT_RADIUS { get; set; }
        public string C_JOINTLESS_TRACK { get; set; }
        public string SLEEPERTYPE { get; set; }
        public Nullable<decimal> SLEEPERCONFIG { get; set; }
        public string ACCESSORYTYPE { get; set; }
        public Nullable<System.DateTime> T_CRT_TM { get; set; }
        public string C_CRT_NAME { get; set; }
        public Nullable<decimal> N_ORDER { get; set; }
        public string C_MEMO { get; set; }
        public Nullable<decimal> ISSMALLCURVE { get; set; }
    }
}
