//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLOODPOINT
    {
        public FLOODPOINT()
        {
            this.TYPEFLOOD_PHOTO = new HashSet<TYPEFLOOD_PHOTO>();
        }
    
        public string PKID { get; set; }
        public string 线名 { get; set; }
        public string 区间 { get; set; }
        public Nullable<decimal> 起点里程 { get; set; }
        public Nullable<decimal> 终点里程 { get; set; }
        public Nullable<decimal> 长度 { get; set; }
        public string 行别 { get; set; }
        public string 侧别 { get; set; }
        public string 病害种类 { get; set; }
        public string 级别 { get; set; }
        public string 病害情况 { get; set; }
        public string 备注 { get; set; }
    
        public virtual ICollection<TYPEFLOOD_PHOTO> TYPEFLOOD_PHOTO { get; set; }
    }
}
