//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRAIL_CURVE
    {
        public string CURVE_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string CJ_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public string LINE_CAT { get; set; }
        public string RUN_STATUS { get; set; }
        public decimal START_MILE { get; set; }
        public decimal END_MILE { get; set; }
        public string LONGCHAIN_MARK { get; set; }
        public string CURVE_DIR { get; set; }
        public Nullable<decimal> CURVE_RADIUS { get; set; }
        public Nullable<decimal> DEFLECTION_ANGLE { get; set; }
        public string GAUGE_TYPE { get; set; }
        public Nullable<short> GAUGE_WIDEN { get; set; }
        public Nullable<short> SUPHIGH { get; set; }
        public Nullable<decimal> SLOPE_RATE { get; set; }
        public Nullable<decimal> START_TANGENT { get; set; }
        public Nullable<short> START_ALLAYLINE { get; set; }
        public Nullable<short> END_ALLAYLINE { get; set; }
        public Nullable<decimal> END_TANGENT { get; set; }
        public Nullable<decimal> CURVE_FULLLEN { get; set; }
        public Nullable<short> AVG_SPEED { get; set; }
        public Nullable<decimal> SORT_RADIUS { get; set; }
        public string MEMO { get; set; }
    }
}
