//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_MSG_BATCHREPLY
    {
        public string PKID { get; set; }
        public string SENDFKID { get; set; }
        public string REPLYMSG { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string FILE_PATH { get; set; }
        public string THUMBNAIL_PATH { get; set; }
        public Nullable<int> TYPE { get; set; }
    
        public virtual JOB_MSG_BATCHSEND JOB_MSG_BATCHSEND { get; set; }
    }
}
