//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_PLAN_DELINGHA_FILL
    {
        public string FILL_ID { get; set; }
        public Nullable<System.DateTime> FILL_DATE { get; set; }
        public string CJ_NAME { get; set; }
        public string FILL_PEOPLE { get; set; }
        public string DEMO { get; set; }
        public Nullable<short> STATU { get; set; }
        public Nullable<System.DateTime> CRT_TIME { get; set; }
        public string DEPCODE { get; set; }
        public Nullable<decimal> SUBSTA { get; set; }
        public string PLAN_TYPE { get; set; }
        public Nullable<decimal> APPROVE_CONTROL { get; set; }
        public Nullable<decimal> APPROVE_CHAIRMAN { get; set; }
        public Nullable<decimal> APPROVE_LINE { get; set; }
    }
}
