//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_PLAN_APPROVAL
    {
        public string PLAN_ID { get; set; }
        public string STATION_CODE { get; set; }
        public string STATION_NAME { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_NAME { get; set; }
        public string DIRECTION { get; set; }
        public Nullable<decimal> MILEAGE { get; set; }
        public Nullable<System.DateTime> PUSH_TIME { get; set; }
        public string CONSTRUCT_PROJECT { get; set; }
        public Nullable<System.DateTime> CONSTRUCT_START_TIME { get; set; }
        public Nullable<System.DateTime> CONSTRUCT_END_TIME { get; set; }
        public Nullable<long> CONSTRUCT_NUM { get; set; }
        public Nullable<long> JOBNUM_WORKER { get; set; }
        public Nullable<long> JOBNUM_AUXILIARY { get; set; }
        public string CARRY_TOOLS { get; set; }
        public string CONSTRUCT_DPT_CODE { get; set; }
        public string CONSTRUCT_DPT { get; set; }
        public string CONSTRUCT_CHARGE { get; set; }
        public string CONSTRUCT_PHONE { get; set; }
        public string JOBHEAD_PUBLIC { get; set; }
        public string JOBHEAD_COOPERATE { get; set; }
        public Nullable<decimal> MARS_LONGITUDE { get; set; }
        public Nullable<decimal> MARS_LATITUDE { get; set; }
        public string APPROVAL_LEVELS { get; set; }
        public string REPAIR_LEVEL { get; set; }
        public string WORKSHOP { get; set; }
        public string JOBTEAM_MAINBODY { get; set; }
        public string JOBTEAM_PUBLIC { get; set; }
        public string JOBTEAM_COOPERATE { get; set; }
        public string JOB_TYPE { get; set; }
        public string JOB_ADDRESS { get; set; }
        public string REGISTRATION_STATION { get; set; }
        public string GUARD_STATION { get; set; }
        public string LOADCAR_STATION { get; set; }
        public string INSPECTOR { get; set; }
        public string OTHER_UNIT { get; set; }
        public string IF_ZFCZK { get; set; }
        public string JOB_REASON { get; set; }
        public string JOB_CONTENT { get; set; }
        public string WORKLOAD { get; set; }
        public string DEFEND_CHARGE { get; set; }
        public string DEFEND_PHONE { get; set; }
        public string DEFEND_WORKSIT { get; set; }
        public string DEFEND_PLACE { get; set; }
        public string JOBINS_ORGCON { get; set; }
        public string RAIN_BDYSFYLYCPH { get; set; }
        public string RAIN_XLTCSFYLYC { get; set; }
        public string IF_LINE { get; set; }
        public string APPROVAL_SECTION { get; set; }
        public string APPROVAL_EXECUTIVE { get; set; }
        public string APPROVAL_WORKS { get; set; }
        public string CONFIRMATION_CODE { get; set; }
        public string PLAN_TYPE { get; set; }
    
        public virtual SYS_DEPT SYS_DEPT { get; set; }
        public virtual JOB_PLAN_TYPE JOB_PLAN_TYPE { get; set; }
    }
}
