//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEDGER_BIGEQUI_TECHPARAM
    {
        public string PKID { get; set; }
        public string SBFL { get; set; }
        public string SBSL { get; set; }
        public string SBMC { get; set; }
        public string XHGG { get; set; }
        public string SCDW { get; set; }
        public string ZYZX { get; set; }
        public string ZYFW { get; set; }
        public string ZYTJ { get; set; }
        public string GW { get; set; }
        public string GZ { get; set; }
        public string DC { get; set; }
        public string ZYXL { get; set; }
        public string GJ { get; set; }
        public string XLZDCG { get; set; }
        public string XLZXPD { get; set; }
        public string ZXZYQXBJ { get; set; }
        public string ZXYXQXBJ { get; set; }
        public string HJWD { get; set; }
        public string TSHJ { get; set; }
        public string LXGZSJ { get; set; }
        public string FDJ { get; set; }
        public string FDJ_XHGG { get; set; }
        public string FDJ_BJCJ { get; set; }
        public string FDJ_SL { get; set; }
        public string FDJ_EDGL { get; set; }
        public string FDJ_EDZS { get; set; }
        public string FDJ_ZDNJ { get; set; }
        public string FDJ_RYXHL { get; set; }
        public string YJFDJEDGL { get; set; }
        public string ZDFS { get; set; }
        public string BSX { get; set; }
        public string BSX_XHGG { get; set; }
        public string BSX_BJCJ { get; set; }
        public string BSX_SL { get; set; }
        public string FDJZ { get; set; }
        public string FDJZ_XHGG { get; set; }
        public string FDJZ_BJCJ { get; set; }
        public string FDJZ_SL { get; set; }
        public string FDJZ_FDJZEDGL { get; set; }
        public string FDJZ_ZFDJGL { get; set; }
        public string FZFDJZ { get; set; }
        public string FZFDJZ_XHGG { get; set; }
        public string FZFDJZ_BJCJ { get; set; }
        public string FZFDJZ_SL { get; set; }
        public string FZFDJZ_EDGL { get; set; }
        public string FZFDJZ_GL { get; set; }
        public string WXCC { get; set; }
        public string ZJZL { get; set; }
        public string ZGSXZXSD { get; set; }
        public string ZGZXSD { get; set; }
        public string ZGLGSD { get; set; }
        public string ZXJXPJ { get; set; }
        public string ZXJXPD_YS { get; set; }
        public string ZXJXPD_SW { get; set; }
        public string ZXJXPD_YSW { get; set; }
        public string GZXCZXJZJ { get; set; }
        public string ZXJGDZJ { get; set; }
        public string ZXJPJCLXCQZJ { get; set; }
        public string CXCZHZXJZXJ { get; set; }
        public string CLXCQHZJ { get; set; }
        public string YSCXPJ { get; set; }
        public string ECXPJ { get; set; }
        public string CGXS { get; set; }
        public string HCZZ { get; set; }
        public string ZYXZDFS { get; set; }
        public string JJZDJL { get; set; }
        public string ZYZXZDFS { get; set; }
        public string ZYZXSD { get; set; }
        public string ZYXL_ONE { get; set; }
        public string CQZYKD { get; set; }
        public string MZZDZYKD { get; set; }
        public string ZDWJSD { get; set; }
        public string ZDZYSD { get; set; }
        public string WJZZXS { get; set; }
        public string WJZZGL { get; set; }
        public string SFZZQDGL { get; set; }
        public string SWYXMJ { get; set; }
        public string SWCS { get; set; }
        public string SKCC { get; set; }
        public string DZHTDZDBJKD { get; set; }
        public string HZWTSSDBJ { get; set; }
        public string YGZDXC { get; set; }
        public string MTSL { get; set; }
        public string CZL { get; set; }
        public string BPZX { get; set; }
        public string SLZJ { get; set; }
        public string DMDJGL { get; set; }
        public string MTHXTJL { get; set; }
        public string MTBJTJL { get; set; }
        public string MTYGGZXJJ { get; set; }
        public string MBPJDMSD { get; set; }
        public string ZYJD { get; set; }
        public string ZXSP { get; set; }
        public string HXSP { get; set; }
        public string ZSBD { get; set; }
        public string QDSPL { get; set; }
        public string CLXXJD { get; set; }
        public string WDZZJZPL { get; set; }
        public string WDZZZDJZL { get; set; }
        public string JGCLXT { get; set; }
        public string LJ { get; set; }
        public string ZXJYSWCLZJ { get; set; }
        public string GZXCZXJCLZJ { get; set; }
        public string CGZXG { get; set; }
        public string ZDQDL { get; set; }
        public string ZDBDL { get; set; }
        public string DGSD { get; set; }
        public string GDCYYKZSB { get; set; }
        public string GDCYYKZSB_XHGG { get; set; }
        public string GDCYYKZSB_BJCJ { get; set; }
        public string GDCYYKZSB_NUM { get; set; }
        public string GDCYYKZSB_ZYJSCS { get; set; }
        public string LCWXDDTXSB { get; set; }
        public string LCWXDDTXSB_XHGG { get; set; }
        public string LCWXDDTXSB_BJCJ { get; set; }
        public string LCWXDDTXSB_NUM { get; set; }
        public string LCWXDDTXSB_ZYJSCS { get; set; }
        public string DEPT_CODE { get; set; }
    }
}
