//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEDGER_TRAFFIC_VEHICLES
    {
        public string PKID { get; set; }
        public string CAR_NUMBER { get; set; }
        public string CAR_TYPE { get; set; }
        public string CAR_NAME { get; set; }
        public string CAR_MODEL { get; set; }
        public string ORIGIN_PLACE { get; set; }
        public string T_SEAT { get; set; }
        public Nullable<System.DateTime> BEGIN_TIME { get; set; }
        public Nullable<decimal> ORIGINAL_VALUE { get; set; }
        public Nullable<decimal> RUN_KM { get; set; }
        public string MONEY_SOURCE { get; set; }
        public string PROPERTY_UNIT { get; set; }
        public string TECHNOLOGY_STATE { get; set; }
        public string CJ_NAME { get; set; }
        public string GQ_NAME { get; set; }
        public string PRESERVER { get; set; }
        public string DEPT_CODE { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string INPUT_USER { get; set; }
        public string DISTRIBUTION_LOCATION { get; set; }
        public string SETUP_TEAM { get; set; }
        public string DRIVER { get; set; }
        public string DEPUTY_DRIVER { get; set; }
        public string LARGE_CLASS { get; set; }
        public string SHAPE_SIZE { get; set; }
    }
}
