//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKJ_BROKEN_CHAIN
    {
        public string PKID { get; set; }
        public string BUREAU_NAME { get; set; }
        public string BUREAU_NUM { get; set; }
        public string LINE_NAME { get; set; }
        public string LINE_NUM { get; set; }
        public string LINE_DIR { get; set; }
        public string BROKEN_CHAIN_TYPE { get; set; }
        public string START_MILEAGE { get; set; }
        public string END_MILEAGE { get; set; }
        public string LONG_CHAIN_LENGTH { get; set; }
        public string SHORT_CHAIN_LENGTH { get; set; }
        public string MODIFY_TAG { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string USER_NAME { get; set; }
        public string DEPT_CODE { get; set; }
    }
}
