//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKJ_MAIN_TRACK_MILEAGE
    {
        public string PKID { get; set; }
        public string NUM { get; set; }
        public string LINE_NAME { get; set; }
        public string LINE_DIR { get; set; }
        public string START_INTERVAL_OR_STATION { get; set; }
        public string START_PLACE { get; set; }
        public string START_MILEAGE { get; set; }
        public string END_INTERVAL_OR_STATION { get; set; }
        public string END_PLACE { get; set; }
        public string END_MILEAGE { get; set; }
        public string EXTENDED_LENGTH { get; set; }
        public string MODIFY_TAG { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string USER_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string LINE_NUM { get; set; }
    }
}
