//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OIL_BDATA_CURVE
    {
        public string CURVE_ID { get; set; }
        public string DEPT_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_NAME { get; set; }
        public string LINE_DIR { get; set; }
        public Nullable<decimal> OILMILE_BEGIN { get; set; }
        public Nullable<decimal> OILMILE_END { get; set; }
        public string POS_FLAG { get; set; }
        public string ENABLE_FLAG { get; set; }
        public Nullable<System.DateTime> CURVE_INDATE { get; set; }
        public Nullable<System.DateTime> CURVE_LSTUPDATEDATE { get; set; }
        public string CURVE_LSTUPDATEUSER { get; set; }
        public Nullable<decimal> CURVE_ORDER { get; set; }
        public string CURVE_MEMO { get; set; }
        public Nullable<decimal> CURVE_RADIUS { get; set; }
        public Nullable<decimal> CURVE_LENGTH { get; set; }
        public Nullable<decimal> OILMILEBUF_BEGIN { get; set; }
        public Nullable<decimal> OILMILEBUF_END { get; set; }
        public Nullable<decimal> OILMILEACT_BEGIN { get; set; }
        public Nullable<decimal> OILMILEACT_END { get; set; }
    }
}
