//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OIL_BDATA_DEVICE
    {
        public string DEVICE_ID { get; set; }
        public string DEPT_CODE { get; set; }
        public string PHONE_NO { get; set; }
        public string DEVICE_NAME { get; set; }
        public string DEVICE_MEMO { get; set; }
        public string DEVICE_NO { get; set; }
    }
}
