//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAIL_CARRIERRECORD_POINT
    {
        public string RECORDPOINT_ID { get; set; }
        public string POINT_NO { get; set; }
        public Nullable<System.DateTime> RECORD_TIME { get; set; }
        public string STATE_FLAG { get; set; }
    }
}
