//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAIL_COMM
    {
        public string ID { get; set; }
        public string HOST_NO { get; set; }
        public string FREQUENCY { get; set; }
        public string SEND_PHONE { get; set; }
        public System.DateTime UPLOAD_TIME { get; set; }
        public System.DateTime SEND_TIME { get; set; }
    }
}
