//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAIL_RECORD_HOST
    {
        public string HOSTRECORD_ID { get; set; }
        public string HOST_NO { get; set; }
        public Nullable<System.DateTime> RECORD_TIME { get; set; }
        public string POWERBOARD_FLAG { get; set; }
        public string INTERFACEBOARD_FLAG { get; set; }
        public Nullable<decimal> POINT_NUM { get; set; }
        public string POWER { get; set; }
        public string HOSTRECORD_LOG { get; set; }
        public string POWER_TYPE { get; set; }
        public string POWER_AC { get; set; }
    }
}
