//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAILCAR_BDATA_ONLINE
    {
        public string PHONE { get; set; }
        public System.DateTime ONLINE_TIME { get; set; }
        public string LINE_NAME { get; set; }
        public string DIRECTION { get; set; }
        public Nullable<decimal> MILEAGE { get; set; }
        public string ONLINESTATU { get; set; }
        public string CONTENT { get; set; }
    }
}
