//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAIL_SOUNDBDATA_SECTION
    {
        public RAIL_SOUNDBDATA_SECTION()
        {
            this.RAIL_SOUNDBDATA_POINT = new HashSet<RAIL_SOUNDBDATA_POINT>();
            this.RAIL_SOUNDSECTION_WARN = new HashSet<RAIL_SOUNDSECTION_WARN>();
        }
    
        public string SECTION_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string START_MILE { get; set; }
        public string END_MILE { get; set; }
        public string SECTION_ID { get; set; }
    
        public virtual ICollection<RAIL_SOUNDBDATA_POINT> RAIL_SOUNDBDATA_POINT { get; set; }
        public virtual SYS_DEPT SYS_DEPT { get; set; }
        public virtual ICollection<RAIL_SOUNDSECTION_WARN> RAIL_SOUNDSECTION_WARN { get; set; }
    }
}
