//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAIN_DEVICE
    {
        public RAIN_DEVICE()
        {
            this.RAIN_SECTION_LINE = new HashSet<RAIN_SECTION_LINE>();
        }
    
        public string 路局 { get; set; }
        public string 监测点 { get; set; }
        public string 编号 { get; set; }
        public string 工务段 { get; set; }
        public string 车间 { get; set; }
        public string 线名 { get; set; }
        public Nullable<decimal> 火星经度 { get; set; }
        public Nullable<decimal> 火星纬度 { get; set; }
        public Nullable<decimal> 里程 { get; set; }
        public string 行别 { get; set; }
        public Nullable<int> 排序 { get; set; }
        public string 区段 { get; set; }
        public string 限速 { get; set; }
        public string 封锁 { get; set; }
        public string 状态 { get; set; }
        public Nullable<System.DateTime> 更改状态时间 { get; set; }
        public string 负责人 { get; set; }
        public string PHONE { get; set; }
    
        public virtual ICollection<RAIN_SECTION_LINE> RAIN_SECTION_LINE { get; set; }
    }
}
