//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESCUE_LINE
    {
        public RESCUE_LINE()
        {
            this.RESCUE_LINE_INFO = new HashSet<RESCUE_LINE_INFO>();
            this.RESCUE_LINE_PHOTO = new HashSet<RESCUE_LINE_PHOTO>();
            this.RESCUE_LINE_PORT = new HashSet<RESCUE_LINE_PORT>();
        }
    
        public string RESCUE_ID { get; set; }
        public string RESCUE_NAME { get; set; }
        public string LINE_NAME { get; set; }
        public string DIRECTION { get; set; }
        public Nullable<decimal> MILEAGE_BEGIN { get; set; }
        public Nullable<decimal> MILEAGE_END { get; set; }
        public string LINE_SIDE { get; set; }
        public string LINE_CONTENT { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<decimal> MARS_LONGITUDE { get; set; }
        public Nullable<decimal> MARS_LATITUDE { get; set; }
        public string DEPT_CODE { get; set; }
        public string ICON { get; set; }
        public Nullable<int> LINE_SORT { get; set; }
    
        public virtual ICollection<RESCUE_LINE_INFO> RESCUE_LINE_INFO { get; set; }
        public virtual ICollection<RESCUE_LINE_PHOTO> RESCUE_LINE_PHOTO { get; set; }
        public virtual ICollection<RESCUE_LINE_PORT> RESCUE_LINE_PORT { get; set; }
    }
}
