//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RULE_PARSE_MARKUP
    {
        public decimal QUERY_ID { get; set; }
        public string DOCUMENT { get; set; }
        public string DOCCODE { get; set; }
        public string DOCNAME { get; set; }
        public string PROBLEMID { get; set; }
        public string PROBLEM { get; set; }
        public string PROBLEMKEYS { get; set; }
        public Nullable<short> HITNUM { get; set; }
        public Nullable<short> MATCHNUM { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public string MEMO { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime CREATETIME { get; set; }
        public string DEPTCODE { get; set; }
    }
}
