//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCRIPTS_SECTION_TYPEFLOOD
    {
        public SCRIPTS_SECTION_TYPEFLOOD()
        {
            this.SCRIPTS_SECTION_FLOOD_PHOTO = new HashSet<SCRIPTS_SECTION_FLOOD_PHOTO>();
            this.SCRIPTS_SECTION_LINE = new HashSet<SCRIPTS_SECTION_LINE>();
        }
    
        public string TYPEFLOOD_ID { get; set; }
        public string TYPEFLOOD_NAME { get; set; }
        public string ICON { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string TYPEFLOOD_LEVEL { get; set; }
        public string LINE_NAME { get; set; }
        public string LINE_DIR { get; set; }
        public Nullable<decimal> MILEAGE_CENTER { get; set; }
        public Nullable<decimal> MILEAGE_BEGIN { get; set; }
        public Nullable<decimal> MILEAGE_END { get; set; }
        public Nullable<decimal> MARSLONGITUDE { get; set; }
        public Nullable<decimal> MARSLATITUDE { get; set; }
        public string TYPEFLOOD_NOTE { get; set; }
        public string FLOOD_TYPE { get; set; }
        public string ESTIMATE_SITUATION { get; set; }
        public string RESCUE_FACILITY { get; set; }
        public Nullable<short> RESCUE_NUMBER { get; set; }
        public string OBSERVATION_SYSTEM { get; set; }
        public string RESCUE_WAY { get; set; }
        public string EXECUTIVE_ID { get; set; }
        public string EXECUTIVE { get; set; }
        public string EXECUTIVE_LEADER_ID { get; set; }
        public string EXECUTIVE_LEADER { get; set; }
        public string LINE_SIDE { get; set; }
        public string DISEASE_SITUATION { get; set; }
        public string DUTY_DEPT { get; set; }
        public string DUTY_DEPTCODE { get; set; }
    
        public virtual ICollection<SCRIPTS_SECTION_FLOOD_PHOTO> SCRIPTS_SECTION_FLOOD_PHOTO { get; set; }
        public virtual ICollection<SCRIPTS_SECTION_LINE> SCRIPTS_SECTION_LINE { get; set; }
    }
}
