//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCRIPTS_SECTION_TYPEOTHER
    {
        public SCRIPTS_SECTION_TYPEOTHER()
        {
            this.SCRIPTS_SECTION_TYPEOTHERINFO = new HashSet<SCRIPTS_SECTION_TYPEOTHERINFO>();
        }
    
        public string TYPE_ID { get; set; }
        public string TYPE_NAME { get; set; }
        public string ICON { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string TYPE_NAME_ID { get; set; }
        public string TIP_TYPE { get; set; }
    
        public virtual ICollection<SCRIPTS_SECTION_TYPEOTHERINFO> SCRIPTS_SECTION_TYPEOTHERINFO { get; set; }
    }
}
