//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCRIPTS_SECTION_BADSIGNAL
    {
        public string PKID { get; set; }
        public string LINE_NAME { get; set; }
        public string LINE_DIR { get; set; }
        public string DEPT_CODE { get; set; }
        public string POSITION { get; set; }
        public Nullable<decimal> MILEAGE_START { get; set; }
        public Nullable<decimal> MILEAGE_END { get; set; }
        public string NOTE { get; set; }
        public string TYPE { get; set; }
    
        public virtual SYS_DEPT SYS_DEPT { get; set; }
    }
}
