//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_MEMBER
    {
        public SYS_MEMBER()
        {
            this.JOB_JOB_PLAN = new HashSet<JOB_JOB_PLAN>();
            this.JOB_MSG_BATCHSEND = new HashSet<JOB_MSG_BATCHSEND>();
            this.JOB_PLAN_WARNPHONESET = new HashSet<JOB_PLAN_WARNPHONESET>();
            this.JOB_PLAN_WARNPOSSET = new HashSet<JOB_PLAN_WARNPOSSET>();
            this.GATE_BDATA_CARD = new HashSet<GATE_BDATA_CARD>();
            this.GATE_JOB_PLAN = new HashSet<GATE_JOB_PLAN>();
        }
    
        public string MEMBER_ID { get; set; }
        public string NAME { get; set; }
        public string MOBILE { get; set; }
        public string JOB { get; set; }
        public string PHONE { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string DEPT_CODE { get; set; }
        public string UPDATE_USER { get; set; }
        public string DEL_FLAG { get; set; }
        public string LOCATION_FLAG { get; set; }
        public string INTELLIGENCE { get; set; }
        public string POS_LEVEL { get; set; }
        public string MOBILE_STATE { get; set; }
    
        public virtual ICollection<JOB_JOB_PLAN> JOB_JOB_PLAN { get; set; }
        public virtual ICollection<JOB_MSG_BATCHSEND> JOB_MSG_BATCHSEND { get; set; }
        public virtual ICollection<JOB_PLAN_WARNPHONESET> JOB_PLAN_WARNPHONESET { get; set; }
        public virtual ICollection<JOB_PLAN_WARNPOSSET> JOB_PLAN_WARNPOSSET { get; set; }
        public virtual SYS_DEPT SYS_DEPT { get; set; }
        public virtual SYS_INTELLIGENCE_DIC SYS_INTELLIGENCE_DIC { get; set; }
        public virtual SYS_POSLEVEL_DIC SYS_POSLEVEL_DIC { get; set; }
        public virtual ICollection<GATE_BDATA_CARD> GATE_BDATA_CARD { get; set; }
        public virtual ICollection<GATE_JOB_PLAN> GATE_JOB_PLAN { get; set; }
    }
}
