//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_MENU
    {
        public SYS_MENU()
        {
            this.SYS_MENU_HELPCONTENT = new HashSet<SYS_MENU_HELPCONTENT>();
            this.SYS_MENUOPT = new HashSet<SYS_MENUOPT>();
            this.SYS_ROLE_MENU_MAP = new HashSet<SYS_ROLE_MENU_MAP>();
            this.SYS_USER_DEFAULTMENU = new HashSet<SYS_USER_DEFAULTMENU>();
        }
    
        public string MENU_ID { get; set; }
        public string MENU_NAME { get; set; }
        public string C_ICO { get; set; }
        public string AREA { get; set; }
        public string CONTROLLER { get; set; }
        public string ACTION { get; set; }
        public string PARENT_ID { get; set; }
        public decimal MENU_LEVEL { get; set; }
        public Nullable<decimal> MENU_ORDER { get; set; }
        public string GIS_ORDER { get; set; }
        public string ISSHOW_FLAG { get; set; }
        public string DEFMENU_ID { get; set; }
    
        public virtual ICollection<SYS_MENU_HELPCONTENT> SYS_MENU_HELPCONTENT { get; set; }
        public virtual ICollection<SYS_MENUOPT> SYS_MENUOPT { get; set; }
        public virtual ICollection<SYS_ROLE_MENU_MAP> SYS_ROLE_MENU_MAP { get; set; }
        public virtual ICollection<SYS_USER_DEFAULTMENU> SYS_USER_DEFAULTMENU { get; set; }
    }
}
