//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ASS_MATERIAL
    {
        public string PKID { get; set; }
        public string C_MATERIALNAME { get; set; }
        public string C_MATERIAL_TYPE { get; set; }
        public string C_MATERIAL_UNIT { get; set; }
        public string C_SAFETYRISKTIPS { get; set; }
        public string C_EFF_FLAG { get; set; }
        public Nullable<decimal> N_ORDER { get; set; }
        public string C_MEMO { get; set; }
    }
}
