//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ASS_FLOW
    {
        public short FLOWID { get; set; }
        public string FLOW_NAME { get; set; }
        public string FLOW_DESC { get; set; }
        public Nullable<short> FLAG { get; set; }
        public string DEPT_CODE { get; set; }
        public Nullable<System.DateTime> CRT_TM { get; set; }
    }
}
