//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ASS_UNIT_TQI
    {
        public string PKID { get; set; }
        public string C_GWD_CODE { get; set; }
        public string C_LINE_CODE { get; set; }
        public string C_LINE_DIR { get; set; }
        public Nullable<short> N_UNIT_NUM { get; set; }
        public Nullable<decimal> N_UNIT_START_MILE { get; set; }
        public Nullable<decimal> N_UNIT_END_MILE { get; set; }
        public string C_LINE_FEATURE { get; set; }
        public Nullable<decimal> N_TQI_MILE { get; set; }
        public Nullable<decimal> N_TQI { get; set; }
        public string C_TQI_OVER { get; set; }
        public string C_OVERRUN { get; set; }
        public Nullable<decimal> N_TRACK_LEFT { get; set; }
        public Nullable<decimal> N_TRACK_RIGHT { get; set; }
        public Nullable<decimal> N_HILOW_LEFT { get; set; }
        public Nullable<decimal> N_HILOW_RIGHT { get; set; }
        public Nullable<decimal> N_PLANE { get; set; }
        public Nullable<decimal> N_GAUGE { get; set; }
        public Nullable<decimal> N_TWIST { get; set; }
        public Nullable<decimal> C_SPEED { get; set; }
        public string C_SPEED_STANDARD { get; set; }
        public Nullable<System.DateTime> T_CHECK_DATE { get; set; }
        public Nullable<System.DateTime> T_ASS_DATE { get; set; }
        public string T_ASS_DEP_CODE { get; set; }
    }
}
