//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ASS_COMPMAINT_PLAN
    {
        public string PKID { get; set; }
        public string C_JOB_NO { get; set; }
        public string C_EFF_FLAG { get; set; }
        public Nullable<System.DateTime> T_PLANREAPIR_DATE { get; set; }
        public string C_GWD_CODE { get; set; }
        public string C_DEP_CODE { get; set; }
        public string C_DEP_NAME { get; set; }
        public string C_DEP_PROP { get; set; }
        public string C_MEMO1 { get; set; }
        public string C_MEMO2 { get; set; }
        public string C_MEMO { get; set; }
        public Nullable<System.DateTime> T_CRT_TM { get; set; }
        public string C_CRT_NAME { get; set; }
        public Nullable<System.DateTime> C_REPAIR_DATE { get; set; }
        public string C_REPAIR_RES { get; set; }
        public string C_APPROVER { get; set; }
        public string C_RECIEW_RESU { get; set; }
        public string C_REPAIR_LEADER { get; set; }
        public string C_SAMP_RES { get; set; }
    }
}
