//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ASS_UNIT625_VAL_DETAIL
    {
        public string PKID { get; set; }
        public string FKID { get; set; }
        public string C_GWD_CODE { get; set; }
        public string C_DEPT_CODE { get; set; }
        public short N_UNIT_NUM { get; set; }
        public Nullable<short> N_UNIT625_NUM { get; set; }
        public string C_LINE_CODE { get; set; }
        public string C_LINE_NAME { get; set; }
        public string C_LINE_DIR { get; set; }
        public Nullable<decimal> N_START_MILE { get; set; }
        public Nullable<decimal> N_END_MILE { get; set; }
        public string C_LINE_FEATURE { get; set; }
        public string C_ITEM { get; set; }
        public string C_PRO_NAME { get; set; }
        public string C_PRO_PLACE { get; set; }
        public Nullable<decimal> N_PEAK { get; set; }
        public Nullable<decimal> N_SCORE { get; set; }
        public string C_CHECK_TYPE { get; set; }
        public string C_CHECK_DEV { get; set; }
        public string C_STANDARD { get; set; }
        public Nullable<System.DateTime> T_ASS_DATE { get; set; }
        public string C_EFF_FLAG { get; set; }
        public Nullable<decimal> N_ORDER { get; set; }
        public string C_MEMO { get; set; }
        public Nullable<decimal> N_PRO_MILE { get; set; }
        public Nullable<short> N_OVERRUN_LEVEL { get; set; }
        public string C_PRO_CODE { get; set; }
        public string C_PRO_DETAIL { get; set; }
        public Nullable<short> N_SPEED { get; set; }
        public Nullable<short> N_REPEAT_NUM { get; set; }
        public string C_SCORE_WEIGHT { get; set; }
        public string C_LINE_CAT { get; set; }
        public string C_ASS_DEP_CODE { get; set; }
    }
}
