//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ASS_PARA_DYN_SCORE
    {
        public string PKID { get; set; }
        public string C_CHECK_TYPE { get; set; }
        public string C_ITEM { get; set; }
        public Nullable<short> N_LEVEL { get; set; }
        public Nullable<short> N_REPEAT { get; set; }
        public Nullable<short> N_SCORE { get; set; }
        public string C_JOINTLESS { get; set; }
        public Nullable<short> N_MAX_SPEED { get; set; }
        public Nullable<short> N_MIN_SPEED { get; set; }
        public Nullable<decimal> N_ORDER { get; set; }
        public string C_MEMO { get; set; }
        public Nullable<short> N_SPEED_LEVEL { get; set; }
        public string C_EFF_FLAG { get; set; }
    }
}
