//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ASS_UNIT_VAL
    {
        public string PKID { get; set; }
        public string FKID { get; set; }
        public string C_GWD_CODE { get; set; }
        public string C_DEP_CODE { get; set; }
        public short N_UNIT_NUM { get; set; }
        public string C_LINE_CODE { get; set; }
        public string C_LINE_NAME { get; set; }
        public string C_LINE_DIR { get; set; }
        public Nullable<decimal> N_START_MILE { get; set; }
        public Nullable<decimal> N_END_MILE { get; set; }
        public string C_STANDARD { get; set; }
        public Nullable<decimal> N_STATIC_SCORE { get; set; }
        public Nullable<decimal> N_DYNAMIC_SCORE { get; set; }
        public Nullable<decimal> N_SCORE { get; set; }
        public Nullable<System.DateTime> T_ASS_DATE { get; set; }
        public Nullable<System.DateTime> T_CRT_TM { get; set; }
        public string C_CRT_NAME { get; set; }
        public string C_EFF_FLAG { get; set; }
        public Nullable<decimal> N_ORDER { get; set; }
        public string C_MEMO { get; set; }
        public string C_EVAL_GRADE { get; set; }
        public string C_SCORE_WEIGHT { get; set; }
        public string C_LINE_CAT { get; set; }
        public string C_ASS_DEP_CODE { get; set; }
        public Nullable<decimal> N_TQI_VALUE { get; set; }
        public Nullable<decimal> N_TQI_SCORE { get; set; }
    }
}
