//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BOOTRECINFO
    {
        public string PKID { get; set; }
        public string PHONE { get; set; }
        public System.DateTime DTIME { get; set; }
        public string LINENAME { get; set; }
        public string DIRE { get; set; }
        public Nullable<decimal> MILEAGE { get; set; }
        public string STATIONNAME { get; set; }
        public string TRACKNUM { get; set; }
        public string USERNAME { get; set; }
        public string RAILCAR_NUM { get; set; }
    }
}
