//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CHK_TURNOUT_ITEMS
    {
        public string PKID { get; set; }
        public string FKID { get; set; }
        public string GAUGE_SLOPE { get; set; }
        public string GAUGE_SWITCHPOINT { get; set; }
        public string GAUGE_SWITCH { get; set; }
        public string GAUGE_SWITCHHEEL_STR { get; set; }
        public string GAUGE_SWITCHHEEL_CUR { get; set; }
        public string GAUGE_STR_HEAD { get; set; }
        public string GAUGE_STR_MID { get; set; }
        public string GAUGE_STR_TAIL { get; set; }
        public string GAUGE_CUR_HEAD { get; set; }
        public string GAUGE_CUR_MID { get; set; }
        public string GAUGE_CUR_TAIL { get; set; }
        public string GAUGE_FROG_HEAD_STR { get; set; }
        public string GAUGE_FROG_HEAD_CUR { get; set; }
        public string GAUGE_FROG_MID_STR { get; set; }
        public string GAUGE_FROG_MID_CUR { get; set; }
        public string GAUGE_FROG_TAIL_STR { get; set; }
        public string GAUGE_FROG_TAIL_CUR { get; set; }
        public string GAUGE_CHECKGAGE_STR { get; set; }
        public string GAUGE_CHECKGAGE_CUR { get; set; }
        public string GAUGE_BACKGAGE_STR { get; set; }
        public string GAUGE_BACKGAGE_CUR { get; set; }
        public string GAUGE_OFFSET { get; set; }
        public string LEVEL_SLOPE { get; set; }
        public string LEVEL_SWITCHPOINT { get; set; }
        public string LEVEL_SWITCH { get; set; }
        public string LEVEL_SWITCHHEEL_STR { get; set; }
        public string LEVEL_SWITCHHEEL_CUR { get; set; }
        public string LEVEL_STR_HEAD { get; set; }
        public string LEVEL_STR_MID { get; set; }
        public string LEVEL_STR_TAIL { get; set; }
        public string LEVEL_CUR_HEAD { get; set; }
        public string LEVEL_CUR_MID { get; set; }
        public string LEVEL_CUR_TAIL { get; set; }
        public string LEVEL_FROG_HEAD_STR { get; set; }
        public string LEVEL_FROG_HEAD_CUR { get; set; }
        public string LEVEL_FROG_MID_STR { get; set; }
        public string LEVEL_FROG_MID_CUR { get; set; }
        public string LEVEL_FROG_TAIL_STR { get; set; }
        public string LEVEL_FROG_TAIL_CUR { get; set; }
        public string LEVEL_CHECKGAGE_STR { get; set; }
        public string LEVEL_CHECKGAGE_CUR { get; set; }
        public string LEVEL_BACKGAGE_STR { get; set; }
        public string LEVEL_BACKGAGE_CUR { get; set; }
        public string TWIST_SLOPE { get; set; }
        public string TWIST_SWITCHPOINT { get; set; }
        public string TWIST_SWITCH { get; set; }
        public string TWIST_SWITCHHEEL_STR { get; set; }
        public string TWIST_SWITCHHEEL_CUR { get; set; }
        public string TWIST_STR_HEAD { get; set; }
        public string TWIST_STR_MID { get; set; }
        public string TWIST_STR_TAIL { get; set; }
        public string TWIST_CUR_HEAD { get; set; }
        public string TWIST_CUR_MID { get; set; }
        public string TWIST_CUR_TAIL { get; set; }
        public string TWIST_FROG_HEAD_STR { get; set; }
        public string TWIST_FROG_HEAD_CUR { get; set; }
        public string TWIST_FROG_MID_STR { get; set; }
        public string TWIST_FROG_MID_CUR { get; set; }
        public string TWIST_FROG_TAIL_STR { get; set; }
        public string TWIST_FROG_TAIL_CUR { get; set; }
        public string TWIST_CHECKGAGE_STR { get; set; }
        public string TWIST_CHECKGAGE_CUR { get; set; }
        public string TWIST_BACKGAGE_STR { get; set; }
        public string TWIST_BACKGAGE_CUR { get; set; }
        public string TRACK_SLOPE { get; set; }
        public string TRACK_SWITCHPOINT { get; set; }
        public string TRACK_SWITCH { get; set; }
        public string TRACK_SWITCHHEEL_STR { get; set; }
        public string TRACK_SWITCHHEEL_CUR { get; set; }
        public string TRACK_STR_HEAD { get; set; }
        public string TRACK_STR_MID { get; set; }
        public string TRACK_STR_TAIL { get; set; }
        public string TRACK_CUR_HEAD { get; set; }
        public string TRACK_CUR_MID { get; set; }
        public string TRACK_CUR_TAIL { get; set; }
        public string TRACK_FROG_HEAD_STR { get; set; }
        public string TRACK_FROG_HEAD_CUR { get; set; }
        public string TRACK_FROG_MID_STR { get; set; }
        public string TRACK_FROG_MID_CUR { get; set; }
        public string TRACK_FROG_TAIL_STR { get; set; }
        public string TRACK_FROG_TAIL_CUR { get; set; }
        public string TRACK_CHECKGAGE_STR { get; set; }
        public string TRACK_CHECKGAGE_CUR { get; set; }
        public string TRACK_BACKGAGE_STR { get; set; }
        public string TRACK_BACKGAGE_CUR { get; set; }
        public string HIHLOW_SLOPE { get; set; }
        public string HIHLOW_SWITCHPOINT { get; set; }
        public string HIHLOW_SWITCH { get; set; }
        public string HIHLOW_SWITCHHEEL_STR { get; set; }
        public string HIHLOW_SWITCHHEEL_CUR { get; set; }
        public string HIHLOW_STR_HEAD { get; set; }
        public string HIHLOW_STR_MID { get; set; }
        public string HIHLOW_STR_TAIL { get; set; }
        public string HIHLOW_CUR_HEAD { get; set; }
        public string HIHLOW_CUR_MID { get; set; }
        public string HIHLOW_CUR_TAIL { get; set; }
        public string HIHLOW_FROG_HEAD_STR { get; set; }
        public string HIHLOW_FROG_HEAD_CUR { get; set; }
        public string HIHLOW_FROG_MID_STR { get; set; }
        public string HIHLOW_FROG_MID_CUR { get; set; }
        public string HIHLOW_FROG_TAIL_STR { get; set; }
        public string HIHLOW_FROG_TAIL_CUR { get; set; }
        public string HIHLOW_CHECKGAGE_STR { get; set; }
        public string HIHLOW_CHECKGAGE_CUR { get; set; }
        public string HIHLOW_BACKGAGE_STR { get; set; }
        public string HIHLOW_BACKGAGE_CUR { get; set; }
        public string REPAIR_TM_CONTENT { get; set; }
        public string RECORD { get; set; }
        public Nullable<System.DateTime> CHK_TM { get; set; }
        public Nullable<decimal> LNG { get; set; }
        public Nullable<decimal> LAT { get; set; }
        public Nullable<decimal> MARS_LNG { get; set; }
        public Nullable<decimal> MARS_LAT { get; set; }
        public Nullable<decimal> BAIDU_LNG { get; set; }
        public Nullable<decimal> BAIDU_LAT { get; set; }
        public Nullable<System.DateTime> GPS_TM { get; set; }
        public string RECHECK_FLAG { get; set; }
    
        public virtual T_CHK_TURNOUT T_CHK_TURNOUT { get; set; }
    }
}
