//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CZ_WARP_TEMP
    {
        public decimal ID { get; set; }
        public string 线名 { get; set; }
        public Nullable<decimal> 线编号 { get; set; }
        public string 行别 { get; set; }
        public decimal 里程 { get; set; }
        public decimal 速度 { get; set; }
        public Nullable<decimal> 水加 { get; set; }
        public Nullable<decimal> 水加级别 { get; set; }
        public Nullable<decimal> 垂加 { get; set; }
        public Nullable<decimal> 垂加级别 { get; set; }
        public System.DateTime 时间 { get; set; }
        public string 机车号 { get; set; }
        public string 车次 { get; set; }
        public string 工区 { get; set; }
        public string 车间 { get; set; }
        public string 工务段 { get; set; }
        public string 路局 { get; set; }
        public Nullable<decimal> 道岔 { get; set; }
        public Nullable<decimal> 道口 { get; set; }
        public Nullable<decimal> 曲线 { get; set; }
        public Nullable<decimal> 桥梁 { get; set; }
        public Nullable<decimal> 涵洞 { get; set; }
        public Nullable<decimal> 隧道 { get; set; }
        public Nullable<decimal> 竖曲线 { get; set; }
        public Nullable<decimal> 自定义 { get; set; }
        public Nullable<decimal> 侧向 { get; set; }
        public Nullable<decimal> 长链 { get; set; }
        public string 其他标记 { get; set; }
        public Nullable<decimal> 动车 { get; set; }
        public string 厂家 { get; set; }
        public string 车型 { get; set; }
        public Nullable<decimal> 车型编号 { get; set; }
        public Nullable<decimal> 重复次数 { get; set; }
        public Nullable<decimal> GRADE { get; set; }
        public string 段编号 { get; set; }
        public string USER_CODE { get; set; }
    }
}
