//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MOBILEFILE_TODOWN
    {
        public string PKID { get; set; }
        public string 手机号 { get; set; }
        public System.DateTime 时间 { get; set; }
        public Nullable<decimal> 纬度 { get; set; }
        public Nullable<decimal> 经度 { get; set; }
        public string 文件名 { get; set; }
        public string 线名 { get; set; }
        public string 行别 { get; set; }
        public Nullable<decimal> 里程 { get; set; }
        public Nullable<decimal> 已提示 { get; set; }
        public Nullable<decimal> 火星纬度 { get; set; }
        public Nullable<decimal> 火星经度 { get; set; }
        public Nullable<decimal> 百度纬度 { get; set; }
        public Nullable<decimal> 百度经度 { get; set; }
        public Nullable<decimal> 文件类型 { get; set; }
        public string 下载地址 { get; set; }
        public string 是否原图 { get; set; }
        public string 描述 { get; set; }
        public string C_TODOWN_ID { get; set; }
        public string 缩略图路径 { get; set; }
        public string 关联作业计划号 { get; set; }
    }
}
