//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RAIN_SMS
    {
        public decimal PKID { get; set; }
        public string 目标手机号 { get; set; }
        public string 内容 { get; set; }
        public Nullable<System.DateTime> 发送时间 { get; set; }
    }
}
