//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REALRAINDATA
    {
        public string PHONE { get; set; }
        public string RWB { get; set; }
        public string GWD { get; set; }
        public string CJ { get; set; }
        public string LINENAME { get; set; }
        public string RSNAME { get; set; }
        public System.DateTime RTIME { get; set; }
        public decimal RM1 { get; set; }
        public decimal RM10 { get; set; }
        public decimal RH1 { get; set; }
        public decimal RH24 { get; set; }
        public decimal RCONT { get; set; }
        public decimal RTODAY { get; set; }
        public decimal RYEDAY { get; set; }
        public Nullable<System.DateTime> CONTSTIME { get; set; }
        public Nullable<System.DateTime> CONTETIME { get; set; }
        public string RLEV { get; set; }
        public Nullable<decimal> RM30 { get; set; }
        public Nullable<decimal> RH3 { get; set; }
        public Nullable<decimal> RH12 { get; set; }
        public Nullable<System.DateTime> WTIME { get; set; }
        public Nullable<decimal> WRAIN { get; set; }
        public Nullable<decimal> WTYPE { get; set; }
        public Nullable<decimal> WRCAT { get; set; }
        public Nullable<decimal> RCOMPCAT { get; set; }
        public Nullable<decimal> RCOMP { get; set; }
        public Nullable<System.DateTime> WCLEARTIME { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public Nullable<decimal> WSTATUS { get; set; }
        public string WDESC { get; set; }
        public Nullable<decimal> RSTATUS { get; set; }
    }
}
