//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_PLAN
    {
        public string PLAN_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string DEP_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public Nullable<System.DateTime> PLAN_DATE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public string TASK_TYPE { get; set; }
        public string TASKS_ECTION { get; set; }
        public Nullable<decimal> START_MILE { get; set; }
        public Nullable<decimal> END_MILE { get; set; }
        public string ITEM_TYPE { get; set; }
        public string TASK_ITEM { get; set; }
        public string TASK_PLACE { get; set; }
        public Nullable<decimal> TASK_QUOTA { get; set; }
        public Nullable<decimal> TASK_ATTEND { get; set; }
        public Nullable<decimal> REAL_UPPER { get; set; }
        public string CONTENT { get; set; }
        public string TOOLS { get; set; }
        public string MATERIALS { get; set; }
        public string PROBLEMS { get; set; }
        public string JOB_SAFEMEASURES { get; set; }
        public string LOCATESTARE_MEMBER { get; set; }
        public string LOCATE_MEMBER { get; set; }
        public string STATION_MEMBER { get; set; }
        public string STATION_MEMBER_LOCATE { get; set; }
        public string FIRST_MEMBER { get; set; }
        public string END_MEMBER { get; set; }
        public string CENTER_MEMBER { get; set; }
        public string PHONE_MEMBER { get; set; }
        public string INSPECERA { get; set; }
        public string INSPECERB { get; set; }
        public string INSPECER_RANGEA { get; set; }
        public string INSPECER_RANGEB { get; set; }
        public string LOCATE_LEADER { get; set; }
        public string LOCATE_LEADER_POST { get; set; }
        public string JOB_LEADER { get; set; }
        public string UPPER_PLANDATE { get; set; }
        public string EFFECT_RANGE { get; set; }
        public string WALK_WAYTYPE { get; set; }
        public string ENTER_LOCATE { get; set; }
        public string LEAVE_LOCATE { get; set; }
        public string MEMO { get; set; }
        public string CREATE_MEMBER { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string CREATE_USER { get; set; }
        public string CREATE_DEPT { get; set; }
        public Nullable<decimal> CENTER_MILE { get; set; }
        public Nullable<decimal> CJSH { get; set; }
        public Nullable<decimal> DDSH { get; set; }
        public Nullable<decimal> DEPTSB { get; set; }
        public Nullable<decimal> DEPTCC { get; set; }
        public Nullable<decimal> DEPTBH { get; set; }
        public Nullable<decimal> LUGONG { get; set; }
        public Nullable<decimal> LAOWUGONG { get; set; }
        public Nullable<decimal> SHANGDAO { get; set; }
        public Nullable<decimal> DAOKOULUGONG { get; set; }
        public Nullable<decimal> DAOKOULAOWUGONG { get; set; }
        public Nullable<decimal> TIAOXIU { get; set; }
        public Nullable<decimal> SHIJIA { get; set; }
        public Nullable<decimal> BINGJIA { get; set; }
        public Nullable<decimal> CHUCHAI { get; set; }
        public string ZHURENWZ { get; set; }
        public string MEMO1 { get; set; }
        public string DDSP1 { get; set; }
        public string DDSP2 { get; set; }
        public string DDSP3 { get; set; }
        public string CJSHE { get; set; }
        public string DDBH1 { get; set; }
        public string DDBH2 { get; set; }
        public string DDBH3 { get; set; }
        public string CJBH { get; set; }
        public string BHUSER1 { get; set; }
        public string BHUSER2 { get; set; }
        public string BHUSER3 { get; set; }
        public string CJBHUSER { get; set; }
        public Nullable<System.DateTime> SUBMIT_DATE { get; set; }
        public string CHOUCHA_USER { get; set; }
        public Nullable<System.DateTime> CHOUCHA_TIME { get; set; }
        public string CJ_SHUSER { get; set; }
        public string DD_SHUSER1 { get; set; }
        public string DD_SHUSER2 { get; set; }
        public string DD_SHUSER3 { get; set; }
        public string UNDERWRITE { get; set; }
        public string BIANGENG { get; set; }
        public string BIANGENG_USER { get; set; }
        public string IPADDRESS { get; set; }
        public Nullable<short> DELPLAN { get; set; }
        public string IMGONE { get; set; }
        public string IMGTWO { get; set; }
        public string IMGTHREE { get; set; }
        public string IMGFOUR { get; set; }
        public string TONGYI { get; set; }
        public string POSITIONTYPE { get; set; }
        public Nullable<short> YESSIGN { get; set; }
        public string SHANG_TIME { get; set; }
        public string XIA_TIME { get; set; }
        public string YESSHIGONG { get; set; }
        public string PLANTYPE { get; set; }
        public Nullable<decimal> TEMPSB { get; set; }
        public Nullable<decimal> TEMPSH { get; set; }
        public Nullable<decimal> REJECTTEMP { get; set; }
        public Nullable<decimal> REJECTTIME { get; set; }
        public string REJECTUSE { get; set; }
        public string REASONNUM { get; set; }
        public Nullable<decimal> SENDTEMP { get; set; }
        public string REJECTVIEW { get; set; }
        public string TEMPSHVIEW { get; set; }
        public string TEMPSBUSER { get; set; }
        public string UPDOWNROAD { get; set; }
        public string SENDTEMPUSER { get; set; }
    }
}
