//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOL_JOB_PLAN_IMPORT
    {
        public string JOB_NO { get; set; }
        public string JOB_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string JOB_LEADER { get; set; }
        public string START_TIME { get; set; }
        public string PLAN_TOOL { get; set; }
        public Nullable<short> JOB_STATE { get; set; }
        public string DEPT_NAME { get; set; }
        public string END_TIME { get; set; }
    
        public virtual SYS_DEPT SYS_DEPT { get; set; }
    }
}
