//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURNOUT_HIS_BRANCH
    {
        public string BRANCH_ID { get; set; }
        public string HISTORY_ID { get; set; }
        public Nullable<decimal> BTANCH_LENGTH { get; set; }
        public Nullable<short> BRANCH_NUM { get; set; }
        public string BRANCH_NOTE { get; set; }
    
        public virtual TURNOUT_HISTORY TURNOUT_HISTORY { get; set; }
    }
}
