//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPEFLOOD_PHOTO
    {
        public string PHOTO_ID { get; set; }
        public string TYPEFLOOD_ID { get; set; }
        public string PHOTO_URL { get; set; }
        public string SMALL_URL { get; set; }
        public string PHOTO_DESC { get; set; }
    
        public virtual FLOODPOINT FLOODPOINT { get; set; }
    }
}
