//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class ALL_LINE_DATA
	{
		public ALL_LINE_DATA ToPOCO(bool isPOCO = true){
			return new ALL_LINE_DATA(){
				PKID = this.PKID,
				LJ_CODE = this.LJ_CODE,
				LJ_NAME = this.LJ_NAME,
				LINE_CODE = this.LINE_CODE,
				LINE_NAME = this.LINE_NAME,
			};
		}
	} 
}
