//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class ASSET_BASE_SUPPLIER_MATERIAL
	{
		public ASSET_BASE_SUPPLIER_MATERIAL ToPOCO(bool isPOCO = true){
			return new ASSET_BASE_SUPPLIER_MATERIAL(){
				SUPPLIER_MATERIAL_ID = this.SUPPLIER_MATERIAL_ID,
				SUPPLIER_CODE = this.SUPPLIER_CODE,
				MATERIAL_CODE = this.MATERIAL_CODE,
			};
		}
	} 
}
