//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class ASSET_BASE_SUPPLIER
	{
		public ASSET_BASE_SUPPLIER ToPOCO(bool isPOCO = true){
			return new ASSET_BASE_SUPPLIER(){
				SUPPLIER_CODE = this.SUPPLIER_CODE,
				SUPPLIER_NAME = this.SUPPLIER_NAME,
				SUPPLIER_SHORTNAME = this.SUPPLIER_SHORTNAME,
				SUPPLIER_TYPE = this.SUPPLIER_TYPE,
				ADDR = this.ADDR,
				ZIP_CODE = this.ZIP_CODE,
				CONTACT = this.CONTACT,
				TELPHONE = this.TELPHONE,
				FAX = this.FAX,
				IS_ENABLE = this.IS_ENABLE,
				MEMO = this.MEMO,
				DEPT_CODE = this.DEPT_CODE,
			};
		}
	} 
}
