//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class ASSET_MRP
	{
		public ASSET_MRP ToPOCO(bool isPOCO = true){
			return new ASSET_MRP(){
				MRP_ID = this.MRP_ID,
				GWD_CODE = this.GWD_CODE,
				DEPT_CODE = this.DEPT_CODE,
				MRP_YMD = this.MRP_YMD,
				MRP_NAEM = this.MRP_NAEM,
				PRI = this.PRI,
				MRP_STATUS = this.MRP_STATUS,
				TOTAL_COST = this.TOTAL_COST,
				NEED_DATE = this.NEED_DATE,
				MEMO = this.MEMO,
				CRT_TIME = this.CRT_TIME,
				CRT_USER = this.CRT_USER,
			};
		}
	} 
}
