//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class ASSET_BASE_MATERIAL_DIC
	{
		public ASSET_BASE_MATERIAL_DIC ToPOCO(bool isPOCO = true){
			return new ASSET_BASE_MATERIAL_DIC(){
				DIC_ID = this.DIC_ID,
				MATERIAL_CODE = this.MATERIAL_CODE,
				MATERIAL_NAME = this.MATERIAL_NAME,
				MATERIAL_TYPE = this.MATERIAL_TYPE,
				MATERIAL_RAW = this.MATERIAL_RAW,
				UNIT = this.UNIT,
				OUT_UNIT = this.OUT_UNIT,
				UNIT_WEIGHT = this.UNIT_WEIGHT,
				CATALOG_PRICE = this.CATALOG_PRICE,
				UNIT_PRICE = this.UNIT_PRICE,
				DWGNO = this.DWGNO,
				ABC_FLAG = this.ABC_FLAG,
				TRAIN_TYPE = this.TRAIN_TYPE,
				STANDARD_CODE = this.STANDARD_CODE,
				STANDARD_NAME = this.STANDARD_NAME,
				MANAGER_RULE = this.MANAGER_RULE,
				DEPT_CODE = this.DEPT_CODE,
				CATEGORY = this.CATEGORY,
				IS_IRON = this.IS_IRON,
				IS_RAIL = this.IS_RAIL,
				IS_COMMON_USE = this.IS_COMMON_USE,
				IS_ENABLE_RATE = this.IS_ENABLE_RATE,
				IS_IN_CHECK = this.IS_IN_CHECK,
				IS_TOOL = this.IS_TOOL,
				IS_KEYTOOL = this.IS_KEYTOOL,
				IS_TOOLKIT = this.IS_TOOLKIT,
				IS_LINE_TOOL = this.IS_LINE_TOOL,
				IS_BRIDGE_TOOL = this.IS_BRIDGE_TOOL,
				IS_CUSTOM = this.IS_CUSTOM,
				EXT_ATTR1 = this.EXT_ATTR1,
				EXT_ATTR2 = this.EXT_ATTR2,
				EXT_ATTR3 = this.EXT_ATTR3,
				MEMO = this.MEMO,
				QRCODE_FLAG = this.QRCODE_FLAG,
			};
		}
	} 
}
