//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class ASSET_BASE_RELATION_UNIT
	{
		public ASSET_BASE_RELATION_UNIT ToPOCO(bool isPOCO = true){
			return new ASSET_BASE_RELATION_UNIT(){
				RELATION_UNIT_CODE = this.RELATION_UNIT_CODE,
				RELATION_UNIT_NAME = this.RELATION_UNIT_NAME,
				ADDR = this.ADDR,
				ZIP_CODE = this.ZIP_CODE,
				CONTACT = this.CONTACT,
				TELPHONE = this.TELPHONE,
				FAX = this.FAX,
				IS_ENABLE = this.IS_ENABLE,
				MEMO = this.MEMO,
				DEPT_CODE = this.DEPT_CODE,
			};
		}
	} 
}
