//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class BASE_DICT
	{
		public BASE_DICT ToPOCO(bool isPOCO = true){
			return new BASE_DICT(){
				C_P_ID = this.C_P_ID,
				C_P_NAME = this.C_P_NAME,
				C_DICT_ID = this.C_DICT_ID,
				C_DICT_VALUE = this.C_DICT_VALUE,
				C_EFF_FLAG = this.C_EFF_FLAG,
				N_ORDER = this.N_ORDER,
				C_EFF_LEAF = this.C_EFF_LEAF,
			};
		}
	} 
}
