//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class BRIDGE_OVERPASS_WATER
	{
		public BRIDGE_OVERPASS_WATER ToPOCO(bool isPOCO = true){
			return new BRIDGE_OVERPASS_WATER(){
				OVERPASSWATER_ID = this.OVERPASSWATER_ID,
				GWD_CODE = this.GWD_CODE,
				CJ_CODE = this.CJ_CODE,
				GQ_CODE = this.GQ_CODE,
				LINE_CODE = this.LINE_CODE,
				LINE_DIR = this.LINE_DIR,
				CENTER_MILE = this.CENTER_MILE,
				HOLESPAN_STYLE = this.HOLESPAN_STYLE,
				BUILD_YEAR = this.BUILD_YEAR,
				DRAINAGE_STYLE = this.DRAINAGE_STYLE,
				DRAINAGE_EQUIP = this.DRAINAGE_EQUIP,
				ROAD_STRUCT = this.ROAD_STRUCT,
				REVETMENT_STYLE = this.REVETMENT_STYLE,
				WATER_SEVERITY = this.WATER_SEVERITY,
				WATER_NOWSTATUS = this.WATER_NOWSTATUS,
				AISLE_MATERIAL = this.AISLE_MATERIAL,
				AISLE_HEIGHTWIDTH = this.AISLE_HEIGHTWIDTH,
				RUN_STATUS = this.RUN_STATUS,
				MEMO = this.MEMO,
			};
		}
	} 
}
