//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class BRIDGE_MAINTENAN_PRO_HIS
	{
		public BRIDGE_MAINTENAN_PRO_HIS ToPOCO(bool isPOCO = true){
			return new BRIDGE_MAINTENAN_PRO_HIS(){
				PRO_HIS_ID = this.PRO_HIS_ID,
				PRO_ID = this.PRO_ID,
				GWD_CODE = this.GWD_CODE,
				CJ_CODE = this.CJ_CODE,
				GQ_CODE = this.GQ_CODE,
				LINE_CODE = this.LINE_CODE,
				LINE_DIR = this.LINE_DIR,
				EQU_CAT = this.EQU_CAT,
				CENTER_MILE = this.CENTER_MILE,
				EQU_CODE = this.EQU_CODE,
				EQU_NAME = this.EQU_NAME,
				MAINTAINCE_LENGTH = this.MAINTAINCE_LENGTH,
				CHECK_DATE = this.CHECK_DATE,
				CHECK_DEP_CODE = this.CHECK_DEP_CODE,
				CHECK_DEP_NAME = this.CHECK_DEP_NAME,
				CHECK_MAN = this.CHECK_MAN,
				ITEM_TYPE = this.ITEM_TYPE,
				ITEM_CODE = this.ITEM_CODE,
				ITEM_NAME = this.ITEM_NAME,
				PRO_PLACE = this.PRO_PLACE,
				ITEM_UNIT = this.ITEM_UNIT,
				ITEM_SCORE = this.ITEM_SCORE,
				CHECK_PRO_NUM = this.CHECK_PRO_NUM,
				CLEAR_PRO_NUM = this.CLEAR_PRO_NUM,
				EXIST_PRO_NUM = this.EXIST_PRO_NUM,
				AVG_SCORE = this.AVG_SCORE,
				EVALUATE_RES = this.EVALUATE_RES,
				CLEAR_PRO_LEADER = this.CLEAR_PRO_LEADER,
				CLEAR_PRO_DATE = this.CLEAR_PRO_DATE,
				RECHECK_MAN = this.RECHECK_MAN,
				RECHECK_DATE = this.RECHECK_DATE,
				RECHECK_RES = this.RECHECK_RES,
				MEMO = this.MEMO,
				PRO_STATUS = this.PRO_STATUS,
				MEMO2 = this.MEMO2,
				PRO_DESC = this.PRO_DESC,
				CRT_TM = this.CRT_TM,
				CRT_NAME = this.CRT_NAME,
				OP_TM = this.OP_TM,
				OP_NAME = this.OP_NAME,
			};
		}
	} 
}
