//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class BRIDGE_LRON_OVERPASS
	{
		public BRIDGE_LRON_OVERPASS ToPOCO(bool isPOCO = true){
			return new BRIDGE_LRON_OVERPASS(){
				LRON_OVERPASS_ID = this.LRON_OVERPASS_ID,
				GWD_CODE = this.GWD_CODE,
				CJ_CODE = this.CJ_CODE,
				GQ_CODE = this.GQ_CODE,
				LINE_CODE = this.LINE_CODE,
				LINE_DIR = this.LINE_DIR,
				CENTER_MILE = this.CENTER_MILE,
				BRIDGE_NAME = this.BRIDGE_NAME,
				BRIDGE_CODE = this.BRIDGE_CODE,
				HOLESPAN_STYLE = this.HOLESPAN_STYLE,
				BRIDGE_SECTION = this.BRIDGE_SECTION,
				ROAD_LINENAME = this.ROAD_LINENAME,
				ROAD_MILE = this.ROAD_MILE,
				HOLE_POSITION = this.HOLE_POSITION,
				MEMO = this.MEMO,
			};
		}
	} 
}
