//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class BRIDGE_LIMITOVERHEAD
	{
		public BRIDGE_LIMITOVERHEAD ToPOCO(bool isPOCO = true){
			return new BRIDGE_LIMITOVERHEAD(){
				LIMITOVERHEAD_ID = this.LIMITOVERHEAD_ID,
				GWD_CODE = this.GWD_CODE,
				CJ_CODE = this.CJ_CODE,
				GQ_CODE = this.GQ_CODE,
				LINE_CODE = this.LINE_CODE,
				LINE_DIR = this.LINE_DIR,
				CENTER_MILE = this.CENTER_MILE,
				RUN_STATUS = this.RUN_STATUS,
				HOLESPAN_STYLE = this.HOLESPAN_STYLE,
				CULVERT_CLEANHEIGHT = this.CULVERT_CLEANHEIGHT,
				CROSS_TYPE = this.CROSS_TYPE,
				CROSS_HOLETYPE = this.CROSS_HOLETYPE,
				STRUCTSTYLE_STAND = this.STRUCTSTYLE_STAND,
				STRUCTSTYLE_SIMPLE = this.STRUCTSTYLE_SIMPLE,
				LIMITOVERHEAD_NUM = this.LIMITOVERHEAD_NUM,
				LIMITOVERHEAD_CLEANHEIGHT = this.LIMITOVERHEAD_CLEANHEIGHT,
				LIMITCARD_NUM = this.LIMITCARD_NUM,
				CLEANWIDTH_LEFT = this.CLEANWIDTH_LEFT,
				CLEANWIDTH_RIGHT = this.CLEANWIDTH_RIGHT,
				DISTANCE_LEFT = this.DISTANCE_LEFT,
				DISTANCE_RIGHT = this.DISTANCE_RIGHT,
				HIT_IF = this.HIT_IF,
				ROAD_WIDTH = this.ROAD_WIDTH,
				ROAD_MATERIAL = this.ROAD_MATERIAL,
				ROAD_LEVEL = this.ROAD_LEVEL,
				ROAD_NAME = this.ROAD_NAME,
				MEMO = this.MEMO,
			};
		}
	} 
}
