//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class BRIDGE_STATE_REPORT
	{
		public BRIDGE_STATE_REPORT ToPOCO(bool isPOCO = true){
			return new BRIDGE_STATE_REPORT(){
				REPORT_ID = this.REPORT_ID,
				GWD_CODE = this.GWD_CODE,
				CJ_CODE = this.CJ_CODE,
				GQ_CODE = this.GQ_CODE,
				LINE_CODE = this.LINE_CODE,
				EQU_CAT = this.EQU_CAT,
				REPORT_DATE = this.REPORT_DATE,
				EQU_TOTAL = this.EQU_TOTAL,
				LEV_OVER_B = this.LEV_OVER_B,
				LEV_AA = this.LEV_AA,
				LEV_A1 = this.LEV_A1,
				LEV_C = this.LEV_C,
				MEMO = this.MEMO,
				LEV_B = this.LEV_B,
			};
		}
	} 
}
