//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class BRIDGE_EQU_CLEARANCE_FILE
	{
		public BRIDGE_EQU_CLEARANCE_FILE ToPOCO(bool isPOCO = true){
			return new BRIDGE_EQU_CLEARANCE_FILE(){
				FILE_ID = this.FILE_ID,
				CLEARANCE_ID = this.CLEARANCE_ID,
				FILE_CAT = this.FILE_CAT,
				FILE_DATE = this.FILE_DATE,
				FILE_NAME = this.FILE_NAME,
				FILE_DESC = this.FILE_DESC,
				CRT_TIME = this.CRT_TIME,
				MEMO = this.MEMO,
			};
		}
	} 
}
