//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class BROKENRAIL_BDATA_DEVICE_STATUS
	{
		public BROKENRAIL_BDATA_DEVICE_STATUS ToPOCO(bool isPOCO = true){
			return new BROKENRAIL_BDATA_DEVICE_STATUS(){
				POINT_NO = this.POINT_NO,
				LEFT_LEFT = this.LEFT_LEFT,
				LEFT_RIGHT = this.LEFT_RIGHT,
				RIGHT_LEFT = this.RIGHT_LEFT,
				RIGHT_RIGHT = this.RIGHT_RIGHT,
				POINT_NAME = this.POINT_NAME,
			};
		}
	} 
}
