//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class BROKENRAIL_BDATA_SECTION
	{
		public BROKENRAIL_BDATA_SECTION ToPOCO(bool isPOCO = true){
			return new BROKENRAIL_BDATA_SECTION(){
				SECTION_NAME = this.SECTION_NAME,
				DEPT_CODE = this.DEPT_CODE,
				START_MILE = this.START_MILE,
				END_MILE = this.END_MILE,
				SECTION_ID = this.SECTION_ID,
				LINE_NAME = this.LINE_NAME,
				LINE_DIR = this.LINE_DIR,
				GC_VOL = this.GC_VOL,
				ENVIRONMENT_VOL = this.ENVIRONMENT_VOL,
				START_SCALER_INDEX = this.START_SCALER_INDEX,
				END_SCALER_INDEX = this.END_SCALER_INDEX,
				STATION_STATION = this.STATION_STATION,
			};
		}
	} 
}
