//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class CAR_OVERSPEED_WARN
	{
		public CAR_OVERSPEED_WARN ToPOCO(bool isPOCO = true){
			return new CAR_OVERSPEED_WARN(){
				LICENSENO = this.LICENSENO,
				OVERSPEED = this.OVERSPEED,
				OVERSPEED_TIME = this.OVERSPEED_TIME,
				WARNSPEED = this.WARNSPEED,
				CARNO = this.CARNO,
				DEPT_CODE = this.DEPT_CODE,
			};
		}
	} 
}
