//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class CAR_BDATA_CAR
	{
		public CAR_BDATA_CAR ToPOCO(bool isPOCO = true){
			return new CAR_BDATA_CAR(){
				CAR_NO = this.CAR_NO,
				CAR_LICENSENO = this.CAR_LICENSENO,
				DEPT_CODE = this.DEPT_CODE,
				CAR_TYPE = this.CAR_TYPE,
				CAR_BRAND = this.CAR_BRAND,
				CAR_MODEL = this.CAR_MODEL,
				CAR_BUYDATE = this.CAR_BUYDATE,
				CAR_PURPOSE = this.CAR_PURPOSE,
				OIL_TYPE = this.OIL_TYPE,
				CAR_DISPLAYMENT = this.CAR_DISPLAYMENT,
				CAR_LOADNO = this.CAR_LOADNO,
				CAR_LOADWEIGHT = this.CAR_LOADWEIGHT,
				CAR_INSURANCEDATE = this.CAR_INSURANCEDATE,
				CAR_TESTDATE = this.CAR_TESTDATE,
				CAR_WARNSPEED = this.CAR_WARNSPEED,
				CAR_NOTE = this.CAR_NOTE,
				CAR_KWH = this.CAR_KWH,
				OIL_PRICE = this.OIL_PRICE,
				PKID = this.PKID,
				LAST_TIME = this.LAST_TIME,
				OIL_UNIT = this.OIL_UNIT,
				MILEAGE_SUM = this.MILEAGE_SUM,
				CAR_SPEED = this.CAR_SPEED,
				OIL_SURPLUS = this.OIL_SURPLUS,
				OIL_SURPLUS_UNIT = this.OIL_SURPLUS_UNIT,
				MILEAGE_MAINTAIN = this.MILEAGE_MAINTAIN,
				OVERSPEED_NUM = this.OVERSPEED_NUM,
				NOOVERSPEED_NUM = this.NOOVERSPEED_NUM,
			};
		}
	} 
}
