//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class CONFIR_CAR_WARN
	{
		public CONFIR_CAR_WARN ToPOCO(bool isPOCO = true){
			return new CONFIR_CAR_WARN(){
				PKID = this.PKID,
				CARPLAN_PKID = this.CARPLAN_PKID,
				WARN_CONTENT = this.WARN_CONTENT,
				WARN_TIME = this.WARN_TIME,
				WARN_TYPE = this.WARN_TYPE,
				WARN_STATE = this.WARN_STATE,
				RELEASE_USER = this.RELEASE_USER,
				RELEASE_TIME = this.RELEASE_TIME,
				DEPT_CODE = this.DEPT_CODE,
				RELEASE_NOTE = this.RELEASE_NOTE,
			};
		}
	} 
}
