//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class CURVE_RAILWEAR
	{
		public CURVE_RAILWEAR ToPOCO(bool isPOCO = true){
			return new CURVE_RAILWEAR(){
				PKID = this.PKID,
				RAIL = this.RAIL,
				WEARTYPE = this.WEARTYPE,
				MINSPEED = this.MINSPEED,
				MAXSPEED = this.MAXSPEED,
				WEARVALUE = this.WEARVALUE,
				TYPE = this.TYPE,
				C_MEMO = this.C_MEMO,
			};
		}
	} 
}
