//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class DR_IDX_DOC_CONTENT_N
	{
		public DR_IDX_DOC_CONTENT_N ToPOCO(bool isPOCO = true){
			return new DR_IDX_DOC_CONTENT_N(){
				NLT_DOCID = this.NLT_DOCID,
				NLT_MARK = this.NLT_MARK,
			};
		}
	} 
}
