//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class EMERGENCY_VIECHLE
	{
		public EMERGENCY_VIECHLE ToPOCO(bool isPOCO = true){
			return new EMERGENCY_VIECHLE(){
				VIECHLE_ID = this.VIECHLE_ID,
				RWB_CODE = this.RWB_CODE,
				RWB_NAME = this.RWB_NAME,
				GWD_CODE = this.GWD_CODE,
				GWD_NAME = this.GWD_NAME,
				CJ_NAME = this.CJ_NAME,
				GQ_NAME = this.GQ_NAME,
				LINE_CODE = this.LINE_CODE,
				LINE_NAME = this.LINE_NAME,
				V_TAB_CAT = this.V_TAB_CAT,
				V_RADIUS = this.V_RADIUS,
				V_GRADIENT = this.V_GRADIENT,
				V_DATETIME = this.V_DATETIME,
				V_ADDR = this.V_ADDR,
				V_CONST = this.V_CONST,
				VIECHLE_CODE = this.VIECHLE_CODE,
				BREAK_CAT = this.BREAK_CAT,
				V_WEATHER = this.V_WEATHER,
				V_MA = this.V_MA,
				V_TRACOUNT = this.V_TRACOUNT,
				V_DRIVER = this.V_DRIVER,
				V_DEPT = this.V_DEPT,
				V_REMA = this.V_REMA,
				V_REDRI = this.V_REDRI,
				V_VIECHLE = this.V_VIECHLE,
				VIECHLE_LEADER = this.VIECHLE_LEADER,
				VIECHLE_NUM = this.VIECHLE_NUM,
				V_HAP = this.V_HAP,
				V_CHECK = this.V_CHECK,
				V_REOLD = this.V_REOLD,
				V_DUTY = this.V_DUTY,
				VIECHLE_TYPE = this.VIECHLE_TYPE,
				VIECHLE_ADDR = this.VIECHLE_ADDR,
				A_REPAIR = this.A_REPAIR,
				R_DEPT = this.R_DEPT,
				R_DATE = this.R_DATE,
				F_REPAIR = this.F_REPAIR,
				D_REPAIR = this.D_REPAIR,
				AU_REPAIR = this.AU_REPAIR,
				T_REPAIR = this.T_REPAIR,
				TYPE_NAME = this.TYPE_NAME,
				EMP_FUL = this.EMP_FUL,
				STATION_FROM = this.STATION_FROM,
				STATION_TO = this.STATION_TO,
				VIECHLE_CHECK = this.VIECHLE_CHECK,
				CHECK_LIST = this.CHECK_LIST,
				BREAK_DIS = this.BREAK_DIS,
				DEV_BRE = this.DEV_BRE,
				BRE_RES = this.BRE_RES,
				DU_DEPT = this.DU_DEPT,
				REP_DEPT = this.REP_DEPT,
				REP_NAME = this.REP_NAME,
				REP_DATE = this.REP_DATE,
				REP_NUM = this.REP_NUM,
				MARK = this.MARK,
				REMARK = this.REMARK,
				MEMO = this.MEMO,
				R_DATEF = this.R_DATEF,
				R_DATED = this.R_DATED,
				R_DATEAU = this.R_DATEAU,
				R_DATET = this.R_DATET,
				V_TAB_CODE = this.V_TAB_CODE,
			};
		}
	} 
}
