//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class FIVET_INFO_PHOTO
	{
		public FIVET_INFO_PHOTO ToPOCO(bool isPOCO = true){
			return new FIVET_INFO_PHOTO(){
				PHOTO_ID = this.PHOTO_ID,
				FIVET_ID = this.FIVET_ID,
				PHOTOURL = this.PHOTOURL,
				SMALLURL = this.SMALLURL,
			};
		}
	} 
}
