//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class FLOW_JOB
	{
		public FLOW_JOB ToPOCO(bool isPOCO = true){
			return new FLOW_JOB(){
				FLOW_ID = this.FLOW_ID,
				JOB_ID = this.JOB_ID,
				DEPT_CODE = this.DEPT_CODE,
				JOB_DATE = this.JOB_DATE,
				CREATE_USER = this.CREATE_USER,
				CREATETIME = this.CREATETIME,
				EDITOR = this.EDITOR,
				EDIT_STATUS = this.EDIT_STATUS,
				SUBMITTIME = this.SUBMITTIME,
				STEPNO = this.STEPNO,
				STEP_STATUS = this.STEP_STATUS,
				NEXT_STEPNO = this.NEXT_STEPNO,
				ISENDSTEP = this.ISENDSTEP,
				ISFINISHED = this.ISFINISHED,
				CJ_CODE = this.CJ_CODE,
				CJ_AUDIT = this.CJ_AUDIT,
				CJ_LEADER = this.CJ_LEADER,
				CJ_AUDITTIME = this.CJ_AUDITTIME,
				GW_CODE = this.GW_CODE,
				GWD_AUDIT = this.GWD_AUDIT,
				GWD_LEADER = this.GWD_LEADER,
				GWD_AUDITTIME = this.GWD_AUDITTIME,
				GWC_AUDIT = this.GWC_AUDIT,
				GWC_LEADER = this.GWC_LEADER,
				GWC_AUDITTIME = this.GWC_AUDITTIME,
				ISREJECT = this.ISREJECT,
				REJECT_COMMENT = this.REJECT_COMMENT,
				MEMO = this.MEMO,
			};
		}
	} 
}
