//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class GATE_GATEMNG_WARNING
	{
		public GATE_GATEMNG_WARNING ToPOCO(bool isPOCO = true){
			return new GATE_GATEMNG_WARNING(){
				WARNING_ID = this.WARNING_ID,
				GATE_NO = this.GATE_NO,
				WARNING_INFO = this.WARNING_INFO,
				WARNING_TIME = this.WARNING_TIME,
				WARNING_TYPE = this.WARNING_TYPE,
				WARNING_LOG = this.WARNING_LOG,
				WARNING_FLAG = this.WARNING_FLAG,
				WARNING_FROM = this.WARNING_FROM,
				CARD_NO = this.CARD_NO,
				GNAME = this.GNAME,
				GMOBILE = this.GMOBILE,
				GDEPTNAME = this.GDEPTNAME,
				AUTHHIS_ID = this.AUTHHIS_ID,
				UNWARN_TIME = this.UNWARN_TIME,
				UNWARN_USER = this.UNWARN_USER,
				UNWARN_REASON = this.UNWARN_REASON,
				AUTHOPT_SECTION = this.AUTHOPT_SECTION,
			};
		}
	} 
}
