//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class GATE_GATEMNG_INOUTHIS
	{
		public GATE_GATEMNG_INOUTHIS ToPOCO(bool isPOCO = true){
			return new GATE_GATEMNG_INOUTHIS(){
				CARD_NO = this.CARD_NO,
				LST_TIME = this.LST_TIME,
				LST_ORDER = this.LST_ORDER,
				CARD_TYPE = this.CARD_TYPE,
				CARD_SECTION = this.CARD_SECTION,
				INGATE_NO = this.INGATE_NO,
				INGATE_TIME = this.INGATE_TIME,
				OUTGATE_NO = this.OUTGATE_NO,
				OUTGATE_TIME = this.OUTGATE_TIME,
				GNAME = this.GNAME,
				GMOBILE = this.GMOBILE,
				GDEPTNAME = this.GDEPTNAME,
			};
		}
	} 
}
