//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class GATE_BDATA_CARD
	{
		public GATE_BDATA_CARD ToPOCO(bool isPOCO = true){
			return new GATE_BDATA_CARD(){
				CARD_NO = this.CARD_NO,
				MEMBER_ID = this.MEMBER_ID,
				DEPT_CODE = this.DEPT_CODE,
				CARD_STATE = this.CARD_STATE,
				CARD_INDATE = this.CARD_INDATE,
				CARD_DELDATE = this.CARD_DELDATE,
				CARD_NOTE = this.CARD_NOTE,
				CARD_TYPE = this.CARD_TYPE,
				TOOL_ID = this.TOOL_ID,
				CARD_SECTION = this.CARD_SECTION,
			};
		}
	} 
}
