//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class GATE_GATEMNG_INOUT
	{
		public GATE_GATEMNG_INOUT ToPOCO(bool isPOCO = true){
			return new GATE_GATEMNG_INOUT(){
				INOUT_ID = this.INOUT_ID,
				GATE_NO = this.GATE_NO,
				CARD_NO = this.CARD_NO,
				INOUT_TIME = this.INOUT_TIME,
				INOUT_FLAG = this.INOUT_FLAG,
				READCARD_FLAG = this.READCARD_FLAG,
				INOUT_STATE = this.INOUT_STATE,
				INOUT_LOG = this.INOUT_LOG,
				INOUT_ORDER = this.INOUT_ORDER,
			};
		}
	} 
}
