//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class GATE_SEND_PHONENO
	{
		public GATE_SEND_PHONENO ToPOCO(bool isPOCO = true){
			return new GATE_SEND_PHONENO(){
				ID = this.ID,
				GATE_NO = this.GATE_NO,
				PHONE_NO = this.PHONE_NO,
				PHONE_ROLE = this.PHONE_ROLE,
				DEPT_CODE = this.DEPT_CODE,
				NOTE = this.NOTE,
				UPDATE_USER = this.UPDATE_USER,
				UPDATE_DATE = this.UPDATE_DATE,
			};
		}
	} 
}
