//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class GATE_GATEMNG_LASTCARDLIST
	{
		public GATE_GATEMNG_LASTCARDLIST ToPOCO(bool isPOCO = true){
			return new GATE_GATEMNG_LASTCARDLIST(){
				LIST_ID = this.LIST_ID,
				GATE_NO = this.GATE_NO,
				CARD_NO = this.CARD_NO,
				CARD_SECTION = this.CARD_SECTION,
				LIST_DATE = this.LIST_DATE,
				OP_USER = this.OP_USER,
				OP_TIME = this.OP_TIME,
				OP_TYPE = this.OP_TYPE,
				OP_RESULT = this.OP_RESULT,
			};
		}
	} 
}
