//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class GATE_GATEMNG_INGATE
	{
		public GATE_GATEMNG_INGATE ToPOCO(bool isPOCO = true){
			return new GATE_GATEMNG_INGATE(){
				GATE_NO = this.GATE_NO,
				CARD_NO = this.CARD_NO,
				INOUT_TIME = this.INOUT_TIME,
				INOUT_STATE = this.INOUT_STATE,
				GNAME = this.GNAME,
				GMOBILE = this.GMOBILE,
				GDEPTNAME = this.GDEPTNAME,
				INOUT_ORDER = this.INOUT_ORDER,
				INOROUT = this.INOROUT,
				GATE_NO_OUT = this.GATE_NO_OUT,
				CARD_TYPE = this.CARD_TYPE,
				CARD_SECTION = this.CARD_SECTION,
				IN_TIME = this.IN_TIME,
				OUT_TIME = this.OUT_TIME,
			};
		}
	} 
}
