//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class HEART_RECENT_SA
	{
		public HEART_RECENT_SA ToPOCO(bool isPOCO = true){
			return new HEART_RECENT_SA(){
				手机号 = this.手机号,
				A37LT = this.A37LT,
				A37L = this.A37L,
				A37RT = this.A37RT,
				A37R = this.A37R,
				A27LT = this.A27LT,
				A27L = this.A27L,
				A27RT = this.A27RT,
				A27R = this.A27R,
			};
		}
	} 
}
