//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class HRAIL_PLAN_ITEM
	{
		public HRAIL_PLAN_ITEM ToPOCO(bool isPOCO = true){
			return new HRAIL_PLAN_ITEM(){
				FLOW_ID = this.FLOW_ID,
				PLAN_ID = this.PLAN_ID,
				LOC_ID = this.LOC_ID,
				ITEM_ID = this.ITEM_ID,
				ITEM_TYPE = this.ITEM_TYPE,
				ITEM_CODE = this.ITEM_CODE,
				PLAN_NUM = this.PLAN_NUM,
				JOB_NUM = this.JOB_NUM,
				CHECK_TYPE = this.CHECK_TYPE,
				CHECK_PLAN_ID = this.CHECK_PLAN_ID,
				UNDERLINE_JOB = this.UNDERLINE_JOB,
				MEMO = this.MEMO,
			};
		}
	} 
}
