//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class HRAIL_UNIT_VAL
	{
		public HRAIL_UNIT_VAL ToPOCO(bool isPOCO = true){
			return new HRAIL_UNIT_VAL(){
				UNITVAL_ID = this.UNITVAL_ID,
				GWD_CODE = this.GWD_CODE,
				CJ_CODE = this.CJ_CODE,
				GQ_CODE = this.GQ_CODE,
				LINE_CODE = this.LINE_CODE,
				LINE_DIR = this.LINE_DIR,
				LINE_CAT = this.LINE_CAT,
				START_MILE = this.START_MILE,
				END_MILE = this.END_MILE,
				STATION_CODE = this.STATION_CODE,
				TURNOUT_CODE = this.TURNOUT_CODE,
				TRACK_CODE = this.TRACK_CODE,
				UNIT_NO = this.UNIT_NO,
				UNIT_CAT = this.UNIT_CAT,
				STATIC_SCORE = this.STATIC_SCORE,
				DYNAMIC_SCORE = this.DYNAMIC_SCORE,
				WEIGHT = this.WEIGHT,
				SCORE = this.SCORE,
				TQI_VALUE = this.TQI_VALUE,
				TQI_SCORE = this.TQI_SCORE,
				EVALUE_GRADE = this.EVALUE_GRADE,
				EVALUE_DATE = this.EVALUE_DATE,
				MEMO = this.MEMO,
				CRT_TM = this.CRT_TM,
				CRT_NAME = this.CRT_NAME,
			};
		}
	} 
}
