//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class HRAIL_PARA_PROITEM
	{
		public HRAIL_PARA_PROITEM ToPOCO(bool isPOCO = true){
			return new HRAIL_PARA_PROITEM(){
				CHECK_TYPE = this.CHECK_TYPE,
				ITEM_CAT = this.ITEM_CAT,
				ITEM_SUBCAT = this.ITEM_SUBCAT,
				ITEM_TYPE = this.ITEM_TYPE,
				ITEM_CODE = this.ITEM_CODE,
				ITEM_NAME = this.ITEM_NAME,
				ITEM_UNIT = this.ITEM_UNIT,
				ITEM_SCORE = this.ITEM_SCORE,
				FLAG = this.FLAG,
				MEMO = this.MEMO,
			};
		}
	} 
}
