//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class HRAIL_STARTMILE
	{
		public HRAIL_STARTMILE ToPOCO(bool isPOCO = true){
			return new HRAIL_STARTMILE(){
				STRATMILE_ID = this.STRATMILE_ID,
				GWD_CODE = this.GWD_CODE,
				CJ_CODE = this.CJ_CODE,
				GQ_CODE = this.GQ_CODE,
				LINE_CODE = this.LINE_CODE,
				LINE_DIR = this.LINE_DIR,
				RUN_STATUS = this.RUN_STATUS,
				LINE_TYPE = this.LINE_TYPE,
				GAUGE_TYPE = this.GAUGE_TYPE,
				START_MILE = this.START_MILE,
				END_MILE = this.END_MILE,
				START_STATIONNAME = this.START_STATIONNAME,
				START_STATIONCODE = this.START_STATIONCODE,
				START_POSITION = this.START_POSITION,
				END_STATIONNAME = this.END_STATIONNAME,
				END_STATIONCODE = this.END_STATIONCODE,
				END_POSITION = this.END_POSITION,
				EXTENSION_LENGTH = this.EXTENSION_LENGTH,
				COMPARE_ADDREDUCE = this.COMPARE_ADDREDUCE,
				STAND_SYS = this.STAND_SYS,
				MEMO = this.MEMO,
			};
		}
	} 
}
