//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class HRAIL_TRACK
	{
		public HRAIL_TRACK ToPOCO(bool isPOCO = true){
			return new HRAIL_TRACK(){
				TRACK_ID = this.TRACK_ID,
				GWD_CODE = this.GWD_CODE,
				CJ_CODE = this.CJ_CODE,
				GQ_CODE = this.GQ_CODE,
				LINE_CODE = this.LINE_CODE,
				LINE_DIR = this.LINE_DIR,
				STATION_NAME = this.STATION_NAME,
				STATION_CODE = this.STATION_CODE,
				LINE_CAT = this.LINE_CAT,
				RUN_STATUS = this.RUN_STATUS,
				TRACK_CODE = this.TRACK_CODE,
				LINE_TYPE = this.LINE_TYPE,
				GAUGE_TYPE = this.GAUGE_TYPE,
				VALID_LEN = this.VALID_LEN,
				FULL_LEN = this.FULL_LEN,
				WOOD_TIE_NUM = this.WOOD_TIE_NUM,
				CONCRETE_TIE_NUM = this.CONCRETE_TIE_NUM,
				STEEL_TIE_NUM = this.STEEL_TIE_NUM,
				BROAD_TIE_NUM = this.BROAD_TIE_NUM,
				LEFT_SPACING = this.LEFT_SPACING,
				RIGHT_SPACING = this.RIGHT_SPACING,
				CURVE_RADIUS = this.CURVE_RADIUS,
				DIR = this.DIR,
				MAX_GRADE = this.MAX_GRADE,
				GRADESECT_LEN = this.GRADESECT_LEN,
				RAIL_TYPE = this.RAIL_TYPE,
				EXTEND_LINE = this.EXTEND_LINE,
				EXTEN_JOINTLESS = this.EXTEN_JOINTLESS,
				MEMO = this.MEMO,
			};
		}
	} 
}
