//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class HRAIL_PROBLEM
	{
		public HRAIL_PROBLEM ToPOCO(bool isPOCO = true){
			return new HRAIL_PROBLEM(){
				PROBLEM_ID = this.PROBLEM_ID,
				GWD_CODE = this.GWD_CODE,
				CJ_CODE = this.CJ_CODE,
				GQ_CODE = this.GQ_CODE,
				LINE_CODE = this.LINE_CODE,
				LINE_DIR = this.LINE_DIR,
				LINE_CAT = this.LINE_CAT,
				PRO_MILE = this.PRO_MILE,
				PRO_MILE2 = this.PRO_MILE2,
				EXTEND_LEN = this.EXTEND_LEN,
				STATION_CODE = this.STATION_CODE,
				TRACK_CODE = this.TRACK_CODE,
				TURNOUT_CODE = this.TURNOUT_CODE,
				EQU_NAME = this.EQU_NAME,
				EQU_CODE = this.EQU_CODE,
				UNIT_NO = this.UNIT_NO,
				TRACK_DIR = this.TRACK_DIR,
				SIDE_DIR = this.SIDE_DIR,
				TRACK_SLAB_NO = this.TRACK_SLAB_NO,
				SUPPORT_TRACK_NO = this.SUPPORT_TRACK_NO,
				RAIL_NO = this.RAIL_NO,
				SLEEPER_NO = this.SLEEPER_NO,
				TRUNOUT_PART = this.TRUNOUT_PART,
				LINE_SHARP = this.LINE_SHARP,
				LINE_FEATURE = this.LINE_FEATURE,
				SPECIAL_CAT = this.SPECIAL_CAT,
				PRO_CAT = this.PRO_CAT,
				PRO_SUBCAT = this.PRO_SUBCAT,
				PRO_TYPE = this.PRO_TYPE,
				PRO_CODE = this.PRO_CODE,
				PRO_NAME = this.PRO_NAME,
				PRO_UNIT = this.PRO_UNIT,
				PRO_PEAK = this.PRO_PEAK,
				PRO_PEAK2 = this.PRO_PEAK2,
				PRO_PEAK3 = this.PRO_PEAK3,
				PRO_SCORE = this.PRO_SCORE,
				PRO_PLACE = this.PRO_PLACE,
				PRO_PLACE2 = this.PRO_PLACE2,
				PRO_DETAIL = this.PRO_DETAIL,
				OVERRUN_LEVEL = this.OVERRUN_LEVEL,
				PRO_LEVEL = this.PRO_LEVEL,
				PRO_GRADE = this.PRO_GRADE,
				PRO_STATUS = this.PRO_STATUS,
				SPEED = this.SPEED,
				SPEED2 = this.SPEED2,
				TRAIN_MODEL = this.TRAIN_MODEL,
				TRAIN_NO = this.TRAIN_NO,
				LOCO_NO = this.LOCO_NO,
				CHECK_PLAN_ID = this.CHECK_PLAN_ID,
				CHECK_DEPT = this.CHECK_DEPT,
				CHECK_MAN = this.CHECK_MAN,
				CHECK_MAN_POST = this.CHECK_MAN_POST,
				CHECK_DATE = this.CHECK_DATE,
				CHECK_TYPE = this.CHECK_TYPE,
				CHECK_DEV = this.CHECK_DEV,
				CHECK_CAT = this.CHECK_CAT,
				JOB_PLAN_ID = this.JOB_PLAN_ID,
				REPAIR_SCENE = this.REPAIR_SCENE,
				REPEAT_NUM = this.REPEAT_NUM,
				REPAIR_DATE = this.REPAIR_DATE,
				REPAIR_MAN = this.REPAIR_MAN,
				REPAIR_RES = this.REPAIR_RES,
				RANDOM_INS_DATE = this.RANDOM_INS_DATE,
				RANDOM_INS_DEPT = this.RANDOM_INS_DEPT,
				RANDOM_INS_NAME = this.RANDOM_INS_NAME,
				RANDOM_INS_RES = this.RANDOM_INS_RES,
				RANDOM_INS_STATUS = this.RANDOM_INS_STATUS,
				CLEAR_TYPE = this.CLEAR_TYPE,
				CLEAR_MAN = this.CLEAR_MAN,
				CLEAR_DATE = this.CLEAR_DATE,
				AUDIT_STATUS = this.AUDIT_STATUS,
				AUDIT_MAN = this.AUDIT_MAN,
				AUDIT_DATE = this.AUDIT_DATE,
				WARN_FLAG = this.WARN_FLAG,
				EFF_FLAG = this.EFF_FLAG,
				MARK = this.MARK,
				MEMO = this.MEMO,
				CRT_TM = this.CRT_TM,
				CRT_NAME = this.CRT_NAME,
			};
		}
	} 
}
