//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class HRAIL_STATION
	{
		public HRAIL_STATION ToPOCO(bool isPOCO = true){
			return new HRAIL_STATION(){
				STATION_ID = this.STATION_ID,
				GWD_CODE = this.GWD_CODE,
				CJ_CODE = this.CJ_CODE,
				GQ_CODE = this.GQ_CODE,
				STATION_NAME = this.STATION_NAME,
				STATION_CODE = this.STATION_CODE,
				RUN_STATUS = this.RUN_STATUS,
				LINE_CODE = this.LINE_CODE,
				THREAD_SIGN = this.THREAD_SIGN,
				LINE_DIR = this.LINE_DIR,
				PY_PREFIX = this.PY_PREFIX,
				SKILL_WORK = this.SKILL_WORK,
				BUSINESS_TYPE = this.BUSINESS_TYPE,
				STATION_GRADE = this.STATION_GRADE,
				GAUGE_TYPE = this.GAUGE_TYPE,
				CENTER_MILE = this.CENTER_MILE,
				AREA_MILE = this.AREA_MILE,
				MIN_RADIUS = this.MIN_RADIUS,
				MAX_SLOPE = this.MAX_SLOPE,
				TRACK_NUM = this.TRACK_NUM,
				TURNOUT_NUM = this.TURNOUT_NUM,
				DOWN_INMAC = this.DOWN_INMAC,
				DOWN_VALID = this.DOWN_VALID,
				UP_INMAC = this.UP_INMAC,
				UP_VALID = this.UP_VALID,
				N_LONGITUDE = this.N_LONGITUDE,
				N_LATITUDE = this.N_LATITUDE,
				C_MEMO = this.C_MEMO,
			};
		}
	} 
}
