//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class HRAIL_PLAN_LOC
	{
		public HRAIL_PLAN_LOC ToPOCO(bool isPOCO = true){
			return new HRAIL_PLAN_LOC(){
				FLOW_ID = this.FLOW_ID,
				PLAN_ID = this.PLAN_ID,
				LOC_ID = this.LOC_ID,
				DEPT_CODE = this.DEPT_CODE,
				PLAN_DATE = this.PLAN_DATE,
				LINE_CODE = this.LINE_CODE,
				LINE_DIR = this.LINE_DIR,
				STATION_CODE = this.STATION_CODE,
				START_MILE = this.START_MILE,
				END_MILE = this.END_MILE,
				TRACK_CODE = this.TRACK_CODE,
				TURNOUT_CODE = this.TURNOUT_CODE,
				BRIDGE_CODE = this.BRIDGE_CODE,
				JOB_LINE_CODE = this.JOB_LINE_CODE,
				JOB_LINE_DIR = this.JOB_LINE_DIR,
				JOB_STATION_CODE = this.JOB_STATION_CODE,
				JOB_START_MILE = this.JOB_START_MILE,
				JOB_END_MILE = this.JOB_END_MILE,
				JOB_TRACK_CODE = this.JOB_TRACK_CODE,
				JOB_TURNOUT_CODE = this.JOB_TURNOUT_CODE,
				JOB_BRIDGE_CODE = this.JOB_BRIDGE_CODE,
				MEMO = this.MEMO,
			};
		}
	} 
}
