//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class HRAIL_CURVE
	{
		public HRAIL_CURVE ToPOCO(bool isPOCO = true){
			return new HRAIL_CURVE(){
				CURVE_ID = this.CURVE_ID,
				GWD_CODE = this.GWD_CODE,
				CJ_CODE = this.CJ_CODE,
				GQ_CODE = this.GQ_CODE,
				LINE_CODE = this.LINE_CODE,
				LINE_DIR = this.LINE_DIR,
				LINE_CAT = this.LINE_CAT,
				RUN_STATUS = this.RUN_STATUS,
				START_MILE = this.START_MILE,
				END_MILE = this.END_MILE,
				LONGCHAIN_MARK = this.LONGCHAIN_MARK,
				CURVE_DIR = this.CURVE_DIR,
				CURVE_RADIUS = this.CURVE_RADIUS,
				DEFLECTION_ANGLE = this.DEFLECTION_ANGLE,
				GAUGE_TYPE = this.GAUGE_TYPE,
				GAUGE_WIDEN = this.GAUGE_WIDEN,
				SUPHIGH = this.SUPHIGH,
				SLOPE_RATE = this.SLOPE_RATE,
				START_TANGENT = this.START_TANGENT,
				START_ALLAYLINE = this.START_ALLAYLINE,
				END_ALLAYLINE = this.END_ALLAYLINE,
				END_TANGENT = this.END_TANGENT,
				CURVE_FULLLEN = this.CURVE_FULLLEN,
				AVG_SPEED = this.AVG_SPEED,
				SORT_RADIUS = this.SORT_RADIUS,
				MEMO = this.MEMO,
			};
		}
	} 
}
