//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class HRAIL_PROBLEM_FILE
	{
		public HRAIL_PROBLEM_FILE ToPOCO(bool isPOCO = true){
			return new HRAIL_PROBLEM_FILE(){
				PROBLEM_FILE_ID = this.PROBLEM_FILE_ID,
				PROBLEM_ID = this.PROBLEM_ID,
				CHECK_TYPE = this.CHECK_TYPE,
				FILE_CAT = this.FILE_CAT,
				FILE_NAME = this.FILE_NAME,
				FILE_DESC = this.FILE_DESC,
				CRT_TIME = this.CRT_TIME,
				CRT_NAME = this.CRT_NAME,
			};
		}
	} 
}
