//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class HRAIL_TQI
	{
		public HRAIL_TQI ToPOCO(bool isPOCO = true){
			return new HRAIL_TQI(){
				TQI_ID = this.TQI_ID,
				GWD_CODE = this.GWD_CODE,
				CJ_CODE = this.CJ_CODE,
				GQ_CODE = this.GQ_CODE,
				LINE_CODE = this.LINE_CODE,
				LINE_DIR = this.LINE_DIR,
				LINE_CAT = this.LINE_CAT,
				TQI_MILE = this.TQI_MILE,
				OVERRUN = this.OVERRUN,
				TRACK_LEFT = this.TRACK_LEFT,
				TRACK_RIGHT = this.TRACK_RIGHT,
				HEGHT_LEFT = this.HEGHT_LEFT,
				HEGHT_RIGHT = this.HEGHT_RIGHT,
				TRACK_CROSSLEVEL = this.TRACK_CROSSLEVEL,
				RAIL_GAUGE = this.RAIL_GAUGE,
				TWIST = this.TWIST,
				TQI_VAL = this.TQI_VAL,
				TQI_OVER = this.TQI_OVER,
				SPEED = this.SPEED,
				SPEED2 = this.SPEED2,
				SPEED_SPAN = this.SPEED_SPAN,
				CHECK_DATE = this.CHECK_DATE,
				JOB_PLAN_ID = this.JOB_PLAN_ID,
				REPAIR_DATE = this.REPAIR_DATE,
				REPAIR_MAN = this.REPAIR_MAN,
				REPAIR_RES = this.REPAIR_RES,
				MEMO = this.MEMO,
				CRT_TM = this.CRT_TM,
				CRT_NAME = this.CRT_NAME,
			};
		}
	} 
}
