//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class HRAIL_CROSSING
	{
		public HRAIL_CROSSING ToPOCO(bool isPOCO = true){
			return new HRAIL_CROSSING(){
				CROSSING_ID = this.CROSSING_ID,
				GWD_CODE = this.GWD_CODE,
				CJ_CODE = this.CJ_CODE,
				GQ_CODE = this.GQ_CODE,
				LINE_CODE = this.LINE_CODE,
				LINE_DIR = this.LINE_DIR,
				RUN_STATUS = this.RUN_STATUS,
				CROSSING_FLAG = this.CROSSING_FLAG,
				STATION_NAME = this.STATION_NAME,
				STATION_CODE = this.STATION_CODE,
				LINE_CAT = this.LINE_CAT,
				TRACK_CODE = this.TRACK_CODE,
				OVERALL_LENGTH = this.OVERALL_LENGTH,
				START_MILE = this.START_MILE,
				END_MILE = this.END_MILE,
				LONGCHAIN_MARKER = this.LONGCHAIN_MARKER,
				GAUGE_TYPE = this.GAUGE_TYPE,
				CROSSING_TYPE = this.CROSSING_TYPE,
				CROSSING_MODEL = this.CROSSING_MODEL,
				LAY_LENGTH = this.LAY_LENGTH,
				LAY_ROOTS = this.LAY_ROOTS,
				MANUFACTURER = this.MANUFACTURER,
				MANUFACTURING_YEAR = this.MANUFACTURING_YEAR,
				LAY_YEAR = this.LAY_YEAR,
				CONFIGE_ROOTS = this.CONFIGE_ROOTS,
				FASTENER_TYPE = this.FASTENER_TYPE,
				FASTENER_MODEL = this.FASTENER_MODEL,
				MEMO = this.MEMO,
			};
		}
	} 
}
