//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class JOB_PLAN_DELINGHA_FILL_DETAIL
	{
		public JOB_PLAN_DELINGHA_FILL_DETAIL ToPOCO(bool isPOCO = true){
			return new JOB_PLAN_DELINGHA_FILL_DETAIL(){
				PLAN_ID = this.PLAN_ID,
				FILL_ID = this.FILL_ID,
				GQ_NAME = this.GQ_NAME,
				REGISTER_STATION = this.REGISTER_STATION,
				LINE_DIR = this.LINE_DIR,
				SECTION_STATION = this.SECTION_STATION,
				JOB_MILE = this.JOB_MILE,
				JOB_ITEM = this.JOB_ITEM,
				JOB_LEADER = this.JOB_LEADER,
				JOB_LEADER_PHONE = this.JOB_LEADER_PHONE,
				LIAISON_MAN = this.LIAISON_MAN,
				LIAISONMAN_PHONE = this.LIAISONMAN_PHONE,
				WORKER_NUM = this.WORKER_NUM,
				MIGRANT_NUM = this.MIGRANT_NUM,
				MAIN_MACHING = this.MAIN_MACHING,
				APPLY_DATE = this.APPLY_DATE,
				REPAIR_LEVEL = this.REPAIR_LEVEL,
				DUAN_LEADER = this.DUAN_LEADER,
				DEMO = this.DEMO,
				CRT_TIME = this.CRT_TIME,
				DEPCODE = this.DEPCODE,
				REJECT_NUM = this.REJECT_NUM,
				NOTES = this.NOTES,
				FILL_NUM = this.FILL_NUM,
				PLAN_DATE = this.PLAN_DATE,
				CONTROL_VIEW = this.CONTROL_VIEW,
				CONTROL_POSTIL = this.CONTROL_POSTIL,
				CONTROL_REJNUM = this.CONTROL_REJNUM,
			};
		}
	} 
}
