//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class JOB_PLAN_TRAIN
	{
		public JOB_PLAN_TRAIN ToPOCO(bool isPOCO = true){
			return new JOB_PLAN_TRAIN(){
				PKID = this.PKID,
				DEPT_CODE = this.DEPT_CODE,
				ADDTIME = this.ADDTIME,
				PHONE = this.PHONE,
				JOB_TYPE = this.JOB_TYPE,
				TRAINS = this.TRAINS,
				DRIVER = this.DRIVER,
				TRAIN_NUM = this.TRAIN_NUM,
				BEGIN_TIME = this.BEGIN_TIME,
				END_TIME = this.END_TIME,
				MONITOR_SIT = this.MONITOR_SIT,
				CHECK_MAN = this.CHECK_MAN,
				DEMO = this.DEMO,
				PHONENAME = this.PHONENAME,
				DEPT_NAME = this.DEPT_NAME,
				CJ_NAME = this.CJ_NAME,
				TRAIN_BEGIN = this.TRAIN_BEGIN,
				TRAIN_END = this.TRAIN_END,
				JOB_TIME = this.JOB_TIME,
				TRAIN_AREA = this.TRAIN_AREA,
				TRAIN_TYPE = this.TRAIN_TYPE,
			};
		}
	} 
}
