//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class JOB_PLAN_LOOKOUT
	{
		public JOB_PLAN_LOOKOUT ToPOCO(bool isPOCO = true){
			return new JOB_PLAN_LOOKOUT(){
				PKID = this.PKID,
				TYPE = this.TYPE,
				LINE_NAME = this.LINE_NAME,
				DIRECTION = this.DIRECTION,
				MILEAGE_BEGIN = this.MILEAGE_BEGIN,
				MILEAGE_END = this.MILEAGE_END,
				NOTE = this.NOTE,
				TOOLCAR_NAME = this.TOOLCAR_NAME,
			};
		}
	} 
}
