//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class LEDGER_MACHINE_TOOL
	{
		public LEDGER_MACHINE_TOOL ToPOCO(bool isPOCO = true){
			return new LEDGER_MACHINE_TOOL(){
				PKID = this.PKID,
				MACHINETOOL_NO = this.MACHINETOOL_NO,
				MACHINETOOL_NAME = this.MACHINETOOL_NAME,
				MACHINETOOL_TYPE = this.MACHINETOOL_TYPE,
				MANUFACTURE_UNIT = this.MANUFACTURE_UNIT,
				MANUFACTURE_DATE = this.MANUFACTURE_DATE,
				ORIGINAL_VALUE = this.ORIGINAL_VALUE,
				UNIT = this.UNIT,
				AMOUNT = this.AMOUNT,
				BEGINTIME = this.BEGINTIME,
				TECHNOLOGY_STATE = this.TECHNOLOGY_STATE,
				CJ_NAME = this.CJ_NAME,
				GQ_NAME = this.GQ_NAME,
				PRESERVER = this.PRESERVER,
				DEPT_CODE = this.DEPT_CODE,
				INPUT_DATE = this.INPUT_DATE,
				INPUT_USER = this.INPUT_USER,
				DISTRIBUTION_LOCATION = this.DISTRIBUTION_LOCATION,
				SETUP_TEAM = this.SETUP_TEAM,
				USE_DEPT = this.USE_DEPT,
				LARGE_CLASS = this.LARGE_CLASS,
				SHAPE_SIZE = this.SHAPE_SIZE,
			};
		}
	} 
}
