//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class LKJ_BROKEN_CHAIN
	{
		public LKJ_BROKEN_CHAIN ToPOCO(bool isPOCO = true){
			return new LKJ_BROKEN_CHAIN(){
				PKID = this.PKID,
				BUREAU_NAME = this.BUREAU_NAME,
				BUREAU_NUM = this.BUREAU_NUM,
				LINE_NAME = this.LINE_NAME,
				LINE_NUM = this.LINE_NUM,
				LINE_DIR = this.LINE_DIR,
				BROKEN_CHAIN_TYPE = this.BROKEN_CHAIN_TYPE,
				START_MILEAGE = this.START_MILEAGE,
				END_MILEAGE = this.END_MILEAGE,
				LONG_CHAIN_LENGTH = this.LONG_CHAIN_LENGTH,
				SHORT_CHAIN_LENGTH = this.SHORT_CHAIN_LENGTH,
				MODIFY_TAG = this.MODIFY_TAG,
				CREATE_TIME = this.CREATE_TIME,
				USER_NAME = this.USER_NAME,
				DEPT_CODE = this.DEPT_CODE,
			};
		}
	} 
}
