//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class LKJ_TRACK
	{
		public LKJ_TRACK ToPOCO(bool isPOCO = true){
			return new LKJ_TRACK(){
				PKID = this.PKID,
				BUREAU_NAME = this.BUREAU_NAME,
				BUREAU_NUM = this.BUREAU_NUM,
				LINE_NAME = this.LINE_NAME,
				LINE_NUM = this.LINE_NUM,
				LINE_DIR = this.LINE_DIR,
				STATION_NAME = this.STATION_NAME,
				STATION_NUM = this.STATION_NUM,
				TRACK_NUM = this.TRACK_NUM,
				EFFECTIVE_LENGTH = this.EFFECTIVE_LENGTH,
				ALL_LENGTH = this.ALL_LENGTH,
				CURVE_RADIUS = this.CURVE_RADIUS,
				DIRECTION = this.DIRECTION,
				SLOPE = this.SLOPE,
				MODIFY_TAG = this.MODIFY_TAG,
				REMARKS = this.REMARKS,
				CREATE_TIME = this.CREATE_TIME,
				USER_NAME = this.USER_NAME,
				DEPT_CODE = this.DEPT_CODE,
				SLOPE_LENGTH = this.SLOPE_LENGTH,
			};
		}
	} 
}
