//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class MATERIAL_INOUT_BILL
	{
		public MATERIAL_INOUT_BILL ToPOCO(bool isPOCO = true){
			return new MATERIAL_INOUT_BILL(){
				BILL_NUM = this.BILL_NUM,
				BILL_DATE = this.BILL_DATE,
				OPERATOR = this.OPERATOR,
				DEPT_CODE = this.DEPT_CODE,
				NOTE = this.NOTE,
				BILL_TYPE = this.BILL_TYPE,
			};
		}
	} 
}
