//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_OIL_RECORD_OIL
    {
        public string RECORDOIL_ID { get; set; }
        public string OP_ID { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public Nullable<System.DateTime> OILTIME_BEGIN { get; set; }
        public Nullable<decimal> OILMILE_BEGIN { get; set; }
        public Nullable<System.DateTime> OILTIME_END { get; set; }
        public Nullable<decimal> OILMILE_END { get; set; }
        public string POS_FLAG { get; set; }
        public string MACHINE_STATE { get; set; }
        public string RECORDOIL_MEMO { get; set; }
        public string OIL_MODEL { get; set; }
        public string LINE_NAME { get; set; }
        public string OP_NAME { get; set; }
        public string PHONE_NO { get; set; }
        public string DEVICE_NAME { get; set; }
        public string DEVICE_NO { get; set; }
    }
}
