//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_CURVE_RAILWEAR
    {
        public string PKID { get; set; }
        public decimal RAIL { get; set; }
        public string WEARTYPE { get; set; }
        public decimal MINSPEED { get; set; }
        public decimal MAXSPEED { get; set; }
        public Nullable<decimal> WEARVALUE { get; set; }
        public string TYPE { get; set; }
        public string C_MEMO { get; set; }
    }
}
