//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_GATE_GATEMNG_WARNING
    {
        public string WARNING_ID { get; set; }
        public string GATE_NO { get; set; }
        public string WARNING_INFO { get; set; }
        public Nullable<System.DateTime> WARNING_TIME { get; set; }
        public string WARNING_TYPE { get; set; }
        public string WARNING_LOG { get; set; }
        public Nullable<short> WARNING_FLAG { get; set; }
        public string WARNING_FROM { get; set; }
        public string CARD_NO { get; set; }
        public string GNAME { get; set; }
        public string GMOBILE { get; set; }
        public string GDEPTNAME { get; set; }
        public string AUTHHIS_ID { get; set; }
        public Nullable<System.DateTime> UNWARN_TIME { get; set; }
        public string UNWARN_USER { get; set; }
        public string UNWARN_REASON { get; set; }
        public string AUTHOPT_SECTION { get; set; }
    }
}
