//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_SNOW_BDATA_WARNSTANDARD
    {
        public decimal WARN_LEVEL { get; set; }
        public string WARN_LEVELDESC { get; set; }
        public string WARN_STANDARDDESC { get; set; }
        public Nullable<decimal> WARN_STANDARDLOW { get; set; }
        public Nullable<decimal> WARN_STANDARDHIGH { get; set; }
        public string WARN_CONTENT { get; set; }
        public string WARN_MSG { get; set; }
        public string REMARK_BGCOLOR { get; set; }
        public string REMARK_FONTCOLOR { get; set; }
    }
}
