//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_T_ASS_PLAN_CONSTRUCTION
    {
        public string PLAN_ID { get; set; }
        public string AREACODEPHONE { get; set; }
        public string PLAN_LEVEL { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public string ITEM { get; set; }
        public string LOCATION { get; set; }
        public string WORKDATE { get; set; }
        public string BLOCKTIME { get; set; }
        public string CONTENT { get; set; }
        public string SPEEDCHANGE { get; set; }
        public string EQUMWNTCHANGE { get; set; }
        public string TRANSIT { get; set; }
        public string WORKUNIT { get; set; }
        public string WORKWITHUNIT { get; set; }
        public string TURNNUM { get; set; }
        public string IMPDEP { get; set; }
    }
}
