//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_VEHICLELOC_BDATA_LOCOMOTIVE
    {
        public decimal LOCOMOTIVE_NO { get; set; }
        public string LOCOMOTIVE_TYPE { get; set; }
        public string DEPT_CODE { get; set; }
        public string JWD_NAME { get; set; }
        public string JWDDW_NAME { get; set; }
        public string PHONE_NO { get; set; }
        public string LOCOMOTIVE_FLAG { get; set; }
        public string LOCOMOTIVE_MEMO { get; set; }
        public string LOCOMOTIVE_NUMBER { get; set; }
    }
}
