//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_CURVE_PSN
    {
        public string PKID { get; set; }
        public string GQEMPNAME { get; set; }
        public string GQEMPPOST { get; set; }
        public Nullable<System.DateTime> GQEMPCHECKDATE { get; set; }
        public string CJEMPNAME { get; set; }
        public string CJEMPPOST { get; set; }
        public Nullable<System.DateTime> CJEMPCHECKDATE { get; set; }
        public string GWDEMPNAME { get; set; }
        public string GWDEMPPOST { get; set; }
        public Nullable<System.DateTime> GWDEMPCHECKDATE { get; set; }
        public Nullable<System.DateTime> T_CRT_TM { get; set; }
        public string C_CRT_NAME { get; set; }
        public Nullable<decimal> N_ORDER { get; set; }
        public string C_MEMO { get; set; }
    }
}
