//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_HIK_PIC_INFO
    {
        public string PKID { get; set; }
        public string CAMERA_ID { get; set; }
        public string CAMERA_NAME { get; set; }
        public string SNAP_PIC_URL { get; set; }
        public string DEVICE_CODE { get; set; }
        public string DEVICE_NAME { get; set; }
        public string ORIGINAL_CREATE_TIME { get; set; }
        public string NEW_PIC_URL { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
    }
}
