//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_T_ASS_SECURITY_OFFER
    {
        public string PKID { get; set; }
        public string EMP_PKID { get; set; }
        public Nullable<System.DateTime> SECURITY_DATE { get; set; }
        public string ASS_RESULT { get; set; }
        public string ASS_SATUATION { get; set; }
        public string DEMO { get; set; }
    }
}
