//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_LEDGER_LEVELCROSS_PIPE_LINE
    {
        public string PKID { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_NAME { get; set; }
        public string LINEDIR_CODE { get; set; }
        public string LINEDIR_NAME { get; set; }
        public string OPERATE_STATU { get; set; }
        public string LEVELCROSS_KM { get; set; }
        public string PAVING_MATERIAL { get; set; }
        public Nullable<decimal> PAVEMENT_WIDTH { get; set; }
        public string RAIL_TYPE { get; set; }
        public string ALARM_DEVICE { get; set; }
        public string VIDEO_INSTALLATE { get; set; }
        public string CROSSE_NATURE { get; set; }
        public string PROPERTY_UNIT { get; set; }
        public string ROADJOINT_CONTROL { get; set; }
        public Nullable<decimal> ACROSS_TRACKS { get; set; }
        public string ROAD_TYPE { get; set; }
        public string ROAD_NAME { get; set; }
        public string IF_PASS { get; set; }
        public string ROAD_FLAG { get; set; }
        public string RETAIN_FENCES { get; set; }
        public string DOOR_FLAG { get; set; }
        public string BOUNDARY_FRAME { get; set; }
        public string DEMO { get; set; }
        public string DEPT_CODE { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string INPUT_USER { get; set; }
    }
}
