//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_T_LKJ_S2_HIS
    {
        public string ID { get; set; }
        public Nullable<decimal> FLOWID { get; set; }
        public Nullable<decimal> WORKID { get; set; }
        public string GID { get; set; }
        public string FLAG { get; set; }
        public string RWBNAME { get; set; }
        public string RWBCODE { get; set; }
        public string LINENAME { get; set; }
        public string LINECODE { get; set; }
        public string LINEDIRECTION { get; set; }
        public string STATIONNAME { get; set; }
        public string STATIONCODE { get; set; }
        public string TRACKCOUNT { get; set; }
        public string KMCENTER { get; set; }
        public string MARK { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> LASTDATE { get; set; }
        public string BACKDESC { get; set; }
        public string MARKID { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string USER_NAME { get; set; }
        public string DEPT_CODE { get; set; }
    }
}
