//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_HRAIL_BALLAST
    {
        public string BALLAST_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string CJ_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public string RUN_STATUS { get; set; }
        public string BALLAST_FLAG { get; set; }
        public string STATION_NAME { get; set; }
        public string STATION_CODE { get; set; }
        public string LINE_CAT { get; set; }
        public string LINE_TYPE { get; set; }
        public string TRACK_CODE { get; set; }
        public Nullable<int> OVERALL_LENGTH { get; set; }
        public Nullable<decimal> START_MILE { get; set; }
        public Nullable<decimal> END_MILE { get; set; }
        public string LONGCHAIN_MARKER { get; set; }
        public string BALLAST_TYPE { get; set; }
        public string BALLAST_MATERAIL { get; set; }
        public string GAUGE_TYPE { get; set; }
        public string BALLAST_LEVEL { get; set; }
        public Nullable<int> BALLAST_TOPWIDTH { get; set; }
        public Nullable<int> PILLOW_THICKNESS { get; set; }
        public string CUSSION_MATERAIL { get; set; }
        public Nullable<int> CUSSION_THICKNESS { get; set; }
        public Nullable<decimal> SIDE_SLOPE { get; set; }
        public string DIRTY_PROGRM { get; set; }
        public string SCREEN_YEAR { get; set; }
        public string MEMO { get; set; }
    }
}
