//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_HRAIL_UNIT_VAL
    {
        public string UNITVAL_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string CJ_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public string LINE_CAT { get; set; }
        public Nullable<decimal> START_MILE { get; set; }
        public Nullable<decimal> END_MILE { get; set; }
        public string STATION_CODE { get; set; }
        public string TURNOUT_CODE { get; set; }
        public string TRACK_CODE { get; set; }
        public string UNIT_NO { get; set; }
        public string UNIT_CAT { get; set; }
        public Nullable<decimal> STATIC_SCORE { get; set; }
        public Nullable<decimal> DYNAMIC_SCORE { get; set; }
        public string WEIGHT { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public Nullable<decimal> TQI_VALUE { get; set; }
        public Nullable<decimal> TQI_SCORE { get; set; }
        public string EVALUE_GRADE { get; set; }
        public Nullable<System.DateTime> EVALUE_DATE { get; set; }
        public string MEMO { get; set; }
        public Nullable<System.DateTime> CRT_TM { get; set; }
        public string CRT_NAME { get; set; }
    }
}
