//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_BRIDGE_STATE_REPORT
    {
        public string REPORT_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string CJ_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string EQU_CAT { get; set; }
        public string REPORT_DATE { get; set; }
        public int EQU_TOTAL { get; set; }
        public int LEV_OVER_B { get; set; }
        public int LEV_AA { get; set; }
        public int LEV_A1 { get; set; }
        public Nullable<int> LEV_C { get; set; }
        public string MEMO { get; set; }
        public int LEV_B { get; set; }
    }
}
