//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_T_ASS_TUNNEL
    {
        public string PKID { get; set; }
        public string GWD_CODE { get; set; }
        public string DEP_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_NAME { get; set; }
        public string ASSIST_LINE_CODE { get; set; }
        public string ASSIST_LINE_NAME { get; set; }
        public string TUNNEL_CODE { get; set; }
        public string TUNNEL_NAME { get; set; }
        public string LINE_DIR { get; set; }
        public string OPERATION_STATUS { get; set; }
        public string GAUGE { get; set; }
        public decimal CENTER_MILEAGE { get; set; }
        public string LONGCHAIN_MARKER { get; set; }
        public Nullable<decimal> TUNNEL_LENGTH { get; set; }
        public Nullable<decimal> START_MILEAGE { get; set; }
        public Nullable<decimal> END_MILEAGE { get; set; }
    }
}
