//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_T_ASS_PLAN_UNIT_PRO_STAT
    {
        public string PKID { get; set; }
        public string PLAN_ID { get; set; }
        public string FLOWID { get; set; }
        public string LOC_PKID { get; set; }
        public Nullable<short> FLAG { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public string UNIT_NUM { get; set; }
        public Nullable<decimal> UNIT_START_MILE { get; set; }
        public Nullable<decimal> UNIT_END_MILE { get; set; }
        public string STATION_CODE { get; set; }
        public string TRACK_CODE { get; set; }
        public string TURNOUT_CODE { get; set; }
        public Nullable<short> TRACK_PRO_NUM { get; set; }
        public Nullable<decimal> TRACK_PRO_PEAK { get; set; }
        public string TRACK_PRO_PLACE { get; set; }
        public Nullable<short> HILOW_PRO_NUM { get; set; }
        public Nullable<decimal> HILOW_PRO_PEAK { get; set; }
        public string HILOW_PRO_PLACE { get; set; }
        public Nullable<short> GAUGE_PRO_NUM { get; set; }
        public Nullable<decimal> GAUGE_PRO_PEAK { get; set; }
        public string GAUGE_PRO_PLACE { get; set; }
        public Nullable<short> HORIAONTAL_PRO_NUM { get; set; }
        public Nullable<decimal> HORIAONTAL_PRO_PEAK { get; set; }
        public string HORIAONTAL_PRO_PLACE { get; set; }
        public Nullable<short> TWIST_PRO_NUM { get; set; }
        public Nullable<decimal> TWIST_PRO_PEAK { get; set; }
        public string TWIST_PRO_PLACE { get; set; }
        public Nullable<short> OTHER_PRO_NUM { get; set; }
        public Nullable<decimal> OTHER_PRO_PEAK { get; set; }
        public string OTHER_PRO_PLACE { get; set; }
        public string MEMO { get; set; }
        public Nullable<System.DateTime> CRT_TM { get; set; }
    }
}
