//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_RAIN_FLOOD_LABOUR
    {
        public string FLOODLABOUR_ID { get; set; }
        public string LABOUR_MAJOR { get; set; }
        public string PLACE { get; set; }
        public string CONTACTS { get; set; }
        public string PHONE { get; set; }
        public Nullable<short> WORKER_NUM { get; set; }
        public Nullable<short> MAGRANT_NUM { get; set; }
        public string BIG_MECHANICS { get; set; }
        public string DEMO { get; set; }
        public string GWD_CODE { get; set; }
        public string DEP_CODE { get; set; }
        public string GQ_CODE { get; set; }
    }
}
