//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_T_ASS_REPEAT_PROBLEM
    {
        public string PKID { get; set; }
        public string C_DEP_CODE { get; set; }
        public string C_LINE_CODE { get; set; }
        public string C_LINE_DIR { get; set; }
        public string C_STATION_CODE { get; set; }
        public string C_TRACK_CODE { get; set; }
        public string C_TURNOUT_CODE { get; set; }
        public string C_PRO_ITEM { get; set; }
        public string C_PRO_CODE { get; set; }
        public Nullable<decimal> N_REPEAT_NUM { get; set; }
        public string C_MEMO { get; set; }
        public Nullable<decimal> N_MILE_RANGE { get; set; }
        public string C_CHECK_DEV { get; set; }
        public Nullable<decimal> N_START_MILE { get; set; }
        public Nullable<decimal> N_END_MILE { get; set; }
        public string C_USER { get; set; }
    }
}
