//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_ASSET_BASE_SUPPLIER
    {
        public string SUPPLIER_CODE { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string SUPPLIER_SHORTNAME { get; set; }
        public string SUPPLIER_TYPE { get; set; }
        public string ADDR { get; set; }
        public string ZIP_CODE { get; set; }
        public string CONTACT { get; set; }
        public string TELPHONE { get; set; }
        public string FAX { get; set; }
        public short IS_ENABLE { get; set; }
        public string MEMO { get; set; }
        public string DEPT_CODE { get; set; }
    }
}
