//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_FLOW_JOB
    {
        public short FLOW_ID { get; set; }
        public string JOB_ID { get; set; }
        public string DEPT_CODE { get; set; }
        public System.DateTime JOB_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string EDITOR { get; set; }
        public short EDIT_STATUS { get; set; }
        public Nullable<System.DateTime> SUBMITTIME { get; set; }
        public short STEPNO { get; set; }
        public short STEP_STATUS { get; set; }
        public short NEXT_STEPNO { get; set; }
        public short ISENDSTEP { get; set; }
        public short ISFINISHED { get; set; }
        public string CJ_CODE { get; set; }
        public string CJ_AUDIT { get; set; }
        public string CJ_LEADER { get; set; }
        public Nullable<System.DateTime> CJ_AUDITTIME { get; set; }
        public string GW_CODE { get; set; }
        public string GWD_AUDIT { get; set; }
        public string GWD_LEADER { get; set; }
        public Nullable<System.DateTime> GWD_AUDITTIME { get; set; }
        public string GWC_AUDIT { get; set; }
        public string GWC_LEADER { get; set; }
        public Nullable<System.DateTime> GWC_AUDITTIME { get; set; }
        public short ISREJECT { get; set; }
        public string REJECT_COMMENT { get; set; }
        public string MEMO { get; set; }
    }
}
