//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_MATERIAL_INOUT_BILL_DETAIL
    {
        public string PKID { get; set; }
        public string BILL_NUM { get; set; }
        public string TYPE { get; set; }
        public string NAME { get; set; }
        public string MODEL { get; set; }
        public string MATERIAL_NO { get; set; }
        public string LABEL { get; set; }
        public Nullable<decimal> SINGLE_NUM { get; set; }
        public string SINGLE_UNIT { get; set; }
        public Nullable<decimal> NUM { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> SUB_TOTAL { get; set; }
        public string NOTE { get; set; }
        public string DEPID { get; set; }
    }
}
