//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_RESCUE_LINE_PHOTO
    {
        public string PHOTO_ID { get; set; }
        public string RESCUE_ID { get; set; }
        public string PHOTOURL { get; set; }
        public string SMALLURL { get; set; }
    }
}
