//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_HEART_DG_WAVE
    {
        public string LINE { get; set; }
        public string DIRE { get; set; }
        public string POS { get; set; }
        public string GB { get; set; }
        public System.DateTime DT { get; set; }
        public Nullable<decimal> VAL { get; set; }
        public string QJID { get; set; }
    }
}
