//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_WIND_GRADING
    {
        public decimal 等级 { get; set; }
        public string 地面物象征 { get; set; }
        public decimal 风速低 { get; set; }
        public decimal 风速高 { get; set; }
    }
}
