//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_SYS_STATIONMEMBER_NO
    {
        public string NO_ID { get; set; }
        public string DEPT_CODE { get; set; }
        public string CJ_NAME { get; set; }
        public string GQ_NAME { get; set; }
        public string MEMBER_NAME { get; set; }
        public string STATION_NAME { get; set; }
        public string TEL_NO { get; set; }
        public string MEMO { get; set; }
    }
}
