//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_TASK_SLIGHT_OUTLINE
    {
        public string PKID { get; set; }
        public string DEPTID { get; set; }
        public string IS_SUBMIT { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_USER { get; set; }
        public string GWD_CODE { get; set; }
        public string DEPT_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string YEAR { get; set; }
        public string MONTH { get; set; }
        public string DAILY { get; set; }
        public string KILOMILE { get; set; }
        public string LINENO { get; set; }
        public string RAILNO { get; set; }
        public string RAILLR { get; set; }
        public string RAILTYPE { get; set; }
        public Nullable<System.DateTime> FINDTIME { get; set; }
        public string FINDNAME { get; set; }
        public string MANUFACTURE { get; set; }
        public Nullable<System.DateTime> PRODUCTION { get; set; }
        public string RAILLENGTH { get; set; }
        public string INJURYSITUATION { get; set; }
        public string WOUNDEDFLAG { get; set; }
        public string CONNECTONE { get; set; }
        public string TAKESTEPS { get; set; }
        public string PHONE { get; set; }
        public string REMARK { get; set; }
    }
}
