//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_T_ASS_PARAREPORT_TEMP
    {
        public string PKID { get; set; }
        public string C_DEP_CODE { get; set; }
        public string C_DEP_NAME { get; set; }
        public string C_CODE { get; set; }
        public string C_NAME { get; set; }
        public string C_TYPE { get; set; }
        public Nullable<decimal> C_CHECK_COUNT { get; set; }
        public Nullable<decimal> C_LEVEL_GOOD { get; set; }
        public Nullable<decimal> C_LEVEL_KIND { get; set; }
        public Nullable<decimal> C_LEVEL_POOR { get; set; }
        public Nullable<decimal> C_JHCC_SCORE { get; set; }
        public Nullable<decimal> C_GG_SCORE { get; set; }
        public Nullable<decimal> C_GZ_SCORE { get; set; }
        public Nullable<decimal> C_PX_SCORE { get; set; }
        public Nullable<decimal> C_DC_SCORE { get; set; }
        public Nullable<decimal> C_OTHER_SCORE { get; set; }
        public Nullable<decimal> C_CUR_GOOD { get; set; }
        public Nullable<decimal> C_CUR_KIND { get; set; }
        public Nullable<decimal> C_CUR_POOR { get; set; }
        public string C_USER_ID { get; set; }
        public Nullable<System.DateTime> C_DATE { get; set; }
        public string C_FLAG { get; set; }
        public Nullable<decimal> DC_CHECK_NUM { get; set; }
        public Nullable<decimal> DC_LEVEL_GOOD { get; set; }
        public Nullable<decimal> DC_LEVEL_KIND { get; set; }
        public Nullable<decimal> DC_LEVEL_POOR { get; set; }
        public Nullable<decimal> DC_JHCC_SCORE { get; set; }
        public Nullable<decimal> DC_GG_SCORE { get; set; }
        public Nullable<decimal> DC_GZ_SCORE { get; set; }
        public Nullable<decimal> DC_PX_SCORE { get; set; }
        public Nullable<decimal> DC_DC_SCORE { get; set; }
        public Nullable<decimal> DC_OTHER_SCORE { get; set; }
        public string C_MEMO { get; set; }
    }
}
