//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_BRIDGE_STATE_PRO
    {
        public string PRO_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string CJ_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public System.DateTime CHECK_DATE { get; set; }
        public string CHECK_DEP_CODE { get; set; }
        public string CHECK_DEP_NAME { get; set; }
        public string CHECK_MAN { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public string EQU_CAT { get; set; }
        public string RUN_STATUS { get; set; }
        public decimal CENTER_MILE { get; set; }
        public string EQU_CODE { get; set; }
        public string EQU_NAME { get; set; }
        public string HOLESPAN_STYLE { get; set; }
        public string ITEM_CAT { get; set; }
        public string ITEM_SUBCAT { get; set; }
        public string ITEM_TYPE { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public string ITEM_UNIT { get; set; }
        public short ITEM_LEVEL { get; set; }
        public string HOLE_NO { get; set; }
        public short PRO_NUM { get; set; }
        public string PRO_DESC { get; set; }
        public string EVALUATE_DEPT { get; set; }
        public string EVALUATE_MAN { get; set; }
        public Nullable<System.DateTime> CLEAR_PRO_DATE { get; set; }
        public string CLEAR_PRO_MAN { get; set; }
        public string CLEAR_PRO_TYPE { get; set; }
        public string MEMO { get; set; }
        public Nullable<short> PRO_STATUS { get; set; }
        public Nullable<System.DateTime> CRT_TM { get; set; }
        public string CRT_NAME { get; set; }
        public string FLAG { get; set; }
    }
}
