//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_RULE_PROBLEM
    {
        public string PKID { get; set; }
        public string DEPT_CODE { get; set; }
        public string INSPECTOR { get; set; }
        public string INSPECT_DEPT_CODE { get; set; }
        public string INSPECT_POST { get; set; }
        public Nullable<System.DateTime> INSPECT_TIME { get; set; }
        public string PROBLEM { get; set; }
        public string PROFESSION_CAT { get; set; }
        public string PROBLEM_NATURE { get; set; }
        public string PROBLEM_LEVEL { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public string RECTIFICATION_DEADLINE { get; set; }
        public string RECTIFICATION_STATUS { get; set; }
        public string RECTIFICATION_DESC { get; set; }
        public string BULLETIN_NO { get; set; }
        public string CHIEF_INSTR { get; set; }
        public string DIRECTOR_INSTR { get; set; }
        public string ORTHER { get; set; }
        public string ANALYSIS_FLAG { get; set; }
        public string DOC_FLAG { get; set; }
        public string MEMO { get; set; }
        public string CREATOR { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string JOB { get; set; }
        public string INSPECT_OFFICE { get; set; }
        public string CREATOR_OFFICE { get; set; }
    }
}
