//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_HRAIL_PARA_PROITEM
    {
        public string CHECK_TYPE { get; set; }
        public string ITEM_CAT { get; set; }
        public string ITEM_SUBCAT { get; set; }
        public string ITEM_TYPE { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public string ITEM_UNIT { get; set; }
        public Nullable<short> ITEM_SCORE { get; set; }
        public short FLAG { get; set; }
        public string MEMO { get; set; }
    }
}
