//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_T_CHK_DIC
    {
        public string PKID { get; set; }
        public string DIC_ID { get; set; }
        public string CHECK_TYPE { get; set; }
        public string TYPE_FLAG { get; set; }
        public string POS_FLAG { get; set; }
        public string PAR_ID { get; set; }
        public string DIC_DESC { get; set; }
        public string DIC_SAMPDESC { get; set; }
        public string DIS_UNIT { get; set; }
        public string MINUS_STANDARD { get; set; }
        public string DIS_LEVEL { get; set; }
        public string DIS_TYPE { get; set; }
    }
}
