//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_TASK_SLIGHT_FROG
    {
        public string PKID { get; set; }
        public string DEPTID { get; set; }
        public string IS_SUBMIT { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_USER { get; set; }
        public string GWD_CODE { get; set; }
        public string DEPT_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string YEAR { get; set; }
        public string MONTH { get; set; }
        public string DAILY { get; set; }
        public string LINE_CAT { get; set; }
        public Nullable<System.DateTime> FOUND_DATE { get; set; }
        public string BREAK_REASON { get; set; }
        public string BREAK_FLAG { get; set; }
        public string COME_MEMBER { get; set; }
        public string STOVE_NO { get; set; }
        public string STATION { get; set; }
        public string TURNOUT_CODE { get; set; }
        public string FROG_TYPE { get; set; }
        public string FOUND_MEMBER { get; set; }
        public string FOUND_TIME { get; set; }
        public string MADE_FACT { get; set; }
        public Nullable<System.DateTime> MADE_YEAR { get; set; }
        public string MEMO { get; set; }
        public string REPLACE_FLAG { get; set; }
        public Nullable<System.DateTime> REPLACE_DATE { get; set; }
    }
}
