//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_GATE_BDATA_CARD
    {
        public string CARD_NO { get; set; }
        public string MEMBER_ID { get; set; }
        public string DEPT_CODE { get; set; }
        public string CARD_STATE { get; set; }
        public Nullable<System.DateTime> CARD_INDATE { get; set; }
        public Nullable<System.DateTime> CARD_DELDATE { get; set; }
        public string CARD_NOTE { get; set; }
        public string CARD_TYPE { get; set; }
        public string TOOL_ID { get; set; }
        public string CARD_SECTION { get; set; }
    }
}
