//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_TASK_SLIGHT_OUTLINE_FILE
    {
        public string TASK_OUT_FILE_ID { get; set; }
        public string TASK_OUT_PKID { get; set; }
        public string FILE_CAT { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_DESC { get; set; }
        public System.DateTime CRT_TIME { get; set; }
    }
}
