//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_DR_IDX_DOC_CONTENT_I
    {
        public string TOKEN_TEXT { get; set; }
        public int TOKEN_TYPE { get; set; }
        public int TOKEN_FIRST { get; set; }
        public int TOKEN_LAST { get; set; }
        public int TOKEN_COUNT { get; set; }
        public byte[] TOKEN_INFO { get; set; }
    }
}
