//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_TURNOUT_HISTORY
    {
        public string HISTORY_ID { get; set; }
        public string TURNOUT_ID { get; set; }
        public string ORG_CODE { get; set; }
        public string LINE_NO { get; set; }
        public string DIRECTION { get; set; }
        public string STATION { get; set; }
        public string STATION_CODE { get; set; }
        public string LINE_TYPE { get; set; }
        public string TURNOUT_NO { get; set; }
        public string TURNOUT_TYPE { get; set; }
        public string SKEEOERS_TYPE { get; set; }
        public string TURNOUT_CATE { get; set; }
        public string FROG_NO { get; set; }
        public string FROG_STRUCTURE { get; set; }
        public Nullable<long> FROG_LENGTH { get; set; }
        public string BLADE_TYPE { get; set; }
        public Nullable<int> BLADE_LEFTLEN { get; set; }
        public Nullable<int> BLADE_RIGHTLEN { get; set; }
        public Nullable<long> TURNOUT_LENGTH { get; set; }
        public string SWITCH_TYPE { get; set; }
        public Nullable<short> BRANCH_NUM { get; set; }
        public Nullable<short> GENERAL_NUM { get; set; }
        public Nullable<short> CONCRETE_NUM { get; set; }
        public Nullable<short> H_SPEED { get; set; }
        public Nullable<short> V_SPEED { get; set; }
        public string DESIGN_DRAWNO { get; set; }
        public string TURNOUT_NOTE { get; set; }
        public string TURNOUT_FAC { get; set; }
        public string MEASURER { get; set; }
        public string MEASURER_DUTY { get; set; }
        public string LAYER { get; set; }
        public string LAYER_DUTY { get; set; }
        public Nullable<System.DateTime> LAYER_TIME { get; set; }
        public string ONLINER { get; set; }
        public string ONLINE_DUTY { get; set; }
        public Nullable<System.DateTime> ONLINE_TIME { get; set; }
        public string CHECKER { get; set; }
        public string CHECKER_DUTY { get; set; }
        public string SKEEOERS_FACTORY { get; set; }
        public Nullable<System.DateTime> SKEEOERS_ONLINE { get; set; }
        public string SKEEOERS_DAMAGE { get; set; }
        public Nullable<System.DateTime> SKEEOERS_REPLACETIME { get; set; }
        public Nullable<System.DateTime> STOCK_ONLINE { get; set; }
        public Nullable<System.DateTime> STOCK_REPLACETIME { get; set; }
        public Nullable<System.DateTime> BLADE_ONLINE { get; set; }
        public string BLADE_DIRECT { get; set; }
        public string BLADE_DRAWNO { get; set; }
        public Nullable<int> BLADE_WEIGHT { get; set; }
        public Nullable<System.DateTime> BLADE_REPLACETIME { get; set; }
        public string FROG_FACTORY { get; set; }
        public Nullable<System.DateTime> FROG_ONLINE { get; set; }
        public string FROG_DRAWNO { get; set; }
        public Nullable<int> FROG_WEIGHT { get; set; }
        public Nullable<System.DateTime> FROG_REPLACETIME { get; set; }
        public Nullable<int> ANNUAL_WEIGHT { get; set; }
        public Nullable<int> TOTAL_WEIGHT { get; set; }
        public string REPAIR_NOTE { get; set; }
        public Nullable<System.DateTime> HISTORY_DATE { get; set; }
        public Nullable<short> REPAIR_FLAG { get; set; }
        public string SLEEPER_PICURL { get; set; }
        public string RAIL_PICURL { get; set; }
        public string C_DEP_CODE { get; set; }
        public string LINE_NUM { get; set; }
    }
}
