//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.POCOModel
{
      
    using System;
    using System.Collections.Generic;
    
    public partial class POCO_GATE_BDATA_TOOL
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string TYPE { get; set; }
        public string MFRS { get; set; }
        public string DEPT_CODE { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string REMARK { get; set; }
        public string TOOLID { get; set; }
        public string MARKER { get; set; }
        public Nullable<System.DateTime> MADEDATE { get; set; }
        public Nullable<System.DateTime> USEDATE { get; set; }
    }
}
