//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class PROTECTEDNET_RECORD_CHECK
	{
		public PROTECTEDNET_RECORD_CHECK ToPOCO(bool isPOCO = true){
			return new PROTECTEDNET_RECORD_CHECK(){
				PKID = this.PKID,
				PHONE_NO = this.PHONE_NO,
				CHECK_TIME = this.CHECK_TIME,
			};
		}
	} 
}
