//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class RAIL_SOUNDWAVE_LOG
	{
		public RAIL_SOUNDWAVE_LOG ToPOCO(bool isPOCO = true){
			return new RAIL_SOUNDWAVE_LOG(){
				PKID = this.PKID,
				手机号 = this.手机号,
				时间 = this.时间,
				左右轨 = this.左右轨,
				里程 = this.里程,
				行别 = this.行别,
				左轨高频 = this.左轨高频,
				左轨低频 = this.左轨低频,
				右轨高频 = this.右轨高频,
				右轨低频 = this.右轨低频,
				电源 = this.电源,
				左轨高频电压 = this.左轨高频电压,
				左轨低频电压 = this.左轨低频电压,
				右轨高频电压 = this.右轨高频电压,
				右轨低频电压 = this.右轨低频电压,
				LOG = this.LOG,
			};
		}
	} 
}
