//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class RAIL_COMM
	{
		public RAIL_COMM ToPOCO(bool isPOCO = true){
			return new RAIL_COMM(){
				ID = this.ID,
				HOST_NO = this.HOST_NO,
				FREQUENCY = this.FREQUENCY,
				SEND_PHONE = this.SEND_PHONE,
				UPLOAD_TIME = this.UPLOAD_TIME,
				SEND_TIME = this.SEND_TIME,
			};
		}
	} 
}
