//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class RAIL_RECORD_POINT
	{
		public RAIL_RECORD_POINT ToPOCO(bool isPOCO = true){
			return new RAIL_RECORD_POINT(){
				POINTRECORD_ID = this.POINTRECORD_ID,
				HOST_NO = this.HOST_NO,
				RECORD_TIME = this.RECORD_TIME,
				RECORD_ORDER = this.RECORD_ORDER,
				POINT_POWER = this.POINT_POWER,
				POINTRECORD_LOG = this.POINTRECORD_LOG,
				STANDARD_POWER = this.STANDARD_POWER,
				POINT_NO = this.POINT_NO,
				STATUS_FLAG = this.STATUS_FLAG,
				WARN_FLAG = this.WARN_FLAG,
			};
		}
	} 
}
