//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class RAIL_RECORD_SAMPWARN
	{
		public RAIL_RECORD_SAMPWARN ToPOCO(bool isPOCO = true){
			return new RAIL_RECORD_SAMPWARN(){
				SAMPWARNRECORD_ID = this.SAMPWARNRECORD_ID,
				HOST_NO = this.HOST_NO,
				RECORD_TIME = this.RECORD_TIME,
				SAMPWARN_TYPE = this.SAMPWARN_TYPE,
				POWER = this.POWER,
				SAMPWARNRECORD_LOG = this.SAMPWARNRECORD_LOG,
				SAMPWARN_FLAG = this.SAMPWARN_FLAG,
			};
		}
	} 
}
