//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class RAIL_BDATA_SENDPHONENO
	{
		public RAIL_BDATA_SENDPHONENO ToPOCO(bool isPOCO = true){
			return new RAIL_BDATA_SENDPHONENO(){
				SENDPHONENO_NO = this.SENDPHONENO_NO,
				MOBILE = this.MOBILE,
				SEND_ROLE = this.SEND_ROLE,
				UPDATE_USER = this.UPDATE_USER,
				UPDATE_DATE = this.UPDATE_DATE,
				SENDPHONENO_NOTE = this.SENDPHONENO_NOTE,
				SECTION_ID = this.SECTION_ID,
				SEND_NAME = this.SEND_NAME,
				BOUNDARY_START = this.BOUNDARY_START,
				BOUNDARY_END = this.BOUNDARY_END,
				LINE_NAME = this.LINE_NAME,
				LINE_DIR = this.LINE_DIR,
				IS_ENABLE = this.IS_ENABLE,
			};
		}
	} 
}
