//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class RAIL_RECORD_HOST
	{
		public RAIL_RECORD_HOST ToPOCO(bool isPOCO = true){
			return new RAIL_RECORD_HOST(){
				HOSTRECORD_ID = this.HOSTRECORD_ID,
				HOST_NO = this.HOST_NO,
				RECORD_TIME = this.RECORD_TIME,
				POWERBOARD_FLAG = this.POWERBOARD_FLAG,
				INTERFACEBOARD_FLAG = this.INTERFACEBOARD_FLAG,
				POINT_NUM = this.POINT_NUM,
				POWER = this.POWER,
				HOSTRECORD_LOG = this.HOSTRECORD_LOG,
				POWER_TYPE = this.POWER_TYPE,
				POWER_AC = this.POWER_AC,
			};
		}
	} 
}
