//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class RAIN_FLOOD_STOCK_PHOTO
	{
		public RAIN_FLOOD_STOCK_PHOTO ToPOCO(bool isPOCO = true){
			return new RAIN_FLOOD_STOCK_PHOTO(){
				PHOTO_ID = this.PHOTO_ID,
				FLOODSTOCK_ID = this.FLOODSTOCK_ID,
				PHOTOURL = this.PHOTOURL,
				SMALLURL = this.SMALLURL,
				DEMO = this.DEMO,
			};
		}
	} 
}
