//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class ROADBED_ITEM_PARA
	{
		public ROADBED_ITEM_PARA ToPOCO(bool isPOCO = true){
			return new ROADBED_ITEM_PARA(){
				ITEM_TYPE = this.ITEM_TYPE,
				ITEM_CODE = this.ITEM_CODE,
				ITEM_NAME = this.ITEM_NAME,
				ITEM_UNIT = this.ITEM_UNIT,
				ITEM_SCORE = this.ITEM_SCORE,
				SCORE_A = this.SCORE_A,
				SCORE_B = this.SCORE_B,
				SCORE_C = this.SCORE_C,
				FLAG = this.FLAG,
				MEMO = this.MEMO,
			};
		}
	} 
}
