//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class SCRIPT_SECTION_BRIDGETUNNEL
	{
		public SCRIPT_SECTION_BRIDGETUNNEL ToPOCO(bool isPOCO = true){
			return new SCRIPT_SECTION_BRIDGETUNNEL(){
				PKID = this.PKID,
				LINE_NAME = this.LINE_NAME,
				LINE_DIR = this.LINE_DIR,
				MILEAGE = this.MILEAGE,
				DEPT_CODE = this.DEPT_CODE,
				COMMENTS = this.COMMENTS,
				TYPE = this.TYPE,
				LENGTH = this.LENGTH,
				MARSLONGITUDE = this.MARSLONGITUDE,
				MARSLATITUDE = this.MARSLATITUDE,
			};
		}
	} 
}
