//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class SCRIPTS_STATION_CHECK
	{
		public SCRIPTS_STATION_CHECK ToPOCO(bool isPOCO = true){
			return new SCRIPTS_STATION_CHECK(){
				PKID = this.PKID,
				DEPT_CODE = this.DEPT_CODE,
				IMPORT_TIME = this.IMPORT_TIME,
				IMPORT_USER = this.IMPORT_USER,
				EXCEL_DATE = this.EXCEL_DATE,
				EXCEL_DATEIN = this.EXCEL_DATEIN,
				CHE_JIAN = this.CHE_JIAN,
				BAN_ZU = this.BAN_ZU,
				CONTENT_LEVEL = this.CONTENT_LEVEL,
				WORK_PLACE = this.WORK_PLACE,
				WORK_LEADER = this.WORK_LEADER,
				CHEJIAN_MONITOR = this.CHEJIAN_MONITOR,
				STATION_MONITOR = this.STATION_MONITOR,
				NOTE = this.NOTE,
				STATUS_FLAG = this.STATUS_FLAG,
				PHONE_NO = this.PHONE_NO,
				PHONE_DEPTCODE = this.PHONE_DEPTCODE,
			};
		}
	} 
}
