//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class SCRIPTS_SECTION_TRACK
	{
		public SCRIPTS_SECTION_TRACK ToPOCO(bool isPOCO = true){
			return new SCRIPTS_SECTION_TRACK(){
				PKID = this.PKID,
				ORD_NUM = this.ORD_NUM,
				MAT_NAME = this.MAT_NAME,
				TRACK_TYPE = this.TRACK_TYPE,
				TRACK_UNIT = this.TRACK_UNIT,
				TRACK_COUNT = this.TRACK_COUNT,
				TRACK_ADDR = this.TRACK_ADDR,
				TRACK_GROUP = this.TRACK_GROUP,
				GWD_CODE = this.GWD_CODE,
				CJ_CODE = this.CJ_CODE,
				CRT_USER = this.CRT_USER,
				CTR_TIME = this.CTR_TIME,
				MEMO = this.MEMO,
			};
		}
	} 
}
