//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class SYS_USERLOGIN
	{
		public SYS_USERLOGIN ToPOCO(bool isPOCO = true){
			return new SYS_USERLOGIN(){
				USERNAME = this.USERNAME,
				MAC = this.MAC,
				IP = this.IP,
				ADDTIME = this.ADDTIME,
				ERRERNUM = this.ERRERNUM,
			};
		}
	} 
}
