//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_ASS_PLAN_CONSTRUCTION
	{
		public T_ASS_PLAN_CONSTRUCTION ToPOCO(bool isPOCO = true){
			return new T_ASS_PLAN_CONSTRUCTION(){
				PLAN_ID = this.PLAN_ID,
				AREACODEPHONE = this.AREACODEPHONE,
				PLAN_LEVEL = this.PLAN_LEVEL,
				LINE_CODE = this.LINE_CODE,
				LINE_DIR = this.LINE_DIR,
				ITEM = this.ITEM,
				LOCATION = this.LOCATION,
				WORKDATE = this.WORKDATE,
				BLOCKTIME = this.BLOCKTIME,
				CONTENT = this.CONTENT,
				SPEEDCHANGE = this.SPEEDCHANGE,
				EQUMWNTCHANGE = this.EQUMWNTCHANGE,
				TRANSIT = this.TRANSIT,
				WORKUNIT = this.WORKUNIT,
				WORKWITHUNIT = this.WORKWITHUNIT,
				TURNNUM = this.TURNNUM,
				IMPDEP = this.IMPDEP,
			};
		}
	} 
}
