//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_ASS_TQI_PARA
	{
		public T_ASS_TQI_PARA ToPOCO(bool isPOCO = true){
			return new T_ASS_TQI_PARA(){
				PKID = this.PKID,
				TQIVALUE = this.TQIVALUE,
				TQIVALTEN = this.TQIVALTEN,
				TQIVALTWENTY = this.TQIVALTWENTY,
				N_SPEED_LEVEL = this.N_SPEED_LEVEL,
				TQIVALTHIRTY = this.TQIVALTHIRTY,
			};
		}
	} 
}
