//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_ASS_UNIT625
	{
		public T_ASS_UNIT625 ToPOCO(bool isPOCO = true){
			return new T_ASS_UNIT625(){
				PKID = this.PKID,
				FKID = this.FKID,
				C_GWD_CODE = this.C_GWD_CODE,
				C_DEPT_CODE = this.C_DEPT_CODE,
				N_UNIT_NUM = this.N_UNIT_NUM,
				N_UNIT625_NUM = this.N_UNIT625_NUM,
				C_LINE_CODE = this.C_LINE_CODE,
				C_LINE_NAME = this.C_LINE_NAME,
				C_LINE_DIR = this.C_LINE_DIR,
				N_START_MILE = this.N_START_MILE,
				N_END_MILE = this.N_END_MILE,
				C_LINE_FEATURE = this.C_LINE_FEATURE,
				T_CRT_TM = this.T_CRT_TM,
				C_CRT_NAME = this.C_CRT_NAME,
				C_EFF_FLAG = this.C_EFF_FLAG,
				N_ORDER = this.N_ORDER,
				C_MEMO = this.C_MEMO,
			};
		}
	} 
}
