//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_ASS_FLOW_USER_ROLE
	{
		public T_ASS_FLOW_USER_ROLE ToPOCO(bool isPOCO = true){
			return new T_ASS_FLOW_USER_ROLE(){
				USER_ROLE_ID = this.USER_ROLE_ID,
				USE_ID = this.USE_ID,
				ROLE_ID = this.ROLE_ID,
			};
		}
	} 
}
