//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_ASS_PLAN_UNIT_PRO_STAT
	{
		public T_ASS_PLAN_UNIT_PRO_STAT ToPOCO(bool isPOCO = true){
			return new T_ASS_PLAN_UNIT_PRO_STAT(){
				PKID = this.PKID,
				PLAN_ID = this.PLAN_ID,
				FLOWID = this.FLOWID,
				LOC_PKID = this.LOC_PKID,
				FLAG = this.FLAG,
				LINE_CODE = this.LINE_CODE,
				LINE_DIR = this.LINE_DIR,
				UNIT_NUM = this.UNIT_NUM,
				UNIT_START_MILE = this.UNIT_START_MILE,
				UNIT_END_MILE = this.UNIT_END_MILE,
				STATION_CODE = this.STATION_CODE,
				TRACK_CODE = this.TRACK_CODE,
				TURNOUT_CODE = this.TURNOUT_CODE,
				TRACK_PRO_NUM = this.TRACK_PRO_NUM,
				TRACK_PRO_PEAK = this.TRACK_PRO_PEAK,
				TRACK_PRO_PLACE = this.TRACK_PRO_PLACE,
				HILOW_PRO_NUM = this.HILOW_PRO_NUM,
				HILOW_PRO_PEAK = this.HILOW_PRO_PEAK,
				HILOW_PRO_PLACE = this.HILOW_PRO_PLACE,
				GAUGE_PRO_NUM = this.GAUGE_PRO_NUM,
				GAUGE_PRO_PEAK = this.GAUGE_PRO_PEAK,
				GAUGE_PRO_PLACE = this.GAUGE_PRO_PLACE,
				HORIAONTAL_PRO_NUM = this.HORIAONTAL_PRO_NUM,
				HORIAONTAL_PRO_PEAK = this.HORIAONTAL_PRO_PEAK,
				HORIAONTAL_PRO_PLACE = this.HORIAONTAL_PRO_PLACE,
				TWIST_PRO_NUM = this.TWIST_PRO_NUM,
				TWIST_PRO_PEAK = this.TWIST_PRO_PEAK,
				TWIST_PRO_PLACE = this.TWIST_PRO_PLACE,
				OTHER_PRO_NUM = this.OTHER_PRO_NUM,
				OTHER_PRO_PEAK = this.OTHER_PRO_PEAK,
				OTHER_PRO_PLACE = this.OTHER_PRO_PLACE,
				MEMO = this.MEMO,
				CRT_TM = this.CRT_TM,
			};
		}
	} 
}
