//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_ASS_MATERIAL
	{
		public T_ASS_MATERIAL ToPOCO(bool isPOCO = true){
			return new T_ASS_MATERIAL(){
				PKID = this.PKID,
				C_MATERIALNAME = this.C_MATERIALNAME,
				C_MATERIAL_TYPE = this.C_MATERIAL_TYPE,
				C_MATERIAL_UNIT = this.C_MATERIAL_UNIT,
				C_SAFETYRISKTIPS = this.C_SAFETYRISKTIPS,
				C_EFF_FLAG = this.C_EFF_FLAG,
				N_ORDER = this.N_ORDER,
				C_MEMO = this.C_MEMO,
			};
		}
	} 
}
