//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_ASS_TQI_DETAIL
	{
		public T_ASS_TQI_DETAIL ToPOCO(bool isPOCO = true){
			return new T_ASS_TQI_DETAIL(){
				PKID = this.PKID,
				FKID = this.FKID,
				C_GWD_CODE = this.C_GWD_CODE,
				C_DEP_CODE = this.C_DEP_CODE,
				C_DEP_NAME = this.C_DEP_NAME,
				C_DEP_PROP = this.C_DEP_PROP,
				C_LINE_CODE = this.C_LINE_CODE,
				C_LINE_NAME = this.C_LINE_NAME,
				C_LINE_DIR = this.C_LINE_DIR,
				C_LINE_CAT = this.C_LINE_CAT,
				N_PRO_MILE = this.N_PRO_MILE,
				C_PRO_CODE = this.C_PRO_CODE,
				C_PRO_NAME = this.C_PRO_NAME,
				C_LEVEL = this.C_LEVEL,
				N_TQI_PEAK = this.N_TQI_PEAK,
				C_TQI_OVER = this.C_TQI_OVER,
				D_CHECK_DATE = this.D_CHECK_DATE,
				C_JOB_FLAG = this.C_JOB_FLAG,
				C_JOB_NO = this.C_JOB_NO,
				C_REPAIR_FLAG = this.C_REPAIR_FLAG,
				D_REPAIR_DATE = this.D_REPAIR_DATE,
				C_REPAIR_RES = this.C_REPAIR_RES,
				C_DOC_FLAG = this.C_DOC_FLAG,
				T_CRT_TM = this.T_CRT_TM,
				C_CRT_NAME = this.C_CRT_NAME,
				C_EFF_FLAG = this.C_EFF_FLAG,
				N_ORDER = this.N_ORDER,
				C_MEMO = this.C_MEMO,
				N_PRO_PEAK = this.N_PRO_PEAK,
				N_SPEED = this.N_SPEED,
				N_SPEED_SPAN = this.N_SPEED_SPAN,
			};
		}
	} 
}
