//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_ASS_PLAN_LOCATE
	{
		public T_ASS_PLAN_LOCATE ToPOCO(bool isPOCO = true){
			return new T_ASS_PLAN_LOCATE(){
				PKID = this.PKID,
				PLAN_ID = this.PLAN_ID,
				FLOWID = this.FLOWID,
				ITEM = this.ITEM,
				WINDOW_TYPE = this.WINDOW_TYPE,
				PLAN_LEVEL = this.PLAN_LEVEL,
				LINE_CODE = this.LINE_CODE,
				LINE_DIR = this.LINE_DIR,
				PLAN_TIME = this.PLAN_TIME,
				START_MILE = this.START_MILE,
				END_MILE = this.END_MILE,
				STATION = this.STATION,
				TRACKNO = this.TRACKNO,
				TURNOUTNO = this.TURNOUTNO,
				EQUIP_UNIT_NO = this.EQUIP_UNIT_NO,
				LABOUR = this.LABOUR,
				TOOLS = this.TOOLS,
				MATERIALS = this.MATERIALS,
				CONTENT = this.CONTENT,
				SPEED_CHANGE = this.SPEED_CHANGE,
				TRAINS = this.TRAINS,
				REMARK = this.REMARK,
				MEMO = this.MEMO,
				CRT_TIME = this.CRT_TIME,
				ITEM_TYPE = this.ITEM_TYPE,
				FC_PLAN_TIME = this.FC_PLAN_TIME,
				FC_ORDER = this.FC_ORDER,
				TURNNUM = this.TURNNUM,
				PLAN_QUANTITY = this.PLAN_QUANTITY,
				ACTUAL_QUANTITY = this.ACTUAL_QUANTITY,
				FLAG = this.FLAG,
				ACTUAL_LOC = this.ACTUAL_LOC,
			};
		}
	} 
}
