//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_ASS_PARAREPORT_TEMP
	{
		public T_ASS_PARAREPORT_TEMP ToPOCO(bool isPOCO = true){
			return new T_ASS_PARAREPORT_TEMP(){
				PKID = this.PKID,
				C_DEP_CODE = this.C_DEP_CODE,
				C_DEP_NAME = this.C_DEP_NAME,
				C_CODE = this.C_CODE,
				C_NAME = this.C_NAME,
				C_TYPE = this.C_TYPE,
				C_CHECK_COUNT = this.C_CHECK_COUNT,
				C_LEVEL_GOOD = this.C_LEVEL_GOOD,
				C_LEVEL_KIND = this.C_LEVEL_KIND,
				C_LEVEL_POOR = this.C_LEVEL_POOR,
				C_JHCC_SCORE = this.C_JHCC_SCORE,
				C_GG_SCORE = this.C_GG_SCORE,
				C_GZ_SCORE = this.C_GZ_SCORE,
				C_PX_SCORE = this.C_PX_SCORE,
				C_DC_SCORE = this.C_DC_SCORE,
				C_OTHER_SCORE = this.C_OTHER_SCORE,
				C_CUR_GOOD = this.C_CUR_GOOD,
				C_CUR_KIND = this.C_CUR_KIND,
				C_CUR_POOR = this.C_CUR_POOR,
				C_USER_ID = this.C_USER_ID,
				C_DATE = this.C_DATE,
				C_FLAG = this.C_FLAG,
				DC_CHECK_NUM = this.DC_CHECK_NUM,
				DC_LEVEL_GOOD = this.DC_LEVEL_GOOD,
				DC_LEVEL_KIND = this.DC_LEVEL_KIND,
				DC_LEVEL_POOR = this.DC_LEVEL_POOR,
				DC_JHCC_SCORE = this.DC_JHCC_SCORE,
				DC_GG_SCORE = this.DC_GG_SCORE,
				DC_GZ_SCORE = this.DC_GZ_SCORE,
				DC_PX_SCORE = this.DC_PX_SCORE,
				DC_DC_SCORE = this.DC_DC_SCORE,
				DC_OTHER_SCORE = this.DC_OTHER_SCORE,
				C_MEMO = this.C_MEMO,
			};
		}
	} 
}
