//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_ASS_PROBLEM_LJ
	{
		public T_ASS_PROBLEM_LJ ToPOCO(bool isPOCO = true){
			return new T_ASS_PROBLEM_LJ(){
				C_NUM = this.C_NUM,
				C_CODE = this.C_CODE,
				C_TYPE = this.C_TYPE,
				C_COUNT = this.C_COUNT,
				C_GJ = this.C_GJ,
				C_SP = this.C_SP,
				C_GD = this.C_GD,
				C_GX = this.C_GX,
				C_SJK = this.C_SJK,
				C_OTHER = this.C_OTHER,
				C_LAST_NOCAN = this.C_LAST_NOCAN,
				C_ZXD = this.C_ZXD,
				C_NOW_ADD = this.C_NOW_ADD,
				C_ZXS = this.C_ZXS,
				C_NOW_OVER = this.C_NOW_OVER,
				C_ZZX = this.C_ZZX,
				C_NOT_TOTAIL = this.C_NOT_TOTAIL,
				C_ZZD = this.C_ZZD,
				C_ID = this.C_ID,
				C_DEPCODE = this.C_DEPCODE,
			};
		}
	} 
}
