//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_ASS_TRACK_VAL_DETAIL
	{
		public T_ASS_TRACK_VAL_DETAIL ToPOCO(bool isPOCO = true){
			return new T_ASS_TRACK_VAL_DETAIL(){
				PKID = this.PKID,
				FKID = this.FKID,
				C_GWD_CODE = this.C_GWD_CODE,
				C_DEP_CODE = this.C_DEP_CODE,
				N_UNIT_NUM = this.N_UNIT_NUM,
				C_TRACK_CODE = this.C_TRACK_CODE,
				C_LINE_CODE = this.C_LINE_CODE,
				C_LINE_NAME = this.C_LINE_NAME,
				C_LINE_DIR = this.C_LINE_DIR,
				C_STATION_NAME = this.C_STATION_NAME,
				C_STATION_CODE = this.C_STATION_CODE,
				C_ITEM = this.C_ITEM,
				C_PRO_NAME = this.C_PRO_NAME,
				C_PRO_PLACE = this.C_PRO_PLACE,
				N_PEAK = this.N_PEAK,
				N_SCORE = this.N_SCORE,
				C_STANDARD = this.C_STANDARD,
				C_CHECK_TYPE = this.C_CHECK_TYPE,
				C_CHECK_DEV = this.C_CHECK_DEV,
				T_ASS_DATE = this.T_ASS_DATE,
				C_EFF_FLAG = this.C_EFF_FLAG,
				N_ORDER = this.N_ORDER,
				C_MEMO = this.C_MEMO,
				C_PRO_CODE = this.C_PRO_CODE,
				C_PRO_DETAIL = this.C_PRO_DETAIL,
				N_SPEED = this.N_SPEED,
				C_LINE_CAT = this.C_LINE_CAT,
				C_ASS_DEP_CODE = this.C_ASS_DEP_CODE,
				D_CHECK_DATE = this.D_CHECK_DATE,
				C_INSPECTOR = this.C_INSPECTOR,
				C_POST = this.C_POST,
				N_TQI_VALUE = this.N_TQI_VALUE,
				N_TQI_SCORE = this.N_TQI_SCORE,
			};
		}
	} 
}
