//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_ASS_STATION
	{
		public T_ASS_STATION ToPOCO(bool isPOCO = true){
			return new T_ASS_STATION(){
				PKID = this.PKID,
				C_GWD_CODE = this.C_GWD_CODE,
				C_DEP_CODE = this.C_DEP_CODE,
				C_STATION_NAME = this.C_STATION_NAME,
				C_STATION_CODE = this.C_STATION_CODE,
				C_RUN_STATUS = this.C_RUN_STATUS,
				C_LINE_CODE = this.C_LINE_CODE,
				C_THREAD_SIGN = this.C_THREAD_SIGN,
				C_LINE_DIR = this.C_LINE_DIR,
				C_PY_PREFIX = this.C_PY_PREFIX,
				C_SKILL_WORK = this.C_SKILL_WORK,
				C_BUSINESS_TYPE = this.C_BUSINESS_TYPE,
				C_STATION_GRADE = this.C_STATION_GRADE,
				C_GAUGE_TYPE = this.C_GAUGE_TYPE,
				N_CENTER_MILE = this.N_CENTER_MILE,
				N_AREA_MILE = this.N_AREA_MILE,
				N_MIN_RADIUS = this.N_MIN_RADIUS,
				N_MAX_SLOPE = this.N_MAX_SLOPE,
				N_TRACK_NUM = this.N_TRACK_NUM,
				N_TURNOUT_NUM = this.N_TURNOUT_NUM,
				N_DOWN_INMAC = this.N_DOWN_INMAC,
				N_DOWN_VALID = this.N_DOWN_VALID,
				N_UP_INMAC = this.N_UP_INMAC,
				N_UP_VALID = this.N_UP_VALID,
				N_LONGITUDE = this.N_LONGITUDE,
				N_LATITUDE = this.N_LATITUDE,
				T_CRT_TM = this.T_CRT_TM,
				C_CRT_NAME = this.C_CRT_NAME,
				C_EFF_FLAG = this.C_EFF_FLAG,
				N_ORDER = this.N_ORDER,
				C_MEMO = this.C_MEMO,
			};
		}
	} 
}
