//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_CHK_LINE
	{
		public T_CHK_LINE ToPOCO(bool isPOCO = true){
			return new T_CHK_LINE(){
				PKID = this.PKID,
				LINE_NAME = this.LINE_NAME,
				LINE_DIR = this.LINE_DIR,
				START_MILE = this.START_MILE,
				END_MILE = this.END_MILE,
				STATION_NAME = this.STATION_NAME,
				TRACK_NUM = this.TRACK_NUM,
				SPEED_RANGE = this.SPEED_RANGE,
				DIR_TYPE = this.DIR_TYPE,
				NAME = this.NAME,
				PHONE_NO = this.PHONE_NO,
				CHK_NAME = this.CHK_NAME,
				CHK_TM = this.CHK_TM,
				CRT_TM = this.CRT_TM,
				CRT_NAME = this.CRT_NAME,
				UPD_TM = this.UPD_TM,
				UPD_NAME = this.UPD_NAME,
				SHOW_ORDER = this.SHOW_ORDER,
				LINE_TYPE = this.LINE_TYPE,
				CHECK_POS = this.CHECK_POS,
			};
		}
	} 
}
