//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_CHK_LINE_ITEMS
	{
		public T_CHK_LINE_ITEMS ToPOCO(bool isPOCO = true){
			return new T_CHK_LINE_ITEMS(){
				PKID = this.PKID,
				FKID = this.FKID,
				RAIL_NO = this.RAIL_NO,
				LICHENG = this.LICHENG,
				POS_TYPE = this.POS_TYPE,
				TYPE = this.TYPE,
				ADD_FLAG = this.ADD_FLAG,
				GAUGE = this.GAUGE,
				C_LEVEL = this.C_LEVEL,
				TWIST = this.TWIST,
				TRACK = this.TRACK,
				HIGH_LOW = this.HIGH_LOW,
				REPAIR_TM_CONTENT = this.REPAIR_TM_CONTENT,
				CHK_TM = this.CHK_TM,
				LNG = this.LNG,
				LAT = this.LAT,
				MARS_LNG = this.MARS_LNG,
				MARS_LAT = this.MARS_LAT,
				BAIDU_LNG = this.BAIDU_LNG,
				BAIDU_LAT = this.BAIDU_LAT,
				GPS_TM = this.GPS_TM,
				RECHECK_FLAG = this.RECHECK_FLAG,
				CURVE_RADIUS = this.CURVE_RADIUS,
				SUPHIGH = this.SUPHIGH,
				SLOPE_RATE = this.SLOPE_RATE,
				WIDENING_VALUE = this.WIDENING_VALUE,
			};
		}
	} 
}
