//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_CHK_CURVE_ITEMS
	{
		public T_CHK_CURVE_ITEMS ToPOCO(bool isPOCO = true){
			return new T_CHK_CURVE_ITEMS(){
				PKID = this.PKID,
				FKID = this.FKID,
				CHK_NO = this.CHK_NO,
				TYPE_CURVE = this.TYPE_CURVE,
				VERSINE_CALC = this.VERSINE_CALC,
				TRACK_MM = this.TRACK_MM,
				VERSINE_TRACKED = this.VERSINE_TRACKED,
				VERSINE_SCENE = this.VERSINE_SCENE,
				RECORD = this.RECORD,
				CHK_TM = this.CHK_TM,
				LNG = this.LNG,
				LAT = this.LAT,
				MARS_LNG = this.MARS_LNG,
				MARS_LAT = this.MARS_LAT,
				BAIDU_LNG = this.BAIDU_LNG,
				BAIDU_LAT = this.BAIDU_LAT,
				GPS_TM = this.GPS_TM,
				RECHECK_FLAG = this.RECHECK_FLAG,
			};
		}
	} 
}
