//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_CHK_DISEASE_STANDARD
	{
		public T_CHK_DISEASE_STANDARD ToPOCO(bool isPOCO = true){
			return new T_CHK_DISEASE_STANDARD(){
				PKID = this.PKID,
				CHECK_TYPE = this.CHECK_TYPE,
				SPEED_RANGE = this.SPEED_RANGE,
				WARN_LEVEL = this.WARN_LEVEL,
				POS_CODE = this.POS_CODE,
				CHECK_ITEM = this.CHECK_ITEM,
				CURVE_RADIUS_RANGE = this.CURVE_RADIUS_RANGE,
				CURVE_SPEED_RANGE = this.CURVE_SPEED_RANGE,
				CURVE_TYPE = this.CURVE_TYPE,
				POSITIVE_VALUE = this.POSITIVE_VALUE,
				NEGATIVE = this.NEGATIVE,
			};
		}
	} 
}
