//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_CZ_PHONE
	{
		public T_CZ_PHONE ToPOCO(bool isPOCO = true){
			return new T_CZ_PHONE(){
				机车号 = this.机车号,
				手机号 = this.手机号,
				车型 = this.车型,
				转发 = this.转发,
			};
		}
	} 
}
