//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_CZ_WARP
	{
		public T_CZ_WARP ToPOCO(bool isPOCO = true){
			return new T_CZ_WARP(){
				ID = this.ID,
				线名 = this.线名,
				线编号 = this.线编号,
				行别 = this.行别,
				里程 = this.里程,
				速度 = this.速度,
				水加 = this.水加,
				水加级别 = this.水加级别,
				垂加 = this.垂加,
				垂加级别 = this.垂加级别,
				时间 = this.时间,
				机车号 = this.机车号,
				车次 = this.车次,
				工区 = this.工区,
				车间 = this.车间,
				工务段 = this.工务段,
				路局 = this.路局,
				道岔 = this.道岔,
				道口 = this.道口,
				曲线 = this.曲线,
				桥梁 = this.桥梁,
				涵洞 = this.涵洞,
				隧道 = this.隧道,
				竖曲线 = this.竖曲线,
				自定义 = this.自定义,
				侧向 = this.侧向,
				长链 = this.长链,
				其他标记 = this.其他标记,
				动车 = this.动车,
				厂家 = this.厂家,
				车型 = this.车型,
				车型编号 = this.车型编号,
				重复次数 = this.重复次数,
				GRADE = this.GRADE,
				段编号 = this.段编号,
			};
		}
	} 
}
