//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_GIS_LINE_TEST_NOPWD
	{
		public T_GIS_LINE_TEST_NOPWD ToPOCO(bool isPOCO = true){
			return new T_GIS_LINE_TEST_NOPWD(){
				PKID = this.PKID,
				工务段 = this.工务段,
				路局 = this.路局,
				线名 = this.线名,
				行别 = this.行别,
				里程 = this.里程,
				经度 = this.经度,
				纬度 = this.纬度,
				火星经度 = this.火星经度,
				火星纬度 = this.火星纬度,
				百度经度 = this.百度经度,
				百度纬度 = this.百度纬度,
				高程 = this.高程,
			};
		}
	} 
}
