//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_GWDETAIL
	{
		public T_GWDETAIL ToPOCO(bool isPOCO = true){
			return new T_GWDETAIL(){
				监测点 = this.监测点,
				时间 = this.时间,
				轨温 = this.轨温,
				报警 = this.报警,
				手机号 = this.手机号,
			};
		}
	} 
}
