//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_GWBASE_SECTION_LINE
	{
		public T_GWBASE_SECTION_LINE ToPOCO(bool isPOCO = true){
			return new T_GWBASE_SECTION_LINE(){
				GW_SECTION_ID = this.GW_SECTION_ID,
				经度 = this.经度,
				纬度 = this.纬度,
				火星经度 = this.火星经度,
				火星纬度 = this.火星纬度,
				百度经度 = this.百度经度,
				百度纬度 = this.百度纬度,
				MILEAGE = this.MILEAGE,
				区段 = this.区段,
				监测点 = this.监测点,
				路局 = this.路局,
				起始里程 = this.起始里程,
				结束里程 = this.结束里程,
				GW_PKID = this.GW_PKID,
			};
		}
	} 
}
