//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_LKJ_FLOW_STEPINFO
	{
		public T_LKJ_FLOW_STEPINFO ToPOCO(bool isPOCO = true){
			return new T_LKJ_FLOW_STEPINFO(){
				FLOWID = this.FLOWID,
				STEPID = this.STEPID,
				STEPNAME = this.STEPNAME,
				PAGEURL = this.PAGEURL,
				DOCFLAG = this.DOCFLAG,
				FLOWTYPE = this.FLOWTYPE,
			};
		}
	} 
}
