//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_LKJ_FLOW_USERROLE
	{
		public T_LKJ_FLOW_USERROLE ToPOCO(bool isPOCO = true){
			return new T_LKJ_FLOW_USERROLE(){
				USER_ROLEID = this.USER_ROLEID,
				USER_ID = this.USER_ID,
				ROLE_ID = this.ROLE_ID,
			};
		}
	} 
}
