//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_RAIN
	{
		public T_RAIN ToPOCO(bool isPOCO = true){
			return new T_RAIN(){
				编号 = this.编号,
				时间 = this.时间,
				分钟雨量 = this.分钟雨量,
				十分钟雨量 = this.十分钟雨量,
				三十分钟雨量 = this.三十分钟雨量,
				一小时雨量 = this.一小时雨量,
				三小时雨量 = this.三小时雨量,
				十二小时雨量 = this.十二小时雨量,
				二十四小时雨量 = this.二十四小时雨量,
				连续雨量 = this.连续雨量,
				今日雨量 = this.今日雨量,
				昨日雨量 = this.昨日雨量,
				连续开始时间 = this.连续开始时间,
				连续结束时间 = this.连续结束时间,
				降雨级别 = this.降雨级别,
				WRITEDATE = this.WRITEDATE,
			};
		}
	} 
}
