//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_RAINWARN
	{
		public T_RAINWARN ToPOCO(bool isPOCO = true){
			return new T_RAINWARN(){
				编号 = this.编号,
				时间 = this.时间,
				报警类型 = this.报警类型,
				报警雨量种类 = this.报警雨量种类,
				报警雨量 = this.报警雨量,
				复合雨量种类 = this.复合雨量种类,
				复合雨量 = this.复合雨量,
				连续开始时间 = this.连续开始时间,
				报警解除时间 = this.报警解除时间,
				报警门限 = this.报警门限,
				复合报警门限 = this.复合报警门限,
				显示标志 = this.显示标志,
				区段编号 = this.区段编号,
				限速 = this.限速,
			};
		}
	} 
}
