//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class T_WATER_DEVICE
	{
		public T_WATER_DEVICE ToPOCO(bool isPOCO = true){
			return new T_WATER_DEVICE(){
				路局 = this.路局,
				监测点 = this.监测点,
				设备手机号 = this.设备手机号,
				工务段 = this.工务段,
				车间 = this.车间,
				线名 = this.线名,
				行别 = this.行别,
				里程 = this.里程,
				区段 = this.区段,
				火星经度 = this.火星经度,
				火星纬度 = this.火星纬度,
				转发手机号 = this.转发手机号,
				设备编号 = this.设备编号,
			};
		}
	} 
}
