//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class TASK_CARD
	{
		public TASK_CARD ToPOCO(bool isPOCO = true){
			return new TASK_CARD(){
				CARD_ID = this.CARD_ID,
				DEPT_CODE = this.DEPT_CODE,
				CARD_NAME = this.CARD_NAME,
			};
		}
	} 
}
