//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class TASK_SLIGHT_RAILP43
	{
		public TASK_SLIGHT_RAILP43 ToPOCO(bool isPOCO = true){
			return new TASK_SLIGHT_RAILP43(){
				PKID = this.PKID,
				DEPTID = this.DEPTID,
				IS_SUBMIT = this.IS_SUBMIT,
				CREATE_TIME = this.CREATE_TIME,
				CREATE_USER = this.CREATE_USER,
				GWD_CODE = this.GWD_CODE,
				DEPT_CODE = this.DEPT_CODE,
				GQ_CODE = this.GQ_CODE,
				YEAR = this.YEAR,
				MONTH = this.MONTH,
				DAILY = this.DAILY,
				DEPTNAME = this.DEPTNAME,
				FOUND_MILE = this.FOUND_MILE,
				RAILNO = this.RAILNO,
				LFTACK = this.LFTACK,
				RAIL_MODEL = this.RAIL_MODEL,
				FOUND_TIME = this.FOUND_TIME,
				FOUND_MEMBER = this.FOUND_MEMBER,
				FACTORY = this.FACTORY,
				SENDS_DATE = this.SENDS_DATE,
				RAIL_LENGTH = this.RAIL_LENGTH,
				BREAK_REASON = this.BREAK_REASON,
				BREAK_FLAG = this.BREAK_FLAG,
				COME_MEMBER = this.COME_MEMBER,
				MEMO = this.MEMO,
				REPLACE_FLAG = this.REPLACE_FLAG,
				REPLACE_DATE = this.REPLACE_DATE,
			};
		}
	} 
}
