//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class TASK_PLAN_TOOL
	{
		public TASK_PLAN_TOOL ToPOCO(bool isPOCO = true){
			return new TASK_PLAN_TOOL(){
				PKID = this.PKID,
				PLAN_ID = this.PLAN_ID,
				DEP_CODE = this.DEP_CODE,
				TOOL_ID = this.TOOL_ID,
				QUANTUM = this.QUANTUM,
				QUANTMEMBER = this.QUANTMEMBER,
			};
		}
	} 
}
