//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class TASK_RAILCOUNT
	{
		public TASK_RAILCOUNT ToPOCO(bool isPOCO = true){
			return new TASK_RAILCOUNT(){
				PKID = this.PKID,
				MILE_PLACECODE = this.MILE_PLACECODE,
				GWD_CODE = this.GWD_CODE,
				DEP_CODE = this.DEP_CODE,
				GQ_CODE = this.GQ_CODE,
				MILE_PLACE = this.MILE_PLACE,
				RAIL_TYPE = this.RAIL_TYPE,
				RAIL_MODEL = this.RAIL_MODEL,
				MILEAGE = this.MILEAGE,
				RAILHC = this.RAILHC,
				RAILNUM = this.RAILNUM,
				MEMO = this.MEMO,
				CREATE_USER = this.CREATE_USER,
				CREATE_DATE = this.CREATE_DATE,
				CREATE_DEPT = this.CREATE_DEPT,
			};
		}
	} 
}
