//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class TASK_FLOOR
	{
		public TASK_FLOOR ToPOCO(bool isPOCO = true){
			return new TASK_FLOOR(){
				PKID = this.PKID,
				LINECODE = this.LINECODE,
				LINEDIR = this.LINEDIR,
				LR = this.LR,
				LRCODE = this.LRCODE,
				LICHENG = this.LICHENG,
				NUMBERTYPE = this.NUMBERTYPE,
				CAIZHI = this.CAIZHI,
				OPENTYPE = this.OPENTYPE,
				CHICUN = this.CHICUN,
				NUMBERS = this.NUMBERS,
				UNIT = this.UNIT,
				YN = this.YN,
				DEPTCODE = this.DEPTCODE,
				GWDCODE = this.GWDCODE,
				MEMO = this.MEMO,
			};
		}
	} 
}
