//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class TASK_PLAN_PROBLEM
	{
		public TASK_PLAN_PROBLEM ToPOCO(bool isPOCO = true){
			return new TASK_PLAN_PROBLEM(){
				PKID = this.PKID,
				PLAN_ID = this.PLAN_ID,
				DEP_CODE = this.DEP_CODE,
				LOC_PKID = this.LOC_PKID,
				PROBLEM_ID = this.PROBLEM_ID,
				C_LINE_CODE = this.C_LINE_CODE,
				C_LINE_DIR = this.C_LINE_DIR,
				C_STATION_CODE = this.C_STATION_CODE,
				C_TRACK_CODE = this.C_TRACK_CODE,
				C_TURNOUT_CODE = this.C_TURNOUT_CODE,
				C_PRO_ITEM = this.C_PRO_ITEM,
				C_PRO_CODE = this.C_PRO_CODE,
				C_UNIT_NUM = this.C_UNIT_NUM,
				C_PRO_PLACE = this.C_PRO_PLACE,
				N_PRO_MILE = this.N_PRO_MILE,
				N_PRO_PEAK = this.N_PRO_PEAK,
				C_PRO_DETAIL = this.C_PRO_DETAIL,
				N_SPEED = this.N_SPEED,
				N_OVERRUN_LEVEL = this.N_OVERRUN_LEVEL,
				C_CHECK_TYPE = this.C_CHECK_TYPE,
				C_CHECK_DEV = this.C_CHECK_DEV,
				C_INSPECTOR = this.C_INSPECTOR,
				D_CHECK_DATE = this.D_CHECK_DATE,
				T_PRO_CRT_TM = this.T_PRO_CRT_TM,
				D_REPAIR_DATE = this.D_REPAIR_DATE,
				C_REPAIR_RES = this.C_REPAIR_RES,
				MEMO = this.MEMO,
				C_LINE_FEATURE = this.C_LINE_FEATURE,
				FLAG = this.FLAG,
				COMPOSITE = this.COMPOSITE,
				C_REPAIR_MAN = this.C_REPAIR_MAN,
			};
		}
	} 
}
