//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class TOOL_PHONE_USER
	{
		public TOOL_PHONE_USER ToPOCO(bool isPOCO = true){
			return new TOOL_PHONE_USER(){
				PKID = this.PKID,
				USER_NAME = this.USER_NAME,
				PASSWORD = this.PASSWORD,
			};
		}
	} 
}
