//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class TOOL_USE
	{
		public TOOL_USE ToPOCO(bool isPOCO = true){
			return new TOOL_USE(){
				SID = this.SID,
				JOB_NO = this.JOB_NO,
				USE_TOOL_ID = this.USE_TOOL_ID,
				USE_TOOL_NAME = this.USE_TOOL_NAME,
				USE_TOOL_TIME = this.USE_TOOL_TIME,
				RETURN_TOOL_TIME = this.RETURN_TOOL_TIME,
				DEMO = this.DEMO,
				TOOL_STATU = this.TOOL_STATU,
			};
		}
	} 
}
