//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class TURNOUT_HIS_PIC
	{
		public TURNOUT_HIS_PIC ToPOCO(bool isPOCO = true){
			return new TURNOUT_HIS_PIC(){
				PIC_ID = this.PIC_ID,
				HISTORY_ID = this.HISTORY_ID,
				FILE_NAME = this.FILE_NAME,
				FILE_URL = this.FILE_URL,
				FILE_UPTIME = this.FILE_UPTIME,
				FILE_NOTE = this.FILE_NOTE,
			};
		}
	} 
}
