//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class TURNOUT_HIS_BRANCH
	{
		public TURNOUT_HIS_BRANCH ToPOCO(bool isPOCO = true){
			return new TURNOUT_HIS_BRANCH(){
				BRANCH_ID = this.BRANCH_ID,
				HISTORY_ID = this.HISTORY_ID,
				BTANCH_LENGTH = this.BTANCH_LENGTH,
				BRANCH_NUM = this.BRANCH_NUM,
				BRANCH_NOTE = this.BRANCH_NOTE,
			};
		}
	} 
}
