//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class WIND_WARN_STANDARD
	{
		public WIND_WARN_STANDARD ToPOCO(bool isPOCO = true){
			return new WIND_WARN_STANDARD(){
				报警ID = this.报警ID,
				报警条件 = this.报警条件,
				报警内容 = this.报警内容,
				报警风速低速 = this.报警风速低速,
				报警风速高速 = this.报警风速高速,
				报警颜色 = this.报警颜色,
			};
		}
	} 
}
