//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class WIND_SECTION_LINE
	{
		public WIND_SECTION_LINE ToPOCO(bool isPOCO = true){
			return new WIND_SECTION_LINE(){
				WIND_SECTION_ID = this.WIND_SECTION_ID,
				监测点 = this.监测点,
				线名 = this.线名,
				行别 = this.行别,
				起始里程 = this.起始里程,
				结束里程 = this.结束里程,
			};
		}
	} 
}
