//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class WIND_GRADING
	{
		public WIND_GRADING ToPOCO(bool isPOCO = true){
			return new WIND_GRADING(){
				等级 = this.等级,
				地面物象征 = this.地面物象征,
				风速低 = this.风速低,
				风速高 = this.风速高,
			};
		}
	} 
}
