//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class WIND_DAYRPT
	{
		public WIND_DAYRPT ToPOCO(bool isPOCO = true){
			return new WIND_DAYRPT(){
				手机号 = this.手机号,
				日最大时刻 = this.日最大时刻,
				日最大风速 = this.日最大风速,
				日最大风速风向 = this.日最大风速风向,
				MAX0 = this.MAX0,
				MAX1 = this.MAX1,
				MAX2 = this.MAX2,
				MAX3 = this.MAX3,
				MAX4 = this.MAX4,
				MAX5 = this.MAX5,
				MAX6 = this.MAX6,
				MAX7 = this.MAX7,
				MAX8 = this.MAX8,
				MAX9 = this.MAX9,
				MAX10 = this.MAX10,
				MAX11 = this.MAX11,
				MAX12 = this.MAX12,
				MAX13 = this.MAX13,
				MAX14 = this.MAX14,
				MAX15 = this.MAX15,
				MAX16 = this.MAX16,
				MAX17 = this.MAX17,
				MAX18 = this.MAX18,
				MAX19 = this.MAX19,
				MAX20 = this.MAX20,
				MAX21 = this.MAX21,
				MAX22 = this.MAX22,
				MAX23 = this.MAX23,
			};
		}
	} 
}
