//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class WUFENG_CHEZHAN
	{
		public WUFENG_CHEZHAN ToPOCO(bool isPOCO = true){
			return new WUFENG_CHEZHAN(){
				ID = this.ID,
				DANWEIBIANHAO = this.DANWEIBIANHAO,
				XIANBIANHAO = this.XIANBIANHAO,
				XIANMING = this.XIANMING,
				CHEZHANMING = this.CHEZHANMING,
				ZHANBIANHAO = this.ZHANBIANHAO,
				XINGBIE = this.XINGBIE,
				ZHONGXINLICHENG = this.ZHONGXINLICHENG,
				ZHANJIE1 = this.ZHANJIE1,
				ZHANJIE2 = this.ZHANJIE2,
			};
		}
	} 
}
