//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
	public partial class WUFENG_DAOCHA
	{
		public WUFENG_DAOCHA ToPOCO(bool isPOCO = true){
			return new WUFENG_DAOCHA(){
				ID = this.ID,
				DANWEIBIANHAO = this.DANWEIBIANHAO,
				XIANBIANHAO = this.XIANBIANHAO,
				XIANMING = this.XIANMING,
				XINGBIE = this.XINGBIE,
				XIANBIE = this.XIANBIE,
				CHAJIANLICHENG = this.CHAJIANLICHENG,
				CHAWEILICHENG = this.CHAWEILICHENG,
				FANGXIANG = this.FANGXIANG,
				XINGHAO = this.XINGHAO,
				BIANHAO = this.BIANHAO,
				QUANCHANG = this.QUANCHANG,
				CHEZHANMING = this.CHEZHANMING,
				ZHONGLEI = this.ZHONGLEI,
				GUIXING = this.GUIXING,
				ZHENMULEIXING = this.ZHENMULEIXING,
				ZHECHAHAO = this.ZHECHAHAO,
				ZHECHAGOUZAO = this.ZHECHAGOUZAO,
				SHENGCHANCHANGJIA = this.SHENGCHANCHANGJIA,
				SHANGXIANRIQI = this.SHANGXIANRIQI,
				ZHECHACHANG = this.ZHECHACHANG,
				JIANGUICHANG = this.JIANGUICHANG,
				JIANGUILEIXING = this.JIANGUILEIXING,
				PUSHENIANDU = this.PUSHENIANDU,
				SHEJITUHAO = this.SHEJITUHAO,
			};
		}
	} 
}
