//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_GATE_GATEMNG_STATE   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string STATE_ID { get; set; }
        public string GATE_NO { get; set; }
        public string STATE_FLAG { get; set; }
        public Nullable<System.DateTime> STATE_TIME { get; set; }
        public string GATEMAGNETS_FLAG { get; set; }
        public string GATELOCK_FLAG { get; set; }
        public string READCARD_FLAG { get; set; }
        public string POWERTYPE { get; set; }
        public Nullable<decimal> POWERV { get; set; }
        public string STATE_LOG { get; set; }
        public string STATE_ORDER { get; set; }
        public string CODELOCK_FLAG { get; set; }
        public string CODELOCK_ENABLENUM { get; set; }
        public Nullable<decimal> CODELOCK_POWERV { get; set; }
        public string OPENGATE_TYPE { get; set; }
        public string CARD_NO { get; set; }
        public string COMMAND_NO { get; set; }
        public Nullable<decimal> BATTERY_VOLTAGE { get; set; }
        public Nullable<decimal> AC_VOLTAGE { get; set; }
    }
}
