//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_TASK_RAILCOUNT   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PKID { get; set; }
        public string MILE_PLACECODE { get; set; }
        public string GWD_CODE { get; set; }
        public string DEP_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string MILE_PLACE { get; set; }
        public string RAIL_TYPE { get; set; }
        public string RAIL_MODEL { get; set; }
        public string MILEAGE { get; set; }
        public string RAILHC { get; set; }
        public Nullable<decimal> RAILNUM { get; set; }
        public string MEMO { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_DEPT { get; set; }
    }
}
