//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_BRIDGE_OVERPASS_WATER   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string OVERPASSWATER_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string CJ_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public decimal CENTER_MILE { get; set; }
        public string HOLESPAN_STYLE { get; set; }
        public string BUILD_YEAR { get; set; }
        public string DRAINAGE_STYLE { get; set; }
        public string DRAINAGE_EQUIP { get; set; }
        public string ROAD_STRUCT { get; set; }
        public string REVETMENT_STYLE { get; set; }
        public string WATER_SEVERITY { get; set; }
        public string WATER_NOWSTATUS { get; set; }
        public string AISLE_MATERIAL { get; set; }
        public string AISLE_HEIGHTWIDTH { get; set; }
        public string RUN_STATUS { get; set; }
        public string MEMO { get; set; }
    }
}
