//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_T_ASS_TRACK   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PKID { get; set; }
        public string C_GWD_CODE { get; set; }
        public string C_DEP_CODE { get; set; }
        public string C_LINE_CODE { get; set; }
        public string C_LINE_DIR { get; set; }
        public string C_STATION_NAME { get; set; }
        public string C_STATION_CODE { get; set; }
        public string C_LINE_CAT { get; set; }
        public string C_RUN_STATUS { get; set; }
        public string C_TRACK_CODE { get; set; }
        public string C_LINE_TYPE { get; set; }
        public string C_GAUGE_TYPE { get; set; }
        public Nullable<short> N_VALID_LEN { get; set; }
        public Nullable<short> N_FULL_LEN { get; set; }
        public Nullable<int> N_WOOD_TIE_NUM { get; set; }
        public Nullable<int> N_CONCRETE_TIE_NUM { get; set; }
        public Nullable<int> N_STEEL_TIE_NUM { get; set; }
        public Nullable<int> N_BROAD_TIE_NUM { get; set; }
        public Nullable<int> N_LEFT_SPACING { get; set; }
        public Nullable<int> N_RIGHT_SPACING { get; set; }
        public Nullable<decimal> N_CURVE_RADIUS { get; set; }
        public string C_DIR { get; set; }
        public Nullable<decimal> N_MAX_GRADE { get; set; }
        public Nullable<decimal> N_GRADESECT_LEN { get; set; }
        public string C_RAIL_TYPE { get; set; }
        public Nullable<int> N_EXTEND_LINE { get; set; }
        public Nullable<int> N_EXTEN_JOINTLESS { get; set; }
        public Nullable<System.DateTime> T_CRT_TM { get; set; }
        public string C_CRT_NAME { get; set; }
        public string C_EFF_FLAG { get; set; }
        public Nullable<decimal> N_ORDER { get; set; }
        public string C_MEMO { get; set; }
    }
}
