//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_CURVE_PIC   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PKID { get; set; }
        public string WEARRAILPKID { get; set; }
        public string YEAR { get; set; }
        public string MONTH { get; set; }
        public string FILENAME { get; set; }
        public string LINKADDRESS { get; set; }
        public string WEARTYPE { get; set; }
        public Nullable<System.DateTime> UPLOADDATE { get; set; }
        public Nullable<System.DateTime> T_CRT_TM { get; set; }
        public string C_CRT_NAME { get; set; }
        public Nullable<decimal> N_ORDER { get; set; }
        public string C_MEMO { get; set; }
    }
}
