//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_RAIL_CARRIERSECTION_WARN   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string SECTION_ID { get; set; }
        public string SECTION_STATUS { get; set; }
        public Nullable<System.DateTime> RECORD_TIME { get; set; }
        public string IS_SHOW { get; set; }
    
        
    }
}
