//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_GATE_GATEMNG_INOUT   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string INOUT_ID { get; set; }
        public string GATE_NO { get; set; }
        public string CARD_NO { get; set; }
        public Nullable<System.DateTime> INOUT_TIME { get; set; }
        public string INOUT_FLAG { get; set; }
        public string READCARD_FLAG { get; set; }
        public string INOUT_STATE { get; set; }
        public string INOUT_LOG { get; set; }
        public string INOUT_ORDER { get; set; }
    }
}
