//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_LEDGER_SMALLEQUI_TECHPARAM   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PKID { get; set; }
        public string SBFL { get; set; }
        public string SBMC { get; set; }
        public string XHGG { get; set; }
        public string SCDW { get; set; }
        public string FDJ { get; set; }
        public string FDJ_XHGG { get; set; }
        public string FDJ_BJCJ { get; set; }
        public string FDJ_SL { get; set; }
        public string FDJ_LX { get; set; }
        public string FDJ_ZDSCGL { get; set; }
        public string FDJ_DS { get; set; }
        public string FDJ_HSPL { get; set; }
        public string FDJ_HYQ { get; set; }
        public string FDJ_CDJ { get; set; }
        public string FDJ_RY { get; set; }
        public string FDJ_ZXSCGL { get; set; }
        public string FDJ_HYL { get; set; }
        public string FDJ_YXRJ { get; set; }
        public string ZDFS { get; set; }
        public string GZJGZYJSCS { get; set; }
        public string RHZXHGG { get; set; }
        public string WXCC { get; set; }
        public string ZL { get; set; }
        public string DEPT_CODE { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string INPUT_USER { get; set; }
    }
}
