//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_HRAIL_RAIL   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string RAIL_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string CJ_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public string RUN_STATUS { get; set; }
        public string LINE_TYPE { get; set; }
        public string GAUGE_TYPE { get; set; }
        public Nullable<decimal> START_MILE { get; set; }
        public Nullable<decimal> END_MILE { get; set; }
        public string LONGCHAIN_MARKER { get; set; }
        public Nullable<int> SINGLERAIL_LENGTH { get; set; }
        public string RAIL_TYPE { get; set; }
        public string STEEK_TYPE { get; set; }
        public string MANUFACTURER { get; set; }
        public string MANUFACTURING_YEAR { get; set; }
        public string JOINT_STYLE { get; set; }
        public string IS_REUSERAIL { get; set; }
        public string RENOVATE_SITUATE { get; set; }
        public Nullable<System.DateTime> REPLACERAIL_YEAR { get; set; }
        public string GROSS_WEIGHT { get; set; }
        public string RAIL_IDENTITY { get; set; }
        public string FISHBOLT_LEVEL { get; set; }
        public string MEMO { get; set; }
    }
}
