//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_HRAIL_PLAN_ITEM   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string FLOW_ID { get; set; }
        public string PLAN_ID { get; set; }
        public string LOC_ID { get; set; }
        public string ITEM_ID { get; set; }
        public string ITEM_TYPE { get; set; }
        public string ITEM_CODE { get; set; }
        public decimal PLAN_NUM { get; set; }
        public decimal JOB_NUM { get; set; }
        public short CHECK_TYPE { get; set; }
        public string CHECK_PLAN_ID { get; set; }
        public short UNDERLINE_JOB { get; set; }
        public string MEMO { get; set; }
    }
}
