//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_SCRIPTS_SECTION_TRACK   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PKID { get; set; }
        public Nullable<int> ORD_NUM { get; set; }
        public string MAT_NAME { get; set; }
        public string TRACK_TYPE { get; set; }
        public string TRACK_UNIT { get; set; }
        public Nullable<int> TRACK_COUNT { get; set; }
        public string TRACK_ADDR { get; set; }
        public string TRACK_GROUP { get; set; }
        public string GWD_CODE { get; set; }
        public string CJ_CODE { get; set; }
        public string CRT_USER { get; set; }
        public Nullable<System.DateTime> CTR_TIME { get; set; }
        public string MEMO { get; set; }
    }
}
