//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_TASK_FLOOR   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PKID { get; set; }
        public string LINECODE { get; set; }
        public string LINEDIR { get; set; }
        public string LR { get; set; }
        public string LRCODE { get; set; }
        public string LICHENG { get; set; }
        public string NUMBERTYPE { get; set; }
        public string CAIZHI { get; set; }
        public string OPENTYPE { get; set; }
        public string CHICUN { get; set; }
        public Nullable<decimal> NUMBERS { get; set; }
        public string UNIT { get; set; }
        public string YN { get; set; }
        public string DEPTCODE { get; set; }
        public string GWDCODE { get; set; }
        public string MEMO { get; set; }
    }
}
