//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_RAIL_CARRIERWAVE_LOG   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PKID { get; set; }
        public string 手机号 { get; set; }
        public Nullable<System.DateTime> 时间 { get; set; }
        public string 主控站标识 { get; set; }
        public string 检测结果 { get; set; }
        public string 安装设备总数 { get; set; }
        public string 检测设备总数 { get; set; }
        public string 包总数 { get; set; }
        public string 包序号 { get; set; }
        public string 设备编号1 { get; set; }
        public string 幅值1 { get; set; }
        public string 轨温1 { get; set; }
        public string 电量1 { get; set; }
        public string 设备编号2 { get; set; }
        public string 幅值2 { get; set; }
        public string 轨温2 { get; set; }
        public string 电量2 { get; set; }
        public string 设备编号3 { get; set; }
        public string 幅值3 { get; set; }
        public string 轨温3 { get; set; }
        public string 电量3 { get; set; }
        public string LOG { get; set; }
    }
}
