//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_JOB_PLANCONTROL_COMMAND   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string DEPT_CODE_CJ { get; set; }
        public string DEPT_NAME_CJ { get; set; }
        public string ON_STATION_PRE { get; set; }
        public string DOWN_STATION_PRE { get; set; }
        public Nullable<System.DateTime> LAST_ONGET_TIME { get; set; }
        public Nullable<decimal> LASTON_STATION_ORDER { get; set; }
        public Nullable<decimal> LASTDOWN_STATION_ORDER { get; set; }
        public Nullable<System.DateTime> LAST_DOWNGET_TIME { get; set; }
    }
}
