//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_EMERGENCY_RESCUE_TOOL   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string TOOL_ID { get; set; }
        public string RESCUE_ID { get; set; }
        public string TOOL_TYPE { get; set; }
        public string TOOL_NAME { get; set; }
        public string TOOL_VERSION { get; set; }
        public string TOOL_UNIT { get; set; }
        public string TOOL_NUM { get; set; }
        public string TOOL_PLACE { get; set; }
        public string TOOL_TIME { get; set; }
        public string TOOL_STATU { get; set; }
        public string TOOL_PERSON { get; set; }
        public string TOOL_NOTES { get; set; }
    
        
    }
}
