//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_T_CAROBD   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string 手机号 { get; set; }
        public System.DateTime 时间 { get; set; }
        public Nullable<decimal> 油耗 { get; set; }
        public string 油耗单位 { get; set; }
        public Nullable<decimal> 里程 { get; set; }
        public Nullable<decimal> 速度 { get; set; }
        public Nullable<decimal> 剩余油量 { get; set; }
        public string 剩余油量单位 { get; set; }
        public Nullable<decimal> OIL_PRICE { get; set; }
        public string CAR_LICENSENO { get; set; }
        public Nullable<decimal> MILEAGE { get; set; }
        public string CHANGE_FLAG { get; set; }
        public Nullable<decimal> CHANGE_MILEAGE { get; set; }
        public string CHANGE_NOTE { get; set; }
    }
}
