//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_EMERGENCY_VIECHLE   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string VIECHLE_ID { get; set; }
        public string RWB_CODE { get; set; }
        public string RWB_NAME { get; set; }
        public string GWD_CODE { get; set; }
        public string GWD_NAME { get; set; }
        public string CJ_NAME { get; set; }
        public string GQ_NAME { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_NAME { get; set; }
        public string V_TAB_CAT { get; set; }
        public Nullable<decimal> V_RADIUS { get; set; }
        public Nullable<decimal> V_GRADIENT { get; set; }
        public Nullable<System.DateTime> V_DATETIME { get; set; }
        public string V_ADDR { get; set; }
        public string V_CONST { get; set; }
        public string VIECHLE_CODE { get; set; }
        public string BREAK_CAT { get; set; }
        public string V_WEATHER { get; set; }
        public string V_MA { get; set; }
        public string V_TRACOUNT { get; set; }
        public string V_DRIVER { get; set; }
        public string V_DEPT { get; set; }
        public string V_REMA { get; set; }
        public string V_REDRI { get; set; }
        public string V_VIECHLE { get; set; }
        public string VIECHLE_LEADER { get; set; }
        public string VIECHLE_NUM { get; set; }
        public string V_HAP { get; set; }
        public string V_CHECK { get; set; }
        public string V_REOLD { get; set; }
        public string V_DUTY { get; set; }
        public string VIECHLE_TYPE { get; set; }
        public string VIECHLE_ADDR { get; set; }
        public string A_REPAIR { get; set; }
        public string R_DEPT { get; set; }
        public string R_DATE { get; set; }
        public string F_REPAIR { get; set; }
        public string D_REPAIR { get; set; }
        public string AU_REPAIR { get; set; }
        public string T_REPAIR { get; set; }
        public string TYPE_NAME { get; set; }
        public string EMP_FUL { get; set; }
        public string STATION_FROM { get; set; }
        public string STATION_TO { get; set; }
        public string VIECHLE_CHECK { get; set; }
        public string CHECK_LIST { get; set; }
        public string BREAK_DIS { get; set; }
        public string DEV_BRE { get; set; }
        public string BRE_RES { get; set; }
        public string DU_DEPT { get; set; }
        public string REP_DEPT { get; set; }
        public string REP_NAME { get; set; }
        public string REP_DATE { get; set; }
        public string REP_NUM { get; set; }
        public string MARK { get; set; }
        public string REMARK { get; set; }
        public string MEMO { get; set; }
        public string R_DATEF { get; set; }
        public string R_DATED { get; set; }
        public string R_DATEAU { get; set; }
        public string R_DATET { get; set; }
        public string V_TAB_CODE { get; set; }
    }
}
