//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_HRAIL_PLAN_FLOW   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string FLOW_ID { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public short PLAN_CAT { get; set; }
        public short PLAN_TYPE { get; set; }
        public string PLAN_DATE { get; set; }
        public string CREATER { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATE_MEMBER { get; set; }
        public string CREATE_VIEW { get; set; }
        public short ISCREATE { get; set; }
        public string REPORTER { get; set; }
        public Nullable<System.DateTime> REPORTTIME { get; set; }
        public string REPORT_MEMBER { get; set; }
        public string REPORT_VIEW { get; set; }
        public short ISSUBMIT { get; set; }
        public short AUDITE_LEVEL { get; set; }
        public string AUDITER { get; set; }
        public Nullable<System.DateTime> AUDITTIME { get; set; }
        public string AUDIT_MEMBER { get; set; }
        public string AUDIT_VIEW { get; set; }
        public short ISAUDIT { get; set; }
        public short ISREJECT { get; set; }
        public string AUDITER2 { get; set; }
        public Nullable<System.DateTime> AUDIT2TIME { get; set; }
        public string AUDIT2_MEMBER { get; set; }
        public string AUDIT2_VIEW { get; set; }
        public short ISAUDIT2 { get; set; }
        public short ISREJECT2 { get; set; }
        public string AUDITER3 { get; set; }
        public Nullable<System.DateTime> AUDIT3TIME { get; set; }
        public string AUDIT3_MEMBER { get; set; }
        public string AUDIT3_VIEW { get; set; }
        public short ISAUDIT3 { get; set; }
        public short ISREJECT3 { get; set; }
        public short ISFINISHED { get; set; }
        public string REJECT_VIEW { get; set; }
        public string MEMO { get; set; }
        public short ISSEND { get; set; }
        public string SENDER { get; set; }
        public Nullable<System.DateTime> SENDTIME { get; set; }
        public string SENDER_MEMBER { get; set; }
        public string SENDER_VIEW { get; set; }
    }
}
