//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_TOOL_VIRTUAL_USE   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string SID { get; set; }
        public string JOB_NO { get; set; }
        public string USE_TOOL_ID { get; set; }
        public string USE_TOOL_NAME { get; set; }
        public Nullable<System.DateTime> USE_TOOL_TIME { get; set; }
        public Nullable<System.DateTime> RETURN_TOOL_TIME { get; set; }
        public string DEMO { get; set; }
        public Nullable<short> TOOL_STATU { get; set; }
    
        
    }
}
