//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_HRAIL_PLAN_LOC   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string FLOW_ID { get; set; }
        public string PLAN_ID { get; set; }
        public string LOC_ID { get; set; }
        public string DEPT_CODE { get; set; }
        public string PLAN_DATE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public string STATION_CODE { get; set; }
        public decimal START_MILE { get; set; }
        public decimal END_MILE { get; set; }
        public string TRACK_CODE { get; set; }
        public string TURNOUT_CODE { get; set; }
        public string BRIDGE_CODE { get; set; }
        public string JOB_LINE_CODE { get; set; }
        public string JOB_LINE_DIR { get; set; }
        public string JOB_STATION_CODE { get; set; }
        public decimal JOB_START_MILE { get; set; }
        public decimal JOB_END_MILE { get; set; }
        public string JOB_TRACK_CODE { get; set; }
        public string JOB_TURNOUT_CODE { get; set; }
        public string JOB_BRIDGE_CODE { get; set; }
        public string MEMO { get; set; }
    }
}
