//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_T_CZ_TJ_TEMP   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public decimal ID { get; set; }
        public Nullable<decimal> 单位 { get; set; }
        public Nullable<decimal> 个数 { get; set; }
        public Nullable<decimal> 同期 { get; set; }
        public string USER_CODE { get; set; }
    }
}
