//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_BRIDGE_BRIDGE   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string BRIDGE_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string CJ_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public decimal CENTER_MILE { get; set; }
        public string BRIDGE_CODE { get; set; }
        public string BRIDGE_NAME { get; set; }
        public string BRIDGE_SECTION { get; set; }
        public Nullable<short> TRACK_NUM { get; set; }
        public decimal FULL_LENGTH { get; set; }
        public decimal BRIDGE_LENGTH { get; set; }
        public decimal MAINTAINCE_LENGTH { get; set; }
        public string BUILD_YEAR { get; set; }
        public string HOLESPAN_STYLE { get; set; }
        public string BRIDGE_TYPE { get; set; }
        public string RUN_STATUS { get; set; }
        public string MEMO { get; set; }
        public string TEST_FLAG { get; set; }
        public string TEST_REPORT { get; set; }
    }
}
