//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_SYS_WARNLEVEL_DIC   
    {  
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string DIC_ID { get; set; }
        public string DIC_NAME { get; set; }
        public string DIC_ICON { get; set; }
        public Nullable<decimal> DIC_ORDER { get; set; }
        public string DEPT_CODE { get; set; }
        public string DIC_MEMO { get; set; }
        public string NOTE1 { get; set; }
        public string NOTE2 { get; set; }
    
        
    }
}
