//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_GATE_GATEMNG_INOUTHIS   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string CARD_NO { get; set; }
        public System.DateTime LST_TIME { get; set; }
        public string LST_ORDER { get; set; }
        public string CARD_TYPE { get; set; }
        public string CARD_SECTION { get; set; }
        public string INGATE_NO { get; set; }
        public Nullable<System.DateTime> INGATE_TIME { get; set; }
        public string OUTGATE_NO { get; set; }
        public Nullable<System.DateTime> OUTGATE_TIME { get; set; }
        public string GNAME { get; set; }
        public string GMOBILE { get; set; }
        public string GDEPTNAME { get; set; }
    }
}
