//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_HRAIL_TURNOUT   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string TURNOUT_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string CJ_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public string STATION_NAME { get; set; }
        public string STATION_CODE { get; set; }
        public string LINE_CAT { get; set; }
        public string RUN_STATUS { get; set; }
        public string TURNOUT_NO { get; set; }
        public string TURNOUT_TYPE { get; set; }
        public string GAUGE_TYPE { get; set; }
        public string GAUGE_MODEL { get; set; }
        public string CROSS_MARK { get; set; }
        public string LEFTRIGHT_OPEN { get; set; }
        public string RAIL_TYPE { get; set; }
        public string FROG_NO { get; set; }
        public string FROG_STRUCTURE { get; set; }
        public Nullable<int> FROG_LENGTH { get; set; }
        public string BLADE_TYPE { get; set; }
        public Nullable<int> BLADE_LEFTLEN { get; set; }
        public Nullable<int> BLADE_RIGHTLEN { get; set; }
        public Nullable<int> TURNOUT_LENGTH { get; set; }
        public string SWITCH_TYPE { get; set; }
        public string LOCK_TYPE { get; set; }
        public Nullable<int> BRANCH_NUM { get; set; }
        public Nullable<int> GENERAL_NUM { get; set; }
        public Nullable<int> CONCRETE_NUM { get; set; }
        public string C_NORULE { get; set; }
        public Nullable<decimal> BLADE_MILE { get; set; }
        public Nullable<int> H_SPEED { get; set; }
        public Nullable<int> V_SPEED { get; set; }
        public string LAY_YEAR { get; set; }
        public string PLAN_NO { get; set; }
        public string TRANPILLOW_TYPE { get; set; }
        public Nullable<int> TRANPILLOW_NUM { get; set; }
        public Nullable<int> FORKFRONT_RAILLEN { get; set; }
        public Nullable<int> FORKAFTER_RAILLEN { get; set; }
        public Nullable<decimal> FORKEND_MILE { get; set; }
        public string MEMO { get; set; }
    }
}
