//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_T_CHK_VISCHECK_ITEMS   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PKID { get; set; }
        public string CHECK_TYPE { get; set; }
        public string LINE_NAME { get; set; }
        public string LINE_DIR { get; set; }
        public Nullable<decimal> MILEAGE { get; set; }
        public string STATION_NAME { get; set; }
        public string TRACK_NUM { get; set; }
        public string TURNOUT_NO { get; set; }
        public string POS_NAME { get; set; }
        public string REPAIR_TM_CONTENT { get; set; }
        public string PHONE_NO { get; set; }
        public string CHK_NAME { get; set; }
        public Nullable<System.DateTime> CHK_TM { get; set; }
        public Nullable<System.DateTime> CRT_TM { get; set; }
        public string CRT_NAME { get; set; }
        public Nullable<System.DateTime> UPD_TM { get; set; }
        public string UPD_NAME { get; set; }
        public Nullable<decimal> SHOW_ORDER { get; set; }
        public Nullable<decimal> LNG { get; set; }
        public Nullable<decimal> LAT { get; set; }
        public Nullable<decimal> MARS_LNG { get; set; }
        public Nullable<decimal> MARS_LAT { get; set; }
        public Nullable<decimal> BAIDU_LNG { get; set; }
        public Nullable<decimal> BAIDU_LAT { get; set; }
        public Nullable<System.DateTime> GPS_TM { get; set; }
        public string CHECK_POS { get; set; }
        public string LINE_TYPE { get; set; }
    }
}
