//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_SYS_MEMBER   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string MEMBER_ID { get; set; }
        public string NAME { get; set; }
        public string MOBILE { get; set; }
        public string JOB { get; set; }
        public string PHONE { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string DEPT_CODE { get; set; }
        public string UPDATE_USER { get; set; }
        public string DEL_FLAG { get; set; }
        public string LOCATION_FLAG { get; set; }
        public string INTELLIGENCE { get; set; }
        public string POS_LEVEL { get; set; }
        public string MOBILE_STATE { get; set; }
    
        
        
        
        
        
        
        
        
        
    }
}
