//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_BRIDGE_TUNNEL   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string TUNNEL_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string CJ_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public decimal CENTER_MILE { get; set; }
        public string TUNNEL_CODE { get; set; }
        public string TUNNEL_NAME { get; set; }
        public decimal FULL_LENGTH { get; set; }
        public decimal MAINTAINCE_LENGTH { get; set; }
        public string RUN_STATUS { get; set; }
        public string MEMO { get; set; }
    }
}
