//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_BRIDGE_MAINTENAN_EVALUATE   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string EVALUATE_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string CJ_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public string EQU_CAT { get; set; }
        public decimal CENTER_MILE { get; set; }
        public string EQU_CODE { get; set; }
        public string EQU_NAME { get; set; }
        public Nullable<decimal> MAINTAINCE_LENGTH { get; set; }
        public Nullable<System.DateTime> EVALUATE_DATE { get; set; }
        public decimal AVG_SCORE { get; set; }
        public short EVALUATE_RES { get; set; }
        public string OVERRUN_PRO { get; set; }
        public Nullable<short> PRE_EVALUATE_RES { get; set; }
        public string NOTICE_ID { get; set; }
        public Nullable<short> NOTICE_IS_SEND { get; set; }
        public string MEMO { get; set; }
    }
}
