//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_BRIDGE_STATE_PRO_FILE   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PRO_FILE_ID { get; set; }
        public string PRO_ID { get; set; }
        public string FILE_CAT { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_DESC { get; set; }
        public System.DateTime CRT_TIME { get; set; }
    }
}
