//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_RAIN_SECTION_LINE   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string RAIN_SECTION_ID { get; set; }
        public Nullable<decimal> 经度 { get; set; }
        public Nullable<decimal> 纬度 { get; set; }
        public Nullable<decimal> 火星经度 { get; set; }
        public Nullable<decimal> 火星纬度 { get; set; }
        public Nullable<decimal> 百度经度 { get; set; }
        public Nullable<decimal> 百度纬度 { get; set; }
        public Nullable<decimal> MILEAGE { get; set; }
        public string 区段 { get; set; }
        public string 监测点 { get; set; }
        public string 路局 { get; set; }
        public Nullable<decimal> 起始里程 { get; set; }
        public Nullable<decimal> 结束里程 { get; set; }
        public string 执行车间 { get; set; }
        public string 执行工区 { get; set; }
        public string 工区编码 { get; set; }
        public Nullable<decimal> 工区中心里程 { get; set; }
        public string 出巡小里程方向手机号 { get; set; }
        public string 出巡大里程方向手机号 { get; set; }
        public string 行别 { get; set; }
        public Nullable<decimal> 区段编号 { get; set; }
    
        
    }
}
