//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_HRAIL_PLAN_EMP   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string FLOW_ID { get; set; }
        public string PLAN_ID { get; set; }
        public string PLAN_EMP_ID { get; set; }
        public string PLAN_DATE { get; set; }
        public string DEPT_CODE { get; set; }
        public short EMP_TOTAL { get; set; }
        public short ATTENDANCE { get; set; }
        public short HOLIDAY { get; set; }
        public short ON_RAILWAY { get; set; }
        public short IN_STATION { get; set; }
        public short CHEF { get; set; }
        public short DRIVER { get; set; }
        public short DOOR_GUARD { get; set; }
        public short EMP_OTHER { get; set; }
        public string MEMO { get; set; }
    }
}
