//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_LKJ_ROAD_FORK   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PKID { get; set; }
        public string BUREAU_NAME { get; set; }
        public string BUREAU_NUM { get; set; }
        public string LINE_NAME { get; set; }
        public string LINE_NUM { get; set; }
        public string LINE_DIR { get; set; }
        public string STATION_NAME { get; set; }
        public string STATION_NUM { get; set; }
        public string ROAD_FORK_NUM { get; set; }
        public string RAIL_TIP_MILEAGE { get; set; }
        public string FLOG_NUM { get; set; }
        public string ROAD_FORK_DIR { get; set; }
        public string LAYING_FIGURE_NUM { get; set; }
        public string MODIFY_TAG { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string USER_NAME { get; set; }
        public string DEPT_CODE { get; set; }
    }
}
