//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_TASK_CONSTRUCTION   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string CONSTRC_ID { get; set; }
        public string FKID { get; set; }
        public string GWD_CODE { get; set; }
        public string DEP_CODE { get; set; }
        public Nullable<System.DateTime> SYS_TIME { get; set; }
        public Nullable<decimal> CHECK_START { get; set; }
        public string CREATE_USER { get; set; }
        public string CHECK_USER { get; set; }
        public string AUDIT_USER { get; set; }
        public string ISSUE_USER { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<System.DateTime> CHECK_TIME { get; set; }
        public Nullable<System.DateTime> AUDIT_TIME { get; set; }
        public Nullable<System.DateTime> ISSUE_TIME { get; set; }
        public Nullable<System.DateTime> CONSTRC_TIME { get; set; }
        public string CONSTRC_SIGN { get; set; }
        public string CREATE_USERS { get; set; }
        public string CONTENT { get; set; }
    }
}
