//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_T_ASS_TQI_DETAIL   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PKID { get; set; }
        public string FKID { get; set; }
        public string C_GWD_CODE { get; set; }
        public string C_DEP_CODE { get; set; }
        public string C_DEP_NAME { get; set; }
        public string C_DEP_PROP { get; set; }
        public string C_LINE_CODE { get; set; }
        public string C_LINE_NAME { get; set; }
        public string C_LINE_DIR { get; set; }
        public string C_LINE_CAT { get; set; }
        public Nullable<decimal> N_PRO_MILE { get; set; }
        public string C_PRO_CODE { get; set; }
        public string C_PRO_NAME { get; set; }
        public string C_LEVEL { get; set; }
        public Nullable<decimal> N_TQI_PEAK { get; set; }
        public string C_TQI_OVER { get; set; }
        public Nullable<System.DateTime> D_CHECK_DATE { get; set; }
        public string C_JOB_FLAG { get; set; }
        public string C_JOB_NO { get; set; }
        public string C_REPAIR_FLAG { get; set; }
        public Nullable<System.DateTime> D_REPAIR_DATE { get; set; }
        public string C_REPAIR_RES { get; set; }
        public string C_DOC_FLAG { get; set; }
        public Nullable<System.DateTime> T_CRT_TM { get; set; }
        public string C_CRT_NAME { get; set; }
        public string C_EFF_FLAG { get; set; }
        public Nullable<decimal> N_ORDER { get; set; }
        public string C_MEMO { get; set; }
        public Nullable<decimal> N_PRO_PEAK { get; set; }
        public Nullable<decimal> N_SPEED { get; set; }
        public string N_SPEED_SPAN { get; set; }
    }
}
