//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_JOB_PLAN_DELINGHA_FILL_DETAIL   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PLAN_ID { get; set; }
        public string FILL_ID { get; set; }
        public string GQ_NAME { get; set; }
        public string REGISTER_STATION { get; set; }
        public string LINE_DIR { get; set; }
        public string SECTION_STATION { get; set; }
        public string JOB_MILE { get; set; }
        public string JOB_ITEM { get; set; }
        public string JOB_LEADER { get; set; }
        public string JOB_LEADER_PHONE { get; set; }
        public string LIAISON_MAN { get; set; }
        public string LIAISONMAN_PHONE { get; set; }
        public string WORKER_NUM { get; set; }
        public string MIGRANT_NUM { get; set; }
        public string MAIN_MACHING { get; set; }
        public string APPLY_DATE { get; set; }
        public string REPAIR_LEVEL { get; set; }
        public string DUAN_LEADER { get; set; }
        public string DEMO { get; set; }
        public Nullable<System.DateTime> CRT_TIME { get; set; }
        public string DEPCODE { get; set; }
        public Nullable<decimal> REJECT_NUM { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> FILL_NUM { get; set; }
        public Nullable<System.DateTime> PLAN_DATE { get; set; }
        public string CONTROL_VIEW { get; set; }
        public string CONTROL_POSTIL { get; set; }
        public Nullable<decimal> CONTROL_REJNUM { get; set; }
    }
}
