//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_HRAIL_PROBLEM_FILE   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PROBLEM_FILE_ID { get; set; }
        public string PROBLEM_ID { get; set; }
        public string CHECK_TYPE { get; set; }
        public string FILE_CAT { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_DESC { get; set; }
        public Nullable<System.DateTime> CRT_TIME { get; set; }
        public string CRT_NAME { get; set; }
    }
}
