//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_CURVE_BASE_EXT   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PKID { get; set; }
        public Nullable<decimal> RAILBRACE { get; set; }
        public Nullable<decimal> GAUGEROD { get; set; }
        public Nullable<System.DateTime> POLISHINGTIME { get; set; }
        public Nullable<decimal> GRINDINGCYCLE { get; set; }
        public string FLAGSOLIDOIL { get; set; }
        public string FLAGLIQUIDOIL { get; set; }
        public Nullable<decimal> OBSERVATIONQUANTITY { get; set; }
        public string HWEARPHOTO { get; set; }
        public string ALERTMESSAGE { get; set; }
        public Nullable<decimal> FLAGCHANGERAIL { get; set; }
        public Nullable<System.DateTime> T_CRT_TM { get; set; }
        public string C_CRT_NAME { get; set; }
        public Nullable<decimal> N_ORDER { get; set; }
        public string C_MEMO { get; set; }
        public Nullable<decimal> RAILTYPE { get; set; }
    }
}
