//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_T_ASS_FLOW_PROCESS   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PKID { get; set; }
        public string FLOWID { get; set; }
        public string PROCESS_ID { get; set; }
        public string UNIT_CODE { get; set; }
        public string DEPT_CODE { get; set; }
        public string USERID { get; set; }
        public short STEPID { get; set; }
        public string STEP_DESC { get; set; }
        public Nullable<short> STEP_STATUS { get; set; }
        public string ACTIONID { get; set; }
        public string ACTION_DESC { get; set; }
        public Nullable<short> ACTION_STATUS { get; set; }
        public Nullable<short> FLOW_STATUS { get; set; }
        public Nullable<short> NEXT_STEPID { get; set; }
        public string NEXT_DEPT_CODE { get; set; }
        public string NEXT_USERID { get; set; }
        public Nullable<short> BACK_STATUS { get; set; }
        public string BACK_DESC { get; set; }
        public string MEMO { get; set; }
        public Nullable<System.DateTime> CRT_TM { get; set; }
    }
}
