//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_T_LKJ_WIRINGDIAGRAM   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string GID { get; set; }
        public string RWBNAME { get; set; }
        public string RWBCODE { get; set; }
        public string LINECODE { get; set; }
        public string LINENAME { get; set; }
        public string STATIONCODE { get; set; }
        public string STATIONNAME { get; set; }
        public string FILEDESC { get; set; }
        public string FILENAME { get; set; }
        public string FILETYPE { get; set; }
        public string LINKURL { get; set; }
        public string ATTACHMENTNAME { get; set; }
        public string MARK { get; set; }
        public string REMARK { get; set; }
        public string MARKID { get; set; }
        public Nullable<System.DateTime> LASTDATE { get; set; }
    }
}
