//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_GATE_SEND_MSG   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public int ID { get; set; }
        public string 手机号 { get; set; }
        public string 内容 { get; set; }
        public Nullable<short> 类型 { get; set; }
        public Nullable<System.DateTime> 时间 { get; set; }
        public Nullable<short> 次数 { get; set; }
        public string 方式 { get; set; }
        public Nullable<short> 记录类型 { get; set; }
        public string 记录ID { get; set; }
    }
}
