//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_T_ASS_PROBLEM_HIS   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PKID { get; set; }
        public string FKID { get; set; }
        public string C_GWD_CODE { get; set; }
        public string C_DEP_CODE { get; set; }
        public string C_DEP_NAME { get; set; }
        public string C_DEP_PROP { get; set; }
        public string C_LINE_CODE { get; set; }
        public string C_LINE_NAME { get; set; }
        public string C_LINE_DIR { get; set; }
        public string C_LINE_CAT { get; set; }
        public string C_STATION_CODE { get; set; }
        public string C_STATION_NAME { get; set; }
        public string C_TRACK_CODE { get; set; }
        public string C_TURNOUT_CODE { get; set; }
        public string C_PRO_ITEM { get; set; }
        public string C_PRO_CODE { get; set; }
        public string C_PRO_NAME { get; set; }
        public Nullable<decimal> N_PRO_MILE { get; set; }
        public string C_PRO_PLACE { get; set; }
        public string C_PRO_DETAIL { get; set; }
        public decimal N_PRO_PEAK { get; set; }
        public short N_OVERRUN_LEVEL { get; set; }
        public string C_PRO_LEVEL { get; set; }
        public Nullable<short> N_SPEED { get; set; }
        public string C_INSPECTOR { get; set; }
        public string C_POST { get; set; }
        public Nullable<System.DateTime> D_CHECK_DATE { get; set; }
        public string C_JOB_FLAG { get; set; }
        public string C_JOB_NO { get; set; }
        public string C_REPAIR_FLAG { get; set; }
        public Nullable<System.DateTime> D_REPAIR_DATE { get; set; }
        public string C_REPAIR_RES { get; set; }
        public string C_CHECK_TYPE { get; set; }
        public string C_CHECK_DEV { get; set; }
        public string C_DOC_FLAG { get; set; }
        public string C_TRAIN_NO { get; set; }
        public string C_LOCO_NO { get; set; }
        public string C_MARK { get; set; }
        public string C_TRAIN_MODEL { get; set; }
        public string C_IS_MOTOR_CAR { get; set; }
        public Nullable<System.DateTime> T_CRT_TM { get; set; }
        public string C_CRT_NAME { get; set; }
        public Nullable<System.DateTime> T_UPD_TM { get; set; }
        public string T_UPD_NAME { get; set; }
        public string C_EFF_FLAG { get; set; }
        public Nullable<System.DateTime> T_EFF_TM { get; set; }
        public Nullable<decimal> N_ORDER { get; set; }
        public string C_MEMO { get; set; }
        public string C_LINE_SHARP { get; set; }
        public string C_ACCESS_FLAG { get; set; }
        public Nullable<System.DateTime> T_ACCESS_DATE { get; set; }
        public Nullable<short> N_REPEAT_NUM { get; set; }
        public string C_HIS_JOB_NO { get; set; }
        public Nullable<short> C_HIS_JOB_NUM { get; set; }
        public System.DateTime T_PRO_TM { get; set; }
        public string C_LINE_FEATURE { get; set; }
    }
}
