//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_GATE_GATEMNG_AUTHORIZATION   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string AUTHORIZATION_ID { get; set; }
        public string CARD_NO { get; set; }
        public string GATE_NO { get; set; }
        public Nullable<System.DateTime> AUTHORIZATIONTIME_BEGIN { get; set; }
        public Nullable<System.DateTime> AUTHORIZATIONTIME_END { get; set; }
        public string ISSUE_STATE { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public string TYPE { get; set; }
        public string PLAN_NO { get; set; }
        public string MEMBER_NAME { get; set; }
        public Nullable<System.DateTime> IN_TIME { get; set; }
        public Nullable<System.DateTime> OUT_TIME { get; set; }
        public string FLOW_ORDER { get; set; }
        public string TRAIN_NO { get; set; }
        public string WORK_NO { get; set; }
        public string TRAIN_MEMBER { get; set; }
        public string WORK_MEMBER { get; set; }
        public Nullable<System.DateTime> PLANTIME_BEGIN { get; set; }
        public Nullable<System.DateTime> PLANTIME_END { get; set; }
        public string CLIENT_NO { get; set; }
        public string GATE_CONVERTNO { get; set; }
        public string AUTHOPT_USER { get; set; }
        public Nullable<System.DateTime> AUTHOPT_TIME { get; set; }
        public string AUTHOPT_SECTION { get; set; }
        public string AUTHOPT_NOTE { get; set; }
        public string GATE_DEPTCODE { get; set; }
    
        
        
    }
}
