//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_TOOL_VIRTUAL_JOB_PLAN   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string JOB_NO { get; set; }
        public string JOB_NAME { get; set; }
        public Nullable<System.DateTime> JOB_CREATE { get; set; }
        public string PHONE { get; set; }
        public string DEMO { get; set; }
        public Nullable<short> JOB_STATE { get; set; }
        public string USE_PERSON { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public Nullable<short> JOB_FLAG { get; set; }
        public string NOTE { get; set; }
    
        
        
        
    }
}
