//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_T_ASS_PLAN_DATA_TEMP   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PLAN_ID { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string PLAN_CAT { get; set; }
        public short PLAN_ORDER { get; set; }
        public Nullable<int> PLAN_TOTAL { get; set; }
        public Nullable<int> PLAN_PASS { get; set; }
        public Nullable<int> PLAN_AUDIT { get; set; }
        public Nullable<int> PLAN_EDIT { get; set; }
        public Nullable<int> PLAN_REJECT { get; set; }
        public Nullable<int> PLAN_ARCHIVING { get; set; }
        public Nullable<int> PLAN_REPAIR { get; set; }
        public Nullable<int> PLAN_CONSTRUCT { get; set; }
        public Nullable<int> PLAN_CHECK { get; set; }
        public Nullable<int> PLAN_OTHER { get; set; }
        public Nullable<int> PLAN_WINDOW_REPAIR { get; set; }
        public Nullable<int> PLAN_WINDOW_CONSTRUCT { get; set; }
        public Nullable<int> PLAN_WINDOW_OTHER { get; set; }
        public Nullable<int> PLAN_WORKER { get; set; }
        public Nullable<int> PLAN_LABOUR { get; set; }
        public string MEMO { get; set; }
        public string PLAN_DATE { get; set; }
    }
}
