//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_RAIN_FLOOD_RESERVE_PLAN   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string RESERVEPLAN_ID { get; set; }
        public string GWD_CODE { get; set; }
        public string DEP_CODE { get; set; }
        public string GQ_CODE { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_NAME { get; set; }
        public Nullable<System.DateTime> UPLOAD_DATE { get; set; }
        public string WORD_URL { get; set; }
        public string DEMO { get; set; }
        public string WORD_TITLE { get; set; }
    }
}
