//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_SNOW_SECTION_LINE   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string SECTIONLINE_ID { get; set; }
        public string DEVICE_NO { get; set; }
        public string LINE_NAME { get; set; }
        public Nullable<decimal> MILE_BEGIN { get; set; }
        public Nullable<decimal> MILE_END { get; set; }
        public string SECTION_NAME { get; set; }
        public string MNG_NAME { get; set; }
        public string MNG_PHONENO { get; set; }
    
        
    }
}
