//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_T_WATER   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public decimal PKID { get; set; }
        public string 设备手机号 { get; set; }
        public Nullable<short> 设备编号 { get; set; }
        public Nullable<short> 传感器状态 { get; set; }
        public Nullable<System.DateTime> 时间 { get; set; }
        public string 报警级别 { get; set; }
        public Nullable<decimal> 水位 { get; set; }
    }
}
