//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_T_OILPOS   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string PKID { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_DIR { get; set; }
        public Nullable<decimal> MILEAGE { get; set; }
        public Nullable<System.DateTime> RECORD_TIME { get; set; }
        public string PHONE_NO { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public Nullable<decimal> MARSLONGITUDE { get; set; }
        public Nullable<decimal> MARSLATITUDE { get; set; }
        public Nullable<decimal> BAIDULONGITUDE { get; set; }
        public Nullable<decimal> BAIDULATITUDE { get; set; }
        public Nullable<decimal> SPEED { get; set; }
        public Nullable<decimal> DIRECTION { get; set; }
        public Nullable<decimal> SATELLITE_NO { get; set; }
        public string POS_MODE { get; set; }
        public string OP_ID { get; set; }
        public string OILPOS_MEMO { get; set; }
    }
}
