//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SxShWeb.Areas.ViewModels
{
     
    
    
    using System;
    using System.Collections.Generic;
         
    public partial class VIEW_RAIL_SOUNDRECEIVE_ORIDATA   
    { 
        public string page { get; set; }
        public string rows { get; set; }
        public string sort { get; set; }
        public string order { get; set; }
        public string editcellname { get; set; }
        public string DATA_ID { get; set; }
        public string 手机号 { get; set; }
        public Nullable<System.DateTime> 时间 { get; set; }
        public string 本区段左轨个数 { get; set; }
        public string 本区段左轨频率 { get; set; }
        public string 本区段左轨幅值 { get; set; }
        public string 本区段右轨个数 { get; set; }
        public string 本区段右轨频率 { get; set; }
        public string 本区段右轨幅值 { get; set; }
        public string 下区段左轨个数 { get; set; }
        public string 下区段左轨频率 { get; set; }
        public string 下区段左轨幅值 { get; set; }
        public string 下区段右轨个数 { get; set; }
        public string 下区段右轨频率 { get; set; }
        public string 下区段右轨幅值 { get; set; }
        public string 电源 { get; set; }
        public string 电压 { get; set; }
        public string 电池电压 { get; set; }
        public string ORILOG { get; set; }
    }
}
